### ISSUE TITLE
Server throws 500 error when metrics are added

### ISSUE THREAD

**Issue by smithkyle** [cachethq/Cachet#1035]
I have a brand new install of 2.0.0-beta2 that I've setup using docker. Everything works fine, but when I add a metric, the frontend starts serving a 500 error. The backend works ok, but the front end just gives the generic 500 internal server error.

**Comment by jbrooksuk** [comment]
Can you give me the appropriate error from the log file please? I guess it's because our Docker instance uses Postgresql and our repository for it is broken.

**Comment by smithkyle** [comment]
This is all I get in the /var/log/nginx/access.log file inside the container (nothing in error.log, and nothing in the docker hosts's nginx logs):

`172.17.42.1 - - [14/Oct/2015:16:27:57 +0000] "GET / HTTP/1.1" 500 3217 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"`

I am using a slightly modified docker-compose.yml file from yours with the following entries changed/added:

```
ports:
    - 8082:8000
env_file: mail.env
```

And a slightly modified Dockerfile from yours to download, extract, and remove the archive for https://github.com/cachethq/Cachet/archive/v2.0.0-beta2.tar.gz.

Thanks!

**Comment by jbrooksuk** [comment]
Sorry, I need the output from `./storage/logs/laravel-2015-10-14.log` please.

**Comment by smithkyle** [comment]
Ahh, sorry about that! Here it is:

```
[2015-10-14 16:49:55] production.ERROR: exception 'ErrorException' with message 'Undefined variable: hourInterval' in /var/www/html/app/Repositories/Metric/PgSqlRepository.php:102
Stack trace:
#0 /var/www/html/app/Repositories/Metric/PgSqlRepository.php(102): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/var/www/html/a...', 102, Array)
#1 /var/www/html/app/Repositories/Metric/MetricRepository.php(82): CachetHQ\Cachet\Repositories\Metric\PgSqlRepository->getPointsForDayInWeek(Object(CachetHQ\Cachet\Models\Metric), 0)
#2 /var/www/html/app/Composers/MetricsComposer.php(55): CachetHQ\Cachet\Repositories\Metric\MetricRepository->listPointsForWeek(Object(CachetHQ\Cachet\Models\Metric))
#3 [internal function]: CachetHQ\Cachet\Composers\MetricsComposer->CachetHQ\Cachet\Composers\{closure}(Object(CachetHQ\Cachet\Models\Metric), 0)
#4 /var/www/html/bootstrap/cache/compiled.php(12118): array_map(Object(Closure), Array, Array)
#5 /var/www/html/app/Composers/MetricsComposer.php(58): Illuminate\Support\Collection->map(Object(Closure))
#6 [internal function]: CachetHQ\Cachet\Composers\MetricsComposer->compose(Object(Illuminate\View\View))
#7 /var/www/html/bootstrap/cache/compiled.php(13927): call_user_func_array(Array, Array)
#8 [internal function]: Illuminate\View\Factory->Illuminate\View\{closure}(Object(Illuminate\View\View))
#9 /var/www/html/bootstrap/cache/compiled.php(9636): call_user_func_array(Object(Closure), Array)
#10 /var/www/html/bootstrap/cache/compiled.php(13940): Illuminate\Events\Dispatcher->fire('composing: inde...', Array)
#11 /var/www/html/bootstrap/cache/compiled.php(14313): Illuminate\View\Factory->callComposer(Object(Illuminate\View\View))
#12 /var/www/html/bootstrap/cache/compiled.php(14305): Illuminate\View\View->renderContents()
#13 /var/www/html/bootstrap/cache/compiled.php(15454): Illuminate\View\View->render()
#14 /var/www/html/bootstrap/cache/compiled.php(14969): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#15 /var/www/html/bootstrap/cache/compiled.php(7588): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#16 /var/www/html/bootstrap/cache/compiled.php(8815): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/bootstrap/cache/compiled.php(9472): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/bootstrap/cache/compiled.php(9454): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/html/bootstrap/cache/compiled.php(8816): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/html/bootstrap/cache/compiled.php(8801): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\StatusPageController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showIndex')
#23 /var/www/html/bootstrap/cache/compiled.php(7755): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showIndex')
#24 /var/www/html/bootstrap/cache/compiled.php(7726): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /var/www/html/bootstrap/cache/compiled.php(7379): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/bootstrap/cache/compiled.php(9472): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/html/app/Http/Middleware/Localize.php(70): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: CachetHQ\Cachet\Http\Middleware\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#31 /var/www/html/app/Http/Middleware/HasSetting.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: CachetHQ\Cachet\Http\Middleware\HasSetting->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/bootstrap/cache/compiled.php(9454): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/html/bootstrap/cache/compiled.php(7380): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /var/www/html/bootstrap/cache/compiled.php(7368): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#38 /var/www/html/bootstrap/cache/compiled.php(7353): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#39 /var/www/html/bootstrap/cache/compiled.php(2262): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/bootstrap/cache/compiled.php(9472): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /var/www/html/bootstrap/cache/compiled.php(12789): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#45 /var/www/html/bootstrap/cache/compiled.php(11412): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#48 /var/www/html/bootstrap/cache/compiled.php(12530): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#51 /var/www/html/bootstrap/cache/compiled.php(12469): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#54 /var/www/html/bootstrap/cache/compiled.php(2936): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#57 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/html/bootstrap/cache/compiled.php(9464): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/html/bootstrap/cache/compiled.php(9454): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /var/www/html/bootstrap/cache/compiled.php(2209): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /var/www/html/bootstrap/cache/compiled.php(2192): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main} {"identification":{"id":"22f8fd5c-bdb0-4ac1-b660-a5eb2886d948"}}
```

**Comment by jbrooksuk** [comment]
Cheers, I know the issue, I never finished `PgsqlRepository` :blush:

**Comment by sollidius** [comment]
Hey, I just installed Cachet on my Deb 7 OVZ VPS and getting the same issue. Is there a fix for this?

**Comment by jbrooksuk** [comment]
What version are you using?
