### ISSUE TITLE
subscriber emails not sent 

### ISSUE THREAD

**Issue by srikanth88infy** [cachethq/Cachet#1075]
Hi,

I have a Cachet instance running on Windows machine and I have configured a local smtp server to send emails. When I create an incident and ask to send emails to all subscribers, the functions seems to be broken. Could some one point me how to debug this issue? Also, where can I find smtp related logs?

**Comment by jbrooksuk** [comment]
Do you have anything in the `laravel.log` file? They're timestamped, so you'll have to find the most recent one.

**Comment by srikanth88infy** [comment]
@jbrooksuk  following is a snippet from my laravel log (if this helps!)
```
[2015-10-28 20:23:59] local.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in C:\wamp\www\cloudfire.status\app\Http\Middleware\Authenticate.php:48
Stack trace:
#0 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#13 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#16 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#19 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#22 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#25 C:\wamp\www\cloudfire.status\vendor\fideloper\proxy\src\TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 C:\wamp\www\cloudfire.status\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#32 C:\wamp\www\cloudfire.status\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 {main} {"identification":{"id":"a76d28cd-6f5f-4065-b8c1-c9d6ce5cfe62"}} 
```

**Comment by GrahamCampbell** [comment]
That doesn't look related to mail.

**Comment by jbrooksuk** [comment]
@srikanth88infy this error isn't useful to us I'm afraid. Is there anything else in there?

**Comment by srikanth88infy** [comment]
Hi @jbrooksuk i do not see any different logs being generated. Anyhow, I have created a new ubuntu vm and deployed Cachet. The emails work just perfect in the new environment! :) May be its a windows related issue rather than Cachet itself..

**Comment by jbrooksuk** [comment]
Ah yes, Windows will always somehow cause an issue with PHP/Laravel.
