### ISSUE TITLE
500 Error When Updating/Adding a Component

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#1104]
Logs are as follows:

```
[2015-11-07 11:17:02] local.ERROR: exception 'Illuminate\Bus\MarshalException' with message 'Unable to map parameter [enabled] to command [CachetHQ\Cachet\Commands\Component\AddComponentCommand]' in C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\MarshalException.php:21
Stack trace:
#0 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(163): Illuminate\Bus\MarshalException::whileMapping('CachetHQ\\Cachet...', Object(ReflectionParameter))
#1 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(132): Illuminate\Bus\Dispatcher->getParameterValueForCommand('CachetHQ\\Cachet...', Object(Illuminate\Support\Collection), Object(ReflectionParameter), Array)
#2 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(ReflectionParameter))
#3 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(133): array_map(Object(Closure), Array)
#4 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(113): Illuminate\Bus\Dispatcher->marshal('CachetHQ\\Cachet...', Object(Illuminate\Support\Collection), Array)
#5 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Bus\Dispatcher.php(88): Illuminate\Bus\Dispatcher->marshalFromArray('CachetHQ\\Cachet...', Array)
#6 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Bus\DispatchesJobs.php(29): Illuminate\Bus\Dispatcher->dispatchFromArray('CachetHQ\\Cachet...', Array)
#7 C:\Users\Administrator\Desktop\Cachet\app\Http\Controllers\Dashboard\ComponentController.php(179): CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController->dispatchFromArray('CachetHQ\\Cachet...', Array)
#8 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController->createComponentAction()
#9 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#10 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('createComponent...', Array)
#11 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController), Object(Illuminate\Routing\Route), 'createComponent...')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\ComponentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'createComponent...')
#18 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'createComponent...')
#19 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\Users\Administrator\Desktop\Cachet\app\Http\Middleware\Authenticate.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#30 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#31 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#33 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#37 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#40 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#43 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#46 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#49 C:\Users\Administrator\Desktop\Cachet\vendor\fideloper\proxy\src\TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 C:\Users\Administrator\Desktop\Cachet\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 C:\Users\Administrator\Desktop\Cachet\public\index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main} {"identification":{"id":"20ee2b73-300c-48fc-9d86-db8c9cf171a5"}} 
```

**Comment by jbrooksuk** [comment]
Thanks @TheoBearman, I'll look at this now.

**Comment by jbrooksuk** [comment]
Looks like the `enabled` field I added is missing from the dashboard forms. How the heck?

**Comment by jbrooksuk** [comment]
Sorry about this Theo, we're all fixed now.

**Comment by TheoBearman** [comment]
@jbrooksuk Just not good enough is it :expressionless:?

Of course I'm only joking @jbrooksuk. Thanks for the quick response and fix as always!

**Comment by jbrooksuk** [comment]
> @jbrooksuk Just not good enough is it :expressionless:?

Thing is, it's not. I think I ballsed up the rebase and lost a commit or something.

**Comment by TheoBearman** [comment]
Better find it now than later! Feel lucky for your lovely group of beta testers!

**Comment by jbrooksuk** [comment]
> Better find it now than later! Feel lucky for your lovely group of beta testers!

Indeed, thank you :) Oh I do, believe me!

**Comment by TheoBearman** [comment]
Well it is a pleasure to be involved in the project in my own small way.

I can confirm this fix is working.
