### ISSUE TITLE
v2.0.0-RC1 & v2.0.0-RC2: Setup throws [Object object]

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1111]
When i run the v2.0.0-RC1 in a Docker env (see https://github.com/cachethq/Docker/pull/15) and setup a new Cachet installation, i visit URL/setup first.

If you create a user and enter:
* Username: andy
* E-Mail: email@example.org
* Password: andy
and you hit "Complete setup", the error of the screenshot below appears.

If you hit "Complete setup" again, the same error appears again (below the first error box) and after half a second the setup finishes and the startpage of your Cachet installation will be shown.

<img width="1174" alt="screen shot 2015-11-07 at 21 14 31" src="https://cloud.githubusercontent.com/assets/320064/11017109/2538c81e-8595-11e5-8b61-afcd511c3194.png">

**Comment by GrahamCampbell** [comment]
Is this still broken in RC2?

**Comment by andygrunwald** [comment]
@GrahamCampbell Will test it. Gimme some minutes.

**Comment by GrahamCampbell** [comment]
Thanks.

**Comment by andygrunwald** [comment]
@GrahamCampbell Yep this is still broken in RC2 as well.

**Comment by GrahamCampbell** [comment]
Could you give us some more information please? Maybe the log entry for this?

**Comment by andygrunwald** [comment]
Browser: Google Chrome Version 46.0.2490.80 (64-bit)
OS: Mac OS X El Capitan (Version 10.11.1 (15B42))

<img width="1426" alt="screen shot 2015-11-07 at 21 50 57" src="https://cloud.githubusercontent.com/assets/320064/11017254/b231ee36-8599-11e5-94b3-691c0075229d.png">

<img width="1438" alt="screen shot 2015-11-07 at 21 52 30" src="https://cloud.githubusercontent.com/assets/320064/11017271/0395bb86-859a-11e5-9ab4-b498b52140ce.png">

<img width="1440" alt="screen shot 2015-11-07 at 21 52 58" src="https://cloud.githubusercontent.com/assets/320064/11017272/0398d762-859a-11e5-810e-61cb0c7c7db0.png">

To reproduce:
Apply https://github.com/cachethq/Docker/pull/15 to your Docker-Setup and execute:
```
$ docker build -t cachethq/docker:2.0.0-RC2 .
$ docker run --name mysql -e MYSQL_USER=$DB_USERNAME -e MYSQL_PASSWORD=$DB_PASSWORD  -e MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD -e MYSQL_DATABASE=$DB_DATABASE -d mysql
$ docker run -d --name cachet --link mysql:mysql -p 80:8000 -e DB_HOST=mysql -e DB_DATABASE=$DB_DATABASE -e DB_USERNAME=$DB_USERNAME -e DB_PASSWORD=$DB_PASSWORD cachethq/docker:2.0.0-RC2
$ docker exec -i cachet php artisan migrate --force
$ docker exec -it cachet php artisan key:generate
$ docker exec -it cachet php artisan config:cache
```

Is this enough?

**Comment by GrahamCampbell** [comment]
No, sorry. The only thing we need is the log file in the storage folder.

**Comment by andygrunwald** [comment]
Here you go:
```
[2015-11-07 21:14:45] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/var/www/html/.env): failed to open stream: Permission denied' in /var/www/html/app/Http/Controllers/SetupController.php:201
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/a...', 201, Array)
#1 /var/www/html/app/Http/Controllers/SetupController.php(201): file_put_contents('/var/www/html/....', 'APP_ENV=product...')
#2 /var/www/html/app/Http/Controllers/SetupController.php(166): CachetHQ\Cachet\Http\Controllers\SetupController->writeEnv('cache_driver', 'apc')
#3 [internal function]: CachetHQ\Cachet\Http\Controllers\SetupController->postStep3()
#4 /var/www/html/bootstrap/cache/compiled.php(8842): call_user_func_array(Array, Array)
#5 /var/www/html/bootstrap/cache/compiled.php(8911): Illuminate\Routing\Controller->callAction('postStep3', Array)
#6 /var/www/html/bootstrap/cache/compiled.php(8891): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\SetupController), Object(Illuminate\Routing\Route), 'postStep3')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /var/www/html/bootstrap/cache/compiled.php(8892): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/html/bootstrap/cache/compiled.php(8877): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\SetupController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postStep3')
#13 /var/www/html/bootstrap/cache/compiled.php(7831): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'postStep3')
#14 /var/www/html/bootstrap/cache/compiled.php(7802): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#15 /var/www/html/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/html/app/Http/Middleware/AppIsSetup.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: CachetHQ\Cachet\Http\Middleware\AppIsSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/html/bootstrap/cache/compiled.php(7456): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/html/bootstrap/cache/compiled.php(7444): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /var/www/html/bootstrap/cache/compiled.php(7429): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /var/www/html/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /var/www/html/bootstrap/cache/compiled.php(12881): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#32 /var/www/html/bootstrap/cache/compiled.php(11504): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#35 /var/www/html/bootstrap/cache/compiled.php(12622): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#38 /var/www/html/bootstrap/cache/compiled.php(12561): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#41 /var/www/html/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#44 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /var/www/html/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /var/www/html/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main} {"identification":{"id":"c02d245b-313b-4fa7-b3c1-c8ea778d8940"}}
```

**Comment by GrahamCampbell** [comment]
Ok, so it looks like your file permissions are wrong, which is why this isn't working.

**Comment by andygrunwald** [comment]
File permission?
From what file? What should be the correct file permission?
I am using https://github.com/cachethq/Docker. We can fix it there.

**Comment by GrahamCampbell** [comment]
The file permissions aren't something we can really fix. That's something you need to fix.

**Comment by andygrunwald** [comment]
Ok. @GrahamCampbell You are talking about /var/www/html/.env ?
This file will be copied. See https://github.com/cachethq/Docker/blob/master/Dockerfile#L16
So we can fix it there with a `chmod` or am i wrong?

**Comment by GrahamCampbell** [comment]
Not if the user you're running as doesn't have permission to do that.

**Comment by GrahamCampbell** [comment]
The don't need to chmod anyway, that would be a security risk. You need to chown it.

**Comment by andygrunwald** [comment]
@GrahamCampbell On the docker host machine? I mean i just clone the docker repo and hit docker build. Nothing more. IMO this should work out of the box. And the a few lines below we fire a chmod already.
The file on the host machine got already my user:
```
-rw-r--r--  1 agrunwald  staff   591 Nov  5 20:52 .env.docker
```

What are the correct file permissions here? What operations are executed on this file?

**Comment by GrahamCampbell** [comment]
The file permissions are correct already. The file ownership is what's wrong. The files need to be owned by the same user used in cli and to run the webserver. Or, you can tweak the file permissions, and have at least the same group.

**Comment by andygrunwald** [comment]
@GrahamCampbell Thanks!
I fixed the docker file. See https://github.com/cachethq/Docker/pull/16
After this it works perfect.
