### ISSUE TITLE
API: POST /api/v1/incidents throws 400 Bad Request

### ISSUE THREAD

**Issue by andygrunwald** [cachethq/Cachet#1112]
The command throws a 400 Bad Request, but the incident is created. with all information.
Tested on https://demo.cachethq.io/ + v2.0.0-RC2 Docker setup

```
$ curl -X POST -H "Content-Type: application/json;" -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR" -d '{"component_id":2,"name":"Incident","status":4,"visible":1,"message":"My\n\nMessage\n\n","created_at":"07/11/2015 12:20"}' https://demo.cachethq.io/api/v1/incidents
```

Response:
```
{
    "errors": [
        {
            "id": "28d8d086-ac3f-480d-b86f-069b276541ba",
            "status": 400,
            "title": "Bad Request",
            "detail": "The request cannot be fulfilled due to bad syntax."
        }
    ]
}
```

<img width="1200" alt="screen shot 2015-11-07 at 22 10 05" src="https://cloud.githubusercontent.com/assets/320064/11017340/592b05cc-859c-11e5-9b87-90c7354bf951.png">

**Comment by andygrunwald** [comment]
Here is a log report from my docker env:
```
2015-11-07 21:16:46] production.WARNING: exception 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException' in /var/www/html/app/Http/Controllers/Api/IncidentController.php:79
Stack trace:
#0 [internal function]: CachetHQ\Cachet\Http\Controllers\Api\IncidentController->postIncidents(Object(Illuminate\Auth\Guard))
#1 /var/www/html/bootstrap/cache/compiled.php(8842): call_user_func_array(Array, Array)
#2 /var/www/html/bootstrap/cache/compiled.php(8911): Illuminate\Routing\Controller->callAction('postIncidents', Array)
#3 /var/www/html/bootstrap/cache/compiled.php(8891): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Api\IncidentController), Object(Illuminate\Routing\Route), 'postIncidents')
#4 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#7 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 /var/www/html/bootstrap/cache/compiled.php(8892): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 /var/www/html/bootstrap/cache/compiled.php(8877): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Api\IncidentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postIncidents')
#10 /var/www/html/bootstrap/cache/compiled.php(7831): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'postIncidents')
#11 /var/www/html/bootstrap/cache/compiled.php(7802): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#12 /var/www/html/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /var/www/html/app/Http/Middleware/ApiAuthenticate.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: CachetHQ\Cachet\Http\Middleware\ApiAuthenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#18 /var/www/html/app/Http/Middleware/ApiOptionalAuthenticate.php(64): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: CachetHQ\Cachet\Http\Middleware\ApiOptionalAuthenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#21 /var/www/html/app/Http/Middleware/Timezone.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: CachetHQ\Cachet\Http\Middleware\Timezone->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#24 /var/www/html/app/Http/Middleware/Acceptable.php(34): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: CachetHQ\Cachet\Http\Middleware\Acceptable->handle(Object(Illuminate\Http\Request), Object(Closure), 'application/jso...')
#26 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /var/www/html/bootstrap/cache/compiled.php(7456): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/html/bootstrap/cache/compiled.php(7444): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /var/www/html/bootstrap/cache/compiled.php(7429): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /var/www/html/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/html/bootstrap/cache/compiled.php(9553): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/html/bootstrap/cache/compiled.php(12881): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#38 /var/www/html/bootstrap/cache/compiled.php(11504): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#41 /var/www/html/bootstrap/cache/compiled.php(12622): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#44 /var/www/html/bootstrap/cache/compiled.php(12561): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#47 /var/www/html/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#50 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /var/www/html/bootstrap/cache/compiled.php(9545): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /var/www/html/bootstrap/cache/compiled.php(9535): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /var/www/html/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /var/www/html/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main} {"identification":{"id":"e7aae2e8-bef3-4e54-a949-c265ad14608b"}}
```

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell on this.

**Comment by andygrunwald** [comment]
Small update:
If you add `component_status` into it, it works:
```
$ curl -X POST -H "Content-Type: application/json;" -H "X-Cachet-Token: 9yMHsdioQosnyVK4iCVR" -d '{"component_id":2,"name":"Incident","status":4,"visible":1,"message":"My\n\nMessage\n\n","component_status":1,"created_at":"07/11/2015 12:20"}' https://demo.cachethq.io/api/v1/incidents
```

Response:
```json
{
    "data": {
        "name": "Incident",
        "status": "4",
        "message": "My\n\nMessage",
        "visible": 1,
        "component_id": "2",
        "created_at": "2015-11-07 12:20:00",
        "updated_at": "2015-11-07 12:20:00",
        "id": 6,
        "human_status": "Fixed",
        "scheduled_at": "2015-11-08 11:02:35"
    }
}
```

See https://github.com/cachethq/Cachet/blob/master/app/Http/Controllers/Api/IncidentController.php#L74
Is this a required field? If not, maybe a default value should be added.

**Comment by jbrooksuk** [comment]
`component_status` is required if you specify `component_id`, otherwise it doesn't know what to update the status to.
