### ISSUE TITLE
Troubleshooting Cachet install 2

### ISSUE THREAD

**Issue by KeiroD** [cachethq/Cachet#1163]
Really? I have to open another issue because my currently closed issue is still not resolved?

Please see #1150 because the issue is NOT resolved.

**Comment by GrahamCampbell** [comment]
The error log pasted there seems unrelated to the install.

**Comment by GrahamCampbell** [comment]
I think your best bet is to start again, and make sure your config and file permissions are right before executing cachet,

**Comment by KeiroD** [comment]
Uhh... unrelated to the install? It sure seems to be related!

I fixed the permissions issue and it seems to me that Cachet is the issue, not permissions or environments.

You want login to the system so you can see for yourself?

See:

```
[2015-11-19 21:13:40] production.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/Cachet/app/Http/Middleware/Authenticate.php:50
Stack trace:
#0 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(7467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /var/www/Cachet/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /var/www/Cachet/bootstrap/cache/compiled.php(7440): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 /var/www/Cachet/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/Cachet/bootstrap/cache/compiled.php(12900): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#13 /var/www/Cachet/bootstrap/cache/compiled.php(11515): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#16 /var/www/Cachet/bootstrap/cache/compiled.php(12641): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#19 /var/www/Cachet/bootstrap/cache/compiled.php(12580): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#22 /var/www/Cachet/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#25 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/Cachet/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#32 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 {main} {"identification":{"id":"60654f9b-ae82-4c34-852b-b4548984b405"}}
[2015-11-19 21:14:34] production.ERROR: exception 'AltThree\Validator\ValidationException' with message 'Validation has failed.' in /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php:89
Validation errors:
The status field is required.
Stack trace:
#0 /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php(54): AltThree\Validator\ValidatingObserver->validate(Object(CachetHQ\Cachet\Models\Component))
#1 [internal function]: AltThree\Validator\ValidatingObserver->saving(Object(CachetHQ\Cachet\Models\Component))
#2 /var/www/Cachet/bootstrap/cache/compiled.php(9783): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Models\Component))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(9728): call_user_func_array(Object(Closure), Array)
#5 /var/www/Cachet/bootstrap/cache/compiled.php(9704): Illuminate\Events\Dispatcher->fire('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component), true)
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10482): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component))
#7 /var/www/Cachet/bootstrap/cache/compiled.php(10395): Illuminate\Database\Eloquent\Model->fireModelEvent('saving')
#8 /var/www/Cachet/bootstrap/cache/compiled.php(10375): Illuminate\Database\Eloquent\Model->save()
#9 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(258): Illuminate\Database\Eloquent\Model->update(Array)
#10 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->editIncidentAction(Object(CachetHQ\Cachet\Models\Incident))
#11 /var/www/Cachet/bootstrap/cache/compiled.php(8853): call_user_func_array(Array, Array)
#12 /var/www/Cachet/bootstrap/cache/compiled.php(8922): Illuminate\Routing\Controller->callAction('editIncidentAct...', Array)
#13 /var/www/Cachet/bootstrap/cache/compiled.php(8902): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), Object(Illuminate\Routing\Route), 'editIncidentAct...')
#14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(8903): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/Cachet/bootstrap/cache/compiled.php(8888): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'editIncidentAct...')
#20 /var/www/Cachet/bootstrap/cache/compiled.php(7842): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\Cachet...', 'editIncidentAct...')
#21 /var/www/Cachet/bootstrap/cache/compiled.php(7813): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#22 /var/www/Cachet/bootstrap/cache/compiled.php(7466): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/Cachet/app/Http/Middleware/Authenticate.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(7467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/Cachet/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(7440): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(12900): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#39 /var/www/Cachet/bootstrap/cache/compiled.php(11515): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#42 /var/www/Cachet/bootstrap/cache/compiled.php(12641): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#45 /var/www/Cachet/bootstrap/cache/compiled.php(12580): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#48 /var/www/Cachet/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#51 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main} {"identification":{"id":"a90e2b8d-99dd-4628-9aa0-58d874e1611c"}}
[2015-11-19 21:20:49] production.ERROR: exception 'AltThree\Validator\ValidationException' with message 'Validation has failed.' in /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php:89
Validation errors:
The status field is required.
Stack trace:
#0 /var/www/Cachet/vendor/alt-three/validator/src/ValidatingObserver.php(54): AltThree\Validator\ValidatingObserver->validate(Object(CachetHQ\Cachet\Models\Component))
#1 [internal function]: AltThree\Validator\ValidatingObserver->saving(Object(CachetHQ\Cachet\Models\Component))
#2 /var/www/Cachet/bootstrap/cache/compiled.php(9783): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Models\Component))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(9728): call_user_func_array(Object(Closure), Array)
#5 /var/www/Cachet/bootstrap/cache/compiled.php(9704): Illuminate\Events\Dispatcher->fire('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component), true)
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10482): Illuminate\Events\Dispatcher->until('eloquent.saving...', Object(CachetHQ\Cachet\Models\Component))
#7 /var/www/Cachet/bootstrap/cache/compiled.php(10395): Illuminate\Database\Eloquent\Model->fireModelEvent('saving')
#8 /var/www/Cachet/bootstrap/cache/compiled.php(10375): Illuminate\Database\Eloquent\Model->save()
#9 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(258): Illuminate\Database\Eloquent\Model->update(Array)
#10 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->editIncidentAction(Object(CachetHQ\Cachet\Models\Incident))
#11 /var/www/Cachet/bootstrap/cache/compiled.php(8853): call_user_func_array(Array, Array)
#12 /var/www/Cachet/bootstrap/cache/compiled.php(8922): Illuminate\Routing\Controller->callAction('editIncidentAct...', Array)
#13 /var/www/Cachet/bootstrap/cache/compiled.php(8902): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), Object(Illuminate\Routing\Route), 'editIncidentAct...')
#14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(8903): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/Cachet/bootstrap/cache/compiled.php(8888): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'editIncidentAct...')
#20 /var/www/Cachet/bootstrap/cache/compiled.php(7842): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\Cachet...', 'editIncidentAct...')
#21 /var/www/Cachet/bootstrap/cache/compiled.php(7813): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#22 /var/www/Cachet/bootstrap/cache/compiled.php(7466): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/Cachet/app/Http/Middleware/Authenticate.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(7467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/Cachet/bootstrap/cache/compiled.php(7455): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(7440): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/bootstrap/cache/compiled.php(2304): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(9564): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(12900): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#39 /var/www/Cachet/bootstrap/cache/compiled.php(11515): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#42 /var/www/Cachet/bootstrap/cache/compiled.php(12641): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#45 /var/www/Cachet/bootstrap/cache/compiled.php(12580): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#48 /var/www/Cachet/bootstrap/cache/compiled.php(2978): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#51 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(9556): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(9546): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(2251): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(2234): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main} {"identification":{"id":"9ccacb97-52aa-4a96-a7e5-e8147eca705f"}}
```

**Comment by KeiroD** [comment]
This happens on editing an incident.

Steps to reproduce:

Edit existing incident. Give it a name, a status, in this case, Fixed, visibility to public. The Investigating section label is set to Operational. I give it a time and message to display. As soon as I press Update, it results in a 500 and similar errors to the one I pasted.

**Comment by GrahamCampbell** [comment]
> This happens on editing an incident.

Unrelated to the install then. At least we're getting somewhere now.

**Comment by KeiroD** [comment]
I mentioned this in #1150 as well. The issue persisted although now I'm able to delete incidents, as mentioned in the previous issue.

So... what steps are necessary to resolve this issue?

**Comment by GrahamCampbell** [comment]
I think this is an existing validation issue I still need to fix.

**Comment by GrahamCampbell** [comment]
Could you please create a new issue and describe the bug please rather than linking to a log since it's very hard for us to keep track of bugs.

**Comment by KeiroD** [comment]
Sure.
