### ISSUE TITLE
Fatal Error After 2.1.0 Upgrade

### ISSUE THREAD

**Issue by mbabker** [CachetHQ/Cachet#1456]
Running `php artisan clear-compiled` after `composer install --no-dev -o`:

```
Fatal error: Uncaught ReflectionException: Class config does not exist in /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('config')
#1 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('config', Array)
#2 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('config', Array)
#3 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(46): Illuminate\Container\Container->__get('config')
#6 [internal function]: GrahamCampb in /var/www/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
```

This is an Ubuntu 14.04 box running PHP 7.0.3-2+deb.sury.org~trusty+1

**Comment by GrahamCampbell** [comment]
This is caused by a misconfigured .env file. If you have spaces around variables, you need to enclose it in double quotes. It is actually a bug that our previous version didn't throw an error. Before this error was being silently ignored, and the .env value was just getting ignored.

**Comment by mbabker** [comment]
:+1: All's good now, thanks!
