### ISSUE TITLE
Install issue with docker-compose

### ISSUE THREAD

**Issue by Moncleared** [CachetHQ/Cachet#1555]
Follow the steps outlined here: (Using docker-compose)
https://docs.cachethq.io/docs/get-started-with-docker

All steps completed successfully according to the output, containers start and appear to work fine. 

Expected Result:
Can reach http://a-domain-here/setup

Actual Result:
Received the error:
root@bfe766244874:/var/www/html/storage/logs# cat laravel-2016-02-24.log 
[2016-02-24 18:56:41] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/html/bootstrap/cache/compiled.php:7590
Stack trace:
#0 /var/www/html/bootstrap/cache/compiled.php(1331): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /var/www/html/bootstrap/cache/compiled.php(1287): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /var/www/html/bootstrap/cache/compiled.php(1837): Illuminate\Container\Container->make('encrypter', Array)
#3 /var/www/html/bootstrap/cache/compiled.php(1388): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /var/www/html/bootstrap/cache/compiled.php(1365): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/bootstrap/cache/compiled.php(1351): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/html/bootstrap/cache/compiled.php(1287): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 /var/www/html/bootstrap/cache/compiled.php(1837): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 /var/www/html/bootstrap/cache/compiled.php(9753): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/html/bootstrap/cache/compiled.php(9743): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/html/bootstrap/cache/compiled.php(8046): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/html/bootstrap/cache/compiled.php(8037): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#15 /var/www/html/bootstrap/cache/compiled.php(8027): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /var/www/html/bootstrap/cache/compiled.php(2381): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/html/bootstrap/cache/compiled.php(3210): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/html/bootstrap/cache/compiled.php(9753): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/bootstrap/cache/compiled.php(9753): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/bootstrap/cache/compiled.php(9743): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/html/bootstrap/cache/compiled.php(2328): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/html/bootstrap/cache/compiled.php(2312): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#34 {main} {"identification":{"id":"88df4838-c0da-4ae5-a598-d9a436ae0585"}} 
[2016-02-24 18:56:41] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/html/bootstrap/cache/compiled.php:7590
Stack trace:
#0 /var/www/html/bootstrap/cache/compiled.php(1331): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#1 /var/www/html/bootstrap/cache/compiled.php(1287): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /var/www/html/bootstrap/cache/compiled.php(1837): Illuminate\Container\Container->make('encrypter', Array)
#3 /var/www/html/bootstrap/cache/compiled.php(1388): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#4 /var/www/html/bootstrap/cache/compiled.php(1365): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/bootstrap/cache/compiled.php(1351): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/html/bootstrap/cache/compiled.php(1287): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 /var/www/html/bootstrap/cache/compiled.php(1837): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 /var/www/html/bootstrap/cache/compiled.php(2335): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 /var/www/html/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#10 {main} {"identification":{"id":"27bf4d31-eca9-4275-80bd-6e58ff5a3359"}}

**Comment by Moncleared** [comment]
Sorry, rm -rf bootstrap/cache/* resolved the issue. A bit confused as to why this would be required right out of the box though...
