### ISSUE TITLE
Error 503: Service Unavailable (Houston, We Have A Problem)

### ISSUE THREAD

**Issue by Srthk** [CachetHQ/Cachet#1613]
Encountering 503, after following the installation steps. Tried debugging through ./storage/logs/laravel-2016-03-15.log and got the below stack trace. Have reinstalled a few times as well.

Is there's something I'm missing? How to debug this?

Tried the following but it didn't work -
`sudo rm -rf bootstrap/cache/*`
rather it gave 500 error.
```
[2016-03-15 05:50:40] local.ERROR: exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $debug ]] in class GrahamCampbell\Exceptions\Filters\VerboseFilter' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839
Stack trace:
#0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\Container\Container->resolveNonClass(Object(ReflectionParameter))
#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->getDependencies(Array, Array)
#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('GrahamCampbell\\...', Array)
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('GrahamCampbell\\...', Array)
#4 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(183): Illuminate\Foundation\Application->make('GrahamCampbell\\...')
#5 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(165): GrahamCampbell\Exceptions\ExceptionHandler->make(Array)
#6 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(145): GrahamCampbell\Exceptions\ExceptionHandler->getFiltered(Array, Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException), Object(Symfony\Component\Debug\Exception\FatalErrorException), 500)
#7 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(112): GrahamCampbell\Exceptions\ExceptionHandler->getDisplayer(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException), Object(Symfony\Component\Debug\Exception\FatalErrorException), 500)
#8 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(89): GrahamCampbell\Exceptions\ExceptionHandler->getResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException), Object(Symfony\Component\Debug\Exception\FatalErrorException))
#9 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(107): GrahamCampbell\Exceptions\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalErrorException))
#10 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(84): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#11 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#12 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#13 {main} {"identification":{"id":"946df7ad-f5af-4ac6-8393-a593b5e29196"}} 
[2016-03-15 05:53:48] local.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:41
Stack trace:
#0 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#13 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#14 {main} {"identification":{"id":"54f6a0ac-2727-4bb3-acd0-624a9215edb3"}} 
```

**Comment by GrahamCampbell** [comment]
Looks like you ran the artisan down command, but not the up command.

The stack trace is not a "crash", that's just how we return 5xx responses.
