### ISSUE TITLE
500 errors after updating to 2.2.0

### ISSUE THREAD

**Issue by alexcroox** [CachetHQ/Cachet#1667]
After running the following:

```
root@962324:/var/www/html/Cachet# git pull
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

root@962324:/var/www/html/Cachet# rm -rf bootstrap/cache/*

root@962324:/var/www/html/Cachet# composer install -o --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!

root@962324:/var/www/html/Cachet# php artisan app:update
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!
```

I'm getting a 500 error page with the following in logs

```
[Sun Mar 27 14:29:13.594902 2016] [:error] [pid 23538] [client x.x.x.x:50399] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:13.597202 2016] [:error] [pid 23538] [client x.x.x.x:50399] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:18.593835 2016] [:error] [pid 23769] [client x.x.x.x:50401] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:18.596121 2016] [:error] [pid 23769] [client x.x.x.x:50401] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:23.601962 2016] [:error] [pid 23595] [client x.x.x.x:50403] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:23.603793 2016] [:error] [pid 23595] [client x.x.x.x:50403] PHP Fatal error:  Uncaught exception 'Illuminate\\Contracts\\Container\\BindingResolutionException' with message 'Unresolvable dependency resolving [Parameter #0 [ <required> $path ]] in class GrahamCampbell\\Exceptions\\ExceptionInfo' in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:839\nStack trace:\n#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(806): Illuminate\\Container\\Container->resolveNonClass(Object(ReflectionParameter))\n#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\\Container\\Container->getDependencies(Array, Array)\n#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\\Container\\Container->build('GrahamCampbell\\\\...', Array)\n#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\\Container\\Container->make('GrahamCampbell\\\\...', Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/ in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 839

[Sun Mar 27 14:29:28.616601 2016] [:error] [pid 1227] [client x.x.x.x:50405] PHP Parse error:  syntax error, unexpected '\\Encryptio', expecting \\\\ (T_NS_SEPARATOR) or ';' or '{' in /var/www/html/Cachet/bootstrap/cache/compiled.php on line 7635
```

I've also tried

```
root@962324:/var/www/html/Cachet# git pull origin v2.2.0
From https://github.com/cachethq/Cachet
 * tag               v2.2.0     -> FETCH_HEAD
Already up-to-date.

root@962324:/var/www/html/Cachet# rm -rf bootstrap/cache/*

root@962324:/var/www/html/Cachet# composer install -o --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
Generating optimized class loader
Compiling common classes
> php artisan config:cache
Configuration cache cleared!
Configuration cached successfully!
> php artisan route:cache
Route cache cleared!
Routes cached successfully!

root@962324:/var/www/html/Cachet# php artisan app:update
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
Nothing to migrate.
Clearing cache...
Application cache cleared!
Cache cleared!
```

**Comment by GrahamCampbell** [comment]
Try restarting the php fpm service?

**Comment by GrahamCampbell** [comment]
Also, can you run `cat VERSION` please?

**Comment by arosenhagen** [comment]
I ran into the same issue - seems its on the `APP_KEY`which is AES-256-CBC and therefore needs to be 32 in length. See http://laravel.io/forum/06-09-2015-no-supported-encrypter-found-the-cipher-and-or-key-length-are-invalid. Be aware that changing your `APP_KEY` will render your current data useless!
Also be aware that the standard value `SomeRandomString`is just 16 characters long, so maybe this should be updated in the docs and the example data.

**Comment by GrahamCampbell** [comment]
That issue is surely unrelated?

**Comment by GrahamCampbell** [comment]
> be updated in the docs and the example data.

Our docs clearly say that you need to set an encryption key before starting.

**Comment by jbrooksuk** [comment]
You should run `php artisan app:install` or `php artisan app:update` appropriately :)

**Comment by alexcroox** [comment]
```php artisan app:install``` fixed the issue for me!

**Comment by alexcroox** [comment]
OK not the /dashboard however

```
[Mon Mar 28 01:21:42.120770 2016] [:error] [pid 23660] [client 104.238.169.127:53154] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/Cachet/storage/logs/laravel-2016-03-28.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87\nStack trace:\n#0 /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(88): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Logger.php(643): Monolog\\Logger->addRecord(500, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->critical(Object(Sym in /var/www/html/Cachet/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 87
```

**Comment by bjshively** [comment]
@jbrooksuk - Just wanted to add a quick note here.

I've had some misc. issues with my install after upgrades, etc. that seem to very frequently trace back to permissions problems and were resolved by chmod +777'ing ./database/.. and ./storage/.. The most recent was giving me a 500 server error (not even the Laravel - Houston We Have a Problem, just a general 500 server error) with nothing being produced in the log files.

After trying many different permutations of artisan app:install, artisan config:cache, rm -rf ./bootstrap/cache, etc. I eventually resolved the issue via the permissions fix. I think adding a few more explicit debugging steps (permissions. config:cache, etc.) to the read me might result in fewer issues being filed here. Hope this is helpful!

**Comment by TheoBearman** [comment]
>  I think adding a few more explicit debugging steps (permissions. config:cache, etc.) to the read me might result in fewer issues being filed here.

Agreed. Happy to help create this if needed.

**Comment by jbrooksuk** [comment]
@bjshively, @TheoBearman this is definitely something we need to figure out. It's really annoying and the problem should be fixed at its core if possible.

**Comment by TheoBearman** [comment]
@jbrooksuk Drop me an email if this is something I can help with.

**Comment by bjshively** [comment]
I believe part of the issue is that permissions are lost during the git clone operations. This is exacerbated by the fact that instances are probably being hosted in places like /var/www/Cachet and a regular user may not have write permissions for this folder. Thus, the user will "solve" the initial clone problem with `sudo git clone ...` But, this will just introduce more issues going forward because the cloned repo will be owned by root (or some su) and so all of the commands to update, edit, repair, etc. or even write to the db will then require escalated privileges.

Possible solution: Maybe have some kind of deployment script that chmods things appropriately?

**Comment by TheoBearman** [comment]
Chmod might cause security issues but could we have chown commands bundled in to the composer scripts?

**Comment by jbrooksuk** [comment]
> but could we have chown commands bundled in to the composer scripts?

Not really because, Windows.

**Comment by TheoBearman** [comment]
Oh.
