### ISSUE TITLE
Problem updating component via API

### ISSUE THREAD

**Issue by dhorbach** [CachetHQ/Cachet#1708]
- *What version of Cachet?*
2.2.0
- *What database driver? MySQL? Postgres? SQLite?*
Postgres
- *What version of PHP?*
PHP 5.6.19-0+deb8u1 (cli) (built: Mar 14 2016 10:22:33)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

### Expected behaviour

PUT /api/v1/components/:id updates status

### Actual behaviour

Body:
```
{
    "status": 1
}
```

Error is thrown:
```
{
  "errors": [
    {
      "id": "246318c9-4ba8-4a7b-ab6f-779b2bce0537",
      "status": 500,
      "title": "Internal Server Error",
      "detail": "An error has occurred and this resource cannot be displayed."
    }
  ]
}
```
Other components API is working fine
### Stacktrace in laravel
```
[2016-04-20 18:06:42] development.ERROR: exception 'InvalidArgumentException' with message 'No connector for []' in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:172
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(155): Illuminate\Queue\QueueManager->getConnector(NULL)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(135): Illuminate\Queue\QueueManager->resolve('apc')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(65): Illuminate\Queue\QueueManager->connection()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Queue\QueueServiceProvider->Illuminate\Queue\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('queue.connectio...', Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('queue.connectio...')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(67): Illuminate\Container\Container->offsetGet('queue.connectio...')
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(34): Illuminate\Mail\MailServiceProvider->setMailerDependencies(Object(Illuminate\Mail\Mailer), Object(Illuminate\Foundation\Application))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(735): Illuminate\Mail\MailServiceProvider->Illuminate\Mail\{closure}(Object(Illuminate\Foundation\Application), Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build(Object(Closure), Array)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('mailer', Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): Illuminate\Container\Container->getDependencies(Array, Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('CachetHQ\\Cachet...', Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('CachetHQ\\Cachet...', Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(366): Illuminate\Foundation\Application->make('CachetHQ\\Cachet...')
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\Events\Dispatcher->createClassCallable('CachetHQ\\Cachet...', Object(Illuminate\Foundation\Application))
#19 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(419): Illuminate\Events\Dispatcher->fire(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent), Array, false)
#22 /var/www/html/app/Bus/Handlers/Commands/Component/UpdateComponentCommandHandler.php(33): event(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent))
#23 [internal function]: CachetHQ\Cachet\Bus\Handlers\Commands\Component\UpdateComponentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#24 /var/www/html/vendor/alt-three/bus/src/Dispatcher.php(225): call_user_func(Array, Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#25 [internal function]: AltThree\Bus\Dispatcher->AltThree\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#29 /var/www/html/vendor/alt-three/bus/src/Dispatcher.php(226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /var/www/html/vendor/alt-three/bus/src/Dispatcher.php(201): AltThree\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand), NULL)
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(323): AltThree\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#32 /var/www/html/app/Http/Controllers/Api/ComponentController.php(122): dispatch(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#33 [internal function]: CachetHQ\Cachet\Http\Controllers\Api\ComponentController->putComponent(Object(CachetHQ\Cachet\Models\Component))
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('putComponent', Array)
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Api\ComponentController), Object(Illuminate\Routing\Route), 'putComponent')
#37 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Api\ComponentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'putComponent')
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'putComponent')
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 /var/www/html/app/Http/Middleware/ApiAuthentication.php(67): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: CachetHQ\Cachet\Http\Middleware\ApiAuthentication->handle(Object(Illuminate\Http\Request), Object(Closure), 'true')
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /var/www/html/app/Http/Middleware/Timezone.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: CachetHQ\Cachet\Http\Middleware\Timezone->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /var/www/html/app/Http/Middleware/Acceptable.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: CachetHQ\Cachet\Http\Middleware\Acceptable->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /var/www/html/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#72 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#73 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#75 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#79 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#84 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#86 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#89 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#90 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#91 {main} {"identification":{"id":"3ee2bd39-b130-4300-84fb-f30bab812371"}}
```

**Comment by jbrooksuk** [comment]
Can we see your `.env` file please? It looks like your queue driver hasn't been set properly.

**Comment by GrahamCampbell** [comment]
Looks like you tried to use the `null` driver. That doesn't work. Please use `sync` instead.

**Comment by dhorbach** [comment]
@jbrooksuk @GrahamCampbell 

This is my .env
Installation - Docker based  de05cd6

```
root@0f6a15770831:/var/www/html# cat .env
APP_ENV=development
APP_DEBUG=true
APP_URL=http://localhost
APP_KEY=CMEVPsWCpPIKKdwikmu13YbNuIplxzK6

DB_DRIVER=pgsql
DB_HOST=postgres
DB_DATABASE=postgres
DB_USERNAME=postgres
DB_PASSWORD=postgres

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=apc

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null
```

**Comment by jbrooksuk** [comment]
`apc` is not a queue driver.

**Comment by dhorbach** [comment]
@jbrooksuk  - that means https://github.com/CachetHQ/Docker/blob/master/docker/entrypoint.sh has incorrect default value ?

```
CACHE_DRIVER=${CACHE_DRIVER:-apc}
  SESSION_DRIVER=${SESSION_DRIVER:-apc}
  QUEUE_DRIVER=${QUEUE_DRIVER:-apc}
```

**Comment by jbrooksuk** [comment]
It does, good spot! Could you open an issue over there please? 😄

**Comment by dhorbach** [comment]
Thanks changing queue driver to database fixed the problem

**Comment by jbrooksuk** [comment]
Thanks, I've set the default queue driver to `database` in the `entrypoint.sh` file.
