### ISSUE TITLE
exception 'InvalidArgumentException' with message 'No connector for []' in QueueManager.php

### ISSUE THREAD

**Issue by jrabbit** [CachetHQ/Cachet#1748]
### Your setup

- *What version of Cachet?* master
- *What database driver? MySQL? Postgres? SQLite?* Postgres 9.5
- *What version of PHP?* 5?

### Expected behaviour

Running a PUT on a created component, should respond 200

### Actual behaviour

PUT returns 500 error 
```
HTTP/1.1 500 Internal Server Error
Cache-Control: no-cache, private
Connection: keep-alive
Content-Type: application/json
Date: Wed, 04 May 2016 08:28:41 GMT
Server: nginx/1.9.3 (Ubuntu)
Transfer-Encoding: chunked

{
    "errors": [
        {
            "detail": "An error has occurred and this resource cannot be displayed.", 
            "id": "88bf2de4-86d6-4a6b-9a8c-09bbf40282ac", 
            "status": 500, 
            "title": "Internal Server Error"
        }
    ]
}

```
traceback:
```
[2016-05-04 08:31:02] development.ERROR: exception 'InvalidArgumentException' with message 'No connector for []' in /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php:172
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(155): Illuminate\Queue\QueueManager->getConnector(NULL)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(135): Illuminate\Queue\QueueManager->resolve('apc')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(146): Illuminate\Queue\QueueManager->connection(NULL)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(110): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '3')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(72): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, false)
#5 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#8 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main} {"identification":{"id":"2fad9d29-13c9-45e6-af50-cd2ef09c99aa"}} 
```

and I'm running cachet via docker-compose.

**Comment by GrahamCampbell** [comment]
> What version of PHP? 5?

Please be more specific.

**Comment by GrahamCampbell** [comment]
> What version of Cachet? master

Again, that's not very specific.

**Comment by GrahamCampbell** [comment]
Anyway, this "bug" occurs when you don't setup the queue config correctly.

**Comment by jrabbit** [comment]
https://github.com/CachetHQ/Docker/issues/63 ah
