### ISSUE TITLE
TLS Mail Server never completes

### ISSUE THREAD

**Issue by splitice** [CachetHQ/Cachet#1828]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [X] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [X] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [X] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?*
v2.2.2.

- *What database driver? MySQL? Postgres? SQLite?*
MySQL

- *What version of PHP?*
5.6.14

### Expected behaviour

Mail Sent

### Actual behaviour

Error, logged to syslog as:
```
exception 'Swift_TransportException' with message 'Connection to tcp://***:465 Timed Out'
```

### Steps to reproduce

Add a mail server that is connectible via TLS. A TCPDUMP shows that the script never initiates a SSL handshake after opening TCP connection, just sits there.

Relevant configuration for reference:
```
MAIL_DRIVER=smtp
MAIL_HOST=***
MAIL_PORT=465
MAIL_USERNAME=***
MAIL_PASSWORD=***
MAIL_ADDRESS=noreply@x4b.net
MAIL_NAME="Network Monitor"
MAIL_ENCRYPTION=tls
```

Im guessing its waiting for a response over a plain (non SSL/TLS) connection.

**Comment by GrahamCampbell** [comment]
Please upgrade to v2.3.0-RC1. It's fixed on there.

**Comment by splitice** [comment]
Nope. Upgraded to v2.3.0-RC1, mail isnt fixed.

```
May 26 04:05:18 web-dev laravel[27289]: production.ERROR: exception 'Swift_TransportException' with message 'Connection to tcp://***:465 Timed Out' in /var/www/cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:404 Stack trace: #0 /var/www/cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(289): Swift_Transport_AbstractSmtpTransport->_getFullResponse(0) #1 /var/www/cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(117): Swift_Transport_AbstractSmtpTransport->_readGreeting() #2 /var/www/cachet/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start() #3 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(386): Swift_Mailer->send(Object(Swift_Message), Array) #4 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(173): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message)) #5 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(278): Illuminate\Mail\Mailer->send(Array, Array, Object(Closure)) #6 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\SyncJob), Array) #7 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\Queue\Jobs\Job->resolveAndFire(Array) #8 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\Queue\Jobs\SyncJob->fire() #9 /var/www/cachet/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(189): Illuminate\Queue\SyncQueue->push('mailer@handleQu...', Array, NULL) #10 /var/www/cachet/app/Bus/Handlers/Events/Subscriber/SendSubscriberVerificationEmailHandler.php(59): Illuminate\Mail\Mailer->queue(Array, Array, Object(Closure)) #11 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\Subscriber\SendSubscriberVerificationEmailHandler->handle(Object(CachetHQ\
```

**Comment by GrahamCampbell** [comment]
DO you have a valid cert on the server?
