### ISSUE TITLE
500 Error on Subscribers Page

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#1858]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* 2.3.0-dev
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* 5.6.11

### Expected behaviour

The normal subscribers page.

### Actual behaviour

500 error thrown:

```
[2016-05-29 09:46:07] local.WARNING: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/html/Cachet/app/Http/Middleware/Authenticate.php:51
Stack trace:
#0 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /var/www/html/Cachet/bootstrap/cache/compiled.php(3203): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/html/Cachet/bootstrap/cache/compiled.php(13355): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/www/html/Cachet/bootstrap/cache/compiled.php(11901): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /var/www/html/Cachet/bootstrap/cache/compiled.php(13094): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /var/www/html/Cachet/bootstrap/cache/compiled.php(13031): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/html/Cachet/bootstrap/cache/compiled.php(9891): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/html/Cachet/bootstrap/cache/compiled.php(8172): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/html/Cachet/bootstrap/cache/compiled.php(8163): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 /var/www/html/Cachet/bootstrap/cache/compiled.php(8153): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /var/www/html/Cachet/bootstrap/cache/compiled.php(2409): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/html/Cachet/bootstrap/cache/compiled.php(3264): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/Cachet/bootstrap/cache/compiled.php(9906): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/html/Cachet/bootstrap/cache/compiled.php(9891): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /var/www/html/Cachet/bootstrap/cache/compiled.php(2356): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 /var/www/html/Cachet/bootstrap/cache/compiled.php(2340): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 /var/www/html/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main} {"identification":{"id":"e0b0ef03-3aaf-43a7-b06d-4f280634dd09"}} 
[2016-05-29 09:46:10] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function subscribes_enabled()' in /var/www/html/Cachet/storage/framework/views/0aff1b1181c3affdfff88759ea89c53ddd72a645.php:10
Stack trace:
#0 {main} {"identification":{"id":"6f1aeff9-516c-482d-9e9f-f93080c088f3"}} 
[2016-05-29 09:48:27] local.CRITICAL: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function subscribes_enabled()' in /var/www/html/Cachet/storage/framework/views/0aff1b1181c3affdfff88759ea89c53ddd72a645.php:10
Stack trace:
#0 {main} {"identification":{"id":"c2c85c86-976b-4e80-bcbc-6e8cd99c3230"}} 
```

**Comment by GrahamCampbell** [comment]
That error log isn't for an error 500. It's for a 401?

**Comment by GrahamCampbell** [comment]
Oh, right, I see, the bottom of the log.

**Comment by GrahamCampbell** [comment]
@TheoBearman Thanks for reporting. I've prepared a PR that fixes this.

**Comment by TheoBearman** [comment]
:trollface:
