### ISSUE TITLE
500 error on opening subscribers page

### ISSUE THREAD

**Issue by Srthk** [CachetHQ/Cachet#1912]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [x] You're running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [x] Ensure that you're running at least PHP 5.5.9, you can check this by running `php -v`
- [x] You've ran `rm -rf bootstrap/cache/*` from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

### Your setup

- *What version of Cachet?* v2.3.0-RC6
- *What database driver? MySQL? Postgres? SQLite?* MySQL
- *What version of PHP?* PHP 5.6.17

### Expected behaviour

The subscribers page

### Actual behaviour

500 error.

```
[2016-06-16 12:44:47] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/Cachet/stora
ge/framework/views/a86c4441ae4a3fd7832736d64ea2ba280427f1a7.php:39
Stack trace:
#0 /var/www/Cachet/storage/framework/views/a86c4441ae4a3fd7832736d64ea2ba280427f1a7.php(39): Illuminate\Foundation\Bootstrap\HandleExceptions->
handleError(8, 'Trying to get p...', '/var/www/Cachet...', 39, Array)
#1 [internal function]: Illuminate\View\Engines\PhpEngine->{closure}(Object(CachetHQ\Cachet\Models\Subscription), 0)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(12662): array_map(Object(Closure), Array, Array)
#3 /var/www/Cachet/storage/framework/views/a86c4441ae4a3fd7832736d64ea2ba280427f1a7.php(40): Illuminate\Support\Collection->map(Object(Closure)
)
#4 /var/www/Cachet/bootstrap/cache/compiled.php(15167): include('/var/www/Cachet...')
#5 /var/www/Cachet/bootstrap/cache/compiled.php(15204): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/Cachet...', Array)
#6 /var/www/Cachet/bootstrap/cache/compiled.php(15036): Illuminate\View\Engines\CompilerEngine->get('/var/www/Cachet...', Array)
#7 /var/www/Cachet/bootstrap/cache/compiled.php(15024): Illuminate\View\View->getContents()
#8 /var/www/Cachet/bootstrap/cache/compiled.php(15008): Illuminate\View\View->renderContents()
#9 /var/www/Cachet/bootstrap/cache/compiled.php(16251): Illuminate\View\View->render()
#10 /var/www/Cachet/bootstrap/cache/compiled.php(15747): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#11 /var/www/Cachet/bootstrap/cache/compiled.php(8339): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#12 /var/www/Cachet/bootstrap/cache/compiled.php(9434): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illu
minate\View\View))
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#15 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(9435): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(9422): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Co
ntrollers\Dashboard\SubscriberController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showSubscribers')
#19 /var/www/Cachet/bootstrap/cache/compiled.php(8490): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Obj
ect(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showSubscribers')
#20 /var/www/Cachet/bootstrap/cache/compiled.php(8477): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#21 /var/www/Cachet/bootstrap/cache/compiled.php(8191): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#24 /var/www/Cachet/app/Http/Middleware/Authenticate.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\
Request))
#25 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#29 /var/www/Cachet/bootstrap/cache/compiled.php(3222): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reques
t))
#30 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#34 /var/www/Cachet/bootstrap/cache/compiled.php(13369): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#35 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#39 /var/www/Cachet/bootstrap/cache/compiled.php(11912): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(13108): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#45 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#49 /var/www/Cachet/bootstrap/cache/compiled.php(13045): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#50 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#54 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(8192): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(8183): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object
(Illuminate\Http\Request))
#58 /var/www/Cachet/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#59 /var/www/Cachet/bootstrap/cache/compiled.php(2416): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#62 /var/www/Cachet/bootstrap/cache/compiled.php(3283): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reques
t))
#63 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)
)
#64 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#67 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminat
e\Http\Request))
#68 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#70 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#72 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 /var/www/Cachet/bootstrap/cache/compiled.php(2363): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /var/www/Cachet/bootstrap/cache/compiled.php(2347): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Requ
est))
#76 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#77 {main}


Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/Cachet/resources/views/dashboard/subscribers
/index.blade.php)' in /var/www/Cachet/storage/framework/views/a86c4441ae4a3fd7832736d64ea2ba280427f1a7.php:39
Stack trace:
#0 /var/www/Cachet/bootstrap/cache/compiled.php(15169): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/Cachet/bootstrap/cache/compiled.php(15204): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/Cachet...', Array)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(15036): Illuminate\View\Engines\CompilerEngine->get('/var/www/Cachet...', Array)
#3 /var/www/Cachet/bootstrap/cache/compiled.php(15024): Illuminate\View\View->getContents()
#4 /var/www/Cachet/bootstrap/cache/compiled.php(15008): Illuminate\View\View->renderContents()
#5 /var/www/Cachet/bootstrap/cache/compiled.php(16251): Illuminate\View\View->render()
#6 /var/www/Cachet/bootstrap/cache/compiled.php(15747): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/Cachet/bootstrap/cache/compiled.php(8339): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/Cachet/bootstrap/cache/compiled.php(9434): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illum
inate\View\View))
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/Cachet/bootstrap/cache/compiled.php(9435): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(9422): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Co
ntrollers\Dashboard\SubscriberController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showSubscribers')
#15 /var/www/Cachet/bootstrap/cache/compiled.php(8490): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Obj
ect(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showSubscribers')
#16 /var/www/Cachet/bootstrap/cache/compiled.php(8477): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(8191): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#20 /var/www/Cachet/app/Http/Middleware/Authenticate.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\
Request))
#21 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#25 /var/www/Cachet/bootstrap/cache/compiled.php(3222): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reques
t))
#26 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(13369): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(11912): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#40 /var/www/Cachet/bootstrap/cache/compiled.php(13108): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#45 /var/www/Cachet/bootstrap/cache/compiled.php(13045): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque
st))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/Cachet/bootstrap/cache/compiled.php(8192): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(8183): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object
(Illuminate\Http\Request))
#54 /var/www/Cachet/bootstrap/cache/compiled.php(8173): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(2416): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#58 /var/www/Cachet/bootstrap/cache/compiled.php(3283): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reques
t))
#59 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure)
)
#60 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#63 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminat
e\Http\Request))
#64 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/Cachet/bootstrap/cache/compiled.php(9926): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Re
quest))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/Cachet/bootstrap/cache/compiled.php(9911): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /var/www/Cachet/bootstrap/cache/compiled.php(2363): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /var/www/Cachet/bootstrap/cache/compiled.php(2347): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Requ
est))
#72 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main} {"identification":{"id":"961d7613-fc11-4751-b6b6-21c511848393"}} 

```
### Steps to reproduce

Trying to access the subscribers page (where x.y.z points to my status page) -
http://x.y.z/dashboard/subscribers

Similar issue is occurring if someone goes to something like this - http://x.y.z/subscribe/manage/k3ScHDJ1vhV0VIIzo1sEg6YsM6WsdKeCDiytdUJflN

Is this related to this issue - https://github.com/CachetHQ/Cachet/issues/1858

I checked the file at this page - resources/views/dashboard/subscribers/index.blade.php and the change was present parallel to this commit (https://github.com/CachetHQ/Cachet/pull/1859/commits/021c2890d29f42ed06b70dc00693ddcdfeea2611)

**Comment by jbrooksuk** [comment]
Did you upgrade from 2.2? If so, did you run `php artisan app:update`?

**Comment by jbrooksuk** [comment]
I'm afraid that I'm unable to replicate this issue, unless the migrations are out of date. Can you run that and see where you get to please.

**Comment by Srthk** [comment]
I upgraded from 2.1.2. Yes, I ran `php artisan app:update` the first time around only and it still threw the same error. I created a new branch from the latest tag, it still failed to work (I followed steps in here - https://docs.cachethq.io/docs/updating-cachet). 

Could you suggest something from the logs I printed, how can I resolve this?

**Comment by jbrooksuk** [comment]
I could do with more log information please.

We do provide Cachet installations if that helps. Email support@alt-three.com for more information.

**Comment by Srthk** [comment]
So, I I upgraded from v2.1.2 to v2.3.1 and http:/status.mysite.com/dashboard/subscribers is returning 500. 

I ran `php artisan migrate`, it returned `Nothing to migrate.`

I took a dump of my database. Did a fresh installation of v2.3.1, tested subscribers page and everything was working fine (added a few subscribers as well) and tested the page.

Then I pointed the app to my older db, and ran `php artisan migrate`, it again returned `Nothing to migrate.` and 500 error on loading subscribers page.

So, I feel there's some compatibility issue in migrating from v2.1.2 to v2.3.1. The database I was using with v2.1.2 is not working with v2.3.1 (failing on subscribers page with the error log given by me in my previous message) whereas v2.3.1 with a fresh installation is working fine. 

I checked the schema for `subscribers` and `subscriptions` table, it was the same in older and new database. I want to run the latest version with my old databases without any issue, how do I achieve this?

**Comment by Srthk** [comment]
On debugging, the issue was there were because of few entries in the `subscriptions` table where entries existed with `subscriber_id` which were deleted and entries of `component_id` which were also deleted. On deleting such rows from `subscriptions` table, the 500 error stopped in v2.3.1. Anyhow it was working fine in v2.1.2 with such entries. But I believe this could have been handled better.
