### ISSUE TITLE
Can't leave the  /setup

### ISSUE THREAD

**Issue by chaica** [CachetHQ/Cachet#2006]
Before submitting your issue, please make sure that you've checked the checkboxes below.

- [x ] I am running the [latest release](https://github.com/CachetHQ/Cachet/releases/latest) version of Cachet.
- [ x] I am running at least PHP 5.5.9. *You can check this by running `php -v`.*
- [ x] I have ran `rm -rf bootstrap/cache/*`.

### Expected behaviour
Use Cachet

### Actual behaviour

The setup completed, gave me access to /dashboard, but any time I disconnect from dashboard, I'm back on /setup 
Clearing cache rm -rf bootstrap/cache only takes me back to /setup

### Steps to reproduce

*If your issue requires any specific steps to reproduce, please outline them here.*

1. checkout github repository
2. checkout the last tag
3. follow the install procedure
4. complete the setup
5. try to disconnect from the dashboard
6. you're back to /setup whatever I try execept using /dashboard

Let me know if you need more information.
Regards,
Carl

**Comment by ccosentino** [comment]
The following worked for someone else with a similar problem. 

My suggestion is to start fresh. Here are the commands that seemed to work for me on one of the last few times I installed it. I saved my .env file in my home directory so I could quickly copy it over to the cloned repo, which is what the `cp ~/env.txt ./.env` line is. You should edit your env at that point and add your values.

```
cd /var/www
git clone https://github.com/cachethq/Cachet.git
cd Cachet
git checkout v2.3.6
chmod -R 777 storage
chmod -R 777 bootstrap
cp ~/env.txt ./.env
chmod 777 .env
composer install --no-dev -o
php artisan key:generate
php artisan app:install 
rm -rf bootstrap/cache/*
```
Then open your browser and go to the site (assuming you set up the virtual host config already)

EDIT: mode 777 is probably not secure. I haven't dug through the real permissions required yet. I am assuming the apache process user needs write permission where I 777'd. I just wanted to get it working. It is on an intranet so not a huge security hole for me.

**Comment by GrahamCampbell** [comment]
Thank. This is a duplicate of https://github.com/CachetHQ/Cachet/issues/1996 though. Please check for existing issues first.

**Comment by praneet12** [comment]
I am trying to setup 2.3.6 tags and done all the steps.

Output Logs 

```
[Thu Aug  9 12:49:30 2018] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/praneet....', 51, Array)
#1 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
[Thu Aug  9 12:49:30 2018] ::1:59923 [500]: /dashboard - Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/praneet....', 51, Array)
#1 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
[Thu Aug  9 12:49:30 2018] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/Users/praneet....', 51, Array)
#1 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /Users/praneet.drolia/Cachet/bootstrap/cache/compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Componen in /Users/praneet.drolia/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51




```
