### ISSUE TITLE
Error in composer install

### ISSUE THREAD

**Issue by mnapoli** [CachetHQ/Cachet#2098]
I just downloaded the latest version and ran `composer install --no-dev -o`, here is what I got at the end:

> TL/DR: Uncaught ErrorException: require(XXX/cachet/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory

```
> Illuminate\Foundation\ComposerScripts::postInstall
PHP Warning:  Uncaught ErrorException: require(/Users/matthieu/dev/cachet/vendor/composer/../symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory in /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php:66
Stack trace:
#0 /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/Users/...', '/Users/matthieu...', 66, Array)
#1 /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php(66): require()
#2 /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php(56): composerRequire554572665491c3ca7e1fcb218e54ffcd('667aeda72477189...', '/Users/matthieu...')
#3 /Users/matthieu/dev/cachet/vendor/autoload.php(7): ComposerAutoloaderInit554572665491c3ca7e1fcb218e54ffcd::getLoader()
#4 /Users/matthieu/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(17): require_once('/Users/matthieu...')
#5 phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDi in /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php on line 66
PHP Stack trace:
PHP   1. {main}() /usr/local/Cellar/composer/1.1.2/libexec/composer.phar:0
PHP   2. require() /usr/local/Cellar/composer/1.1.2/libexec/composer.phar:24
PHP   3. Composer\Console\Application->run() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/bin/composer:43
PHP   4. Symfony\Component\Console\Application->run() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/Console/Application.php:102
PHP   5. Composer\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/vendor/symfony/console/Application.php:123
PHP   6. Symfony\Component\Console\Application->doRun() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/Console/Application.php:227
PHP   7. Symfony\Component\Console\Application->doRunCommand() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/vendor/symfony/console/Application.php:192
PHP   8. Symfony\Component\Console\Command\Command->run() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/vendor/symfony/console/Application.php:844
PHP   9. Composer\Command\InstallCommand->execute() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/vendor/symfony/console/Command/Command.php:259
PHP  10. Composer\Installer->run() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/Command/InstallCommand.php:133
PHP  11. Composer\EventDispatcher\EventDispatcher->dispatchScript() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/Installer.php:296
PHP  12. Composer\EventDispatcher\EventDispatcher->doDispatch() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:95
PHP  13. Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:209
PHP  14. Illuminate\Foundation\ComposerScripts::postInstall() phar:///usr/local/Cellar/composer/1.1.2/libexec/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:255
PHP  15. require_once() /Users/matthieu/dev/cachet/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php:17
PHP  16. ComposerAutoloaderInit554572665491c3ca7e1fcb218e54ffcd::getLoader() /Users/matthieu/dev/cachet/vendor/autoload.php:7
PHP  17. composerRequire554572665491c3ca7e1fcb218e54ffcd() /Users/matthieu/dev/cachet/vendor/composer/autoload_real.php:56
```

**Comment by yoyosan** [comment]
Did you get the latest from [releases](https://github.com/CachetHQ/Cachet/releases)?
Because I just ran the command and it finished just fine.

Maybe try first
```
composer dump-autoload
```

then

```
composer install --no-dev -o
```
?

**Comment by jbrooksuk** [comment]
Are you upgrading from a previous release?

**Comment by mnapoli** [comment]
Nope I really just downloaded the zip and run composer install. I noticed some directories in vendor were empty (symfony ones for example)… Weird, looks like a Composer error (1.1.something). I upgraded PHP (7) and Composer and still the same result. Tried clearing `vendor` and reinstalling, same.

**Comment by mnapoli** [comment]
I just tried from a different PC and it works… Maybe I need to clear my Composer cache or something…

Sorry everyone!
