### ISSUE TITLE
Scheduled Maintenance Calendar Function

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2324]
Running 2.4.0-Dev
Currently the Scheduled Maintenance section is just a plain text box but it requires a date to be added in the following format: ('Y-m-d H:i') otherwise a 500 error will occur on saving the item and the following error will be logged:

 ```
   [2017-01-23 17:19:53] production.ERROR: InvalidArgumentException: Unexpected data found.
    Unexpected data found.
    Data missing in /var/www/Cachet/vendor/nesbot/carbon/src/Carbon/Carbon.php:582
    Stack trace:
    #0 /var/www/Cachet/app/Dates/DateFactory.php(65): Carbon\Carbon::createFromFormat
('Y-m-d H:i', '01/02/2017', 'Europe/London')
```

Perhaps a calendar date picker can be integrated into the form to avoid any initial confusion, or as a workaround some text above the text-box stating the required date format?

Otherwise I fear people will get confused, especially those of us not used to the US date format.

**Comment by jbrooksuk** [comment]
There should be a date picker there...

**Comment by jbrooksuk** [comment]
Do you not see this?

![](https://cldup.com/QJruKXKXC2.png)

**Comment by max-l-weaver** [comment]
Oh, erm no I don't.
I just see a plain ol' text box.


![image](https://cloud.githubusercontent.com/assets/22293003/22241924/597a025a-e219-11e6-9c38-d66926c0eacf.png)

**Comment by jbrooksuk** [comment]
How weird! Do you have any console errors?

**Comment by ConnorVG** [comment]
Or, possibly, do you have JavaScript disabled?

**Comment by max-l-weaver** [comment]
I have the following console errors. Sorry but as I have to remove the address:

```Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at s (https://cachet..com/build/dist/js/all-74bb70763d.js:14:10869)
    at t (https://cachet..com/build/dist/js/all-74bb70763d.js:14:10202)
    at n (https://cachet..com/build/dist/js/all-74bb70763d.js:14:11996)
    at https://cachet..com/build/dist/js/all-74bb70763d.js:14:12799
    at ae.fn.init.forEach (native)
    at s (https://cachet..com/build/dist/js/all-74bb70763d.js:14:12760)
    at HTMLDocument.<anonymous> (https://cachet..com/build/dist/js/all-74bb70763d.js:22:15888)
    at u (https://cachet..com/build/dist/js/all-74bb70763d.js:2:6477)
    at Object.fireWith [as resolveWith] (https://cachet..com/build/dist/js/all-74bb70763d.js:2:7245)
    at Function.ready (https://cachet..com/build/dist/js/all-74bb70763d.js:2:9062)```

**Comment by max-l-weaver** [comment]
@ConnorVG JS definitely enabled

**Comment by jbrooksuk** [comment]
What browser/OS are you using?

**Comment by max-l-weaver** [comment]
Chrome 55.0.2883.95
macOS Sierra 10.12.2

**Comment by equero** [comment]
Exactly like @max-l-weaver here, but not in firefox..

**Comment by max-l-weaver** [comment]
@equero are you saying it **did** work in FF? Just tried it in FF and same problem.

**Comment by jbrooksuk** [comment]
This is fixed now.
