### ISSUE TITLE
500 Error when updating incidents

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2340]
Cachet Version: 2.4.0-Dev
OS: Ubuntu 16.04
PHP: 7.1
Laravel Framework version 5.3.29

We're getting a 500 error when updating incidents. This seems to only apply to incidents that notify via email as I cannot replicate with non-notifying test incidents.

Latest extract from log:

```
[2017-02-02 11:19:36] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification::__construct() must be an instance of CachetHQ\Cachet\Models\IncidentUpdate, instance of CachetHQ\Cachet\Models\Incident given, called in /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php on line 77 in /var/www/Cachet/app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php:46
Stack trace:
#0 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(77): CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification->__construct(Object(CachetHQ\Cachet\Models\Incident))
#1 /var/www/Cachet/bootstrap/cache/compiled.php(12809): CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\{closure}(Object(CachetHQ\Cachet\Models\Subscriber), 26)
#2 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(78): Illuminate\Support\Collection->each(Object(Closure))
#3 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->handle(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(10322): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10256): call_user_func_array(Object(Closure), Array)
#7 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('CachetHQ\\Cachet...')
#8 /var/www/Cachet/app/Bus/Handlers/Commands/IncidentUpdate/ReportIncidentUpdateCommandHandler.php(61): event(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#9 /var/www/Cachet/bootstrap/cache/compiled.php(9947): CachetHQ\Cachet\Bus\Handlers\Commands\IncidentUpdate\ReportIncidentUpdateCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#10 /var/www/Cachet/bootstrap/cache/compiled.php(10066): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#11 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#12 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#13 /var/www/Cachet/bootstrap/cache/compiled.php(11956): Illuminate\Database\Connection->transaction(Object(Closure))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(6468): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#15 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#16 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand), Object(Closure))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(9954): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/Cachet/bootstrap/cache/compiled.php(9940): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#20 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(373): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#21 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(315): dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#22 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->createIncidentUpdateAction(Object(CachetHQ\Cachet\Models\Incident))
#23 /var/www/Cachet/bootstrap/cache/compiled.php(9574): call_user_func_array(Array, Array)
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9601): Illuminate\Routing\Controller->callAction('createIncidentU...', Array)
#25 /var/www/Cachet/bootstrap/cache/compiled.php(8655): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'createIncidentU...')
#26 /var/www/Cachet/bootstrap/cache/compiled.php(8636): Illuminate\Routing\Route->runController()
#27 /var/www/Cachet/bootstrap/cache/compiled.php(8345): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(10167): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(3312): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(13739): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(12145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(13485): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(13422): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/Cachet/bootstrap/cache/compiled.php(8346): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/Cachet/bootstrap/cache/compiled.php(8337): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(8328): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /var/www/Cachet/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/Cachet/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/Cachet/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main} {"identification":{"id":"6acb15e4-43ec-491a-9b46-08d6acbbe9c8"}} 
```

**Comment by GrahamCampbell** [comment]
Please upgrade to the latest 2.4.x. I think this was already fixed.

**Comment by protogonfs** [comment]
Hello,

I was able to fix the issue in this way:

- Open "app/Bus/Commands/Component/UpdateComponentCommand.php" in text editor

- Go to line 121

- Rewrite the function without the $silent parameter, comment it out inside the function too.

This is my new function after the changes I've made:

```
public function __construct(Component $component, $name, $description, $status, $link, $order, $group_id, $enabled, $meta)
    {
        $this->component = $component;
        $this->name = $name;
        $this->description = $description;
        $this->status = (int) $status;
        $this->link = $link;
        $this->order = $order;
        $this->group_id = $group_id;
        $this->enabled = $enabled;
        $this->meta = $meta;
//        $this->silent = $silent;
    }
```

I hope this will help :)

Bye
