### ISSUE TITLE
Updating an incident throws 500 error

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2378]
We're currently on the latest commit under 2.4 branch and are experiencing issues when updating incidents.

For example, go to dashboard>Incident>Update
Click on 'Fixed' radio button
Hit 'Update'
Throws 500 error.

The most annoying thing is it emails our subs saying the component has been updated, however when they go to view the status it is still showing as previous update.

Log below:

```
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.actions' doesn't exist (SQL: insert into `actions` (`class_name`, `user_id`, `username`, `description`, `updated_at`, `created_at`) values (CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent, 1, max.weaver, Incident was updated., 2017-02-20 12:01:39, 2017-02-20 12:01:39)) in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:770
Stack trace:
#0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#3 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#4 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2154): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1470): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10991): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 /var/www/Cachet/bootstrap/cache/compiled.php(10977): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /var/www/Cachet/bootstrap/cache/compiled.php(10931): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 /var/www/Cachet/bootstrap/cache/compiled.php(10589): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/Cachet/app/Bus/Handlers/Events/ActionStorageHandler.php(47): Illuminate\Database\Eloquent\Model::create(Array)
#11 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\ActionStorageHandler->handle(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent))
#12 /var/www/Cachet/bootstrap/cache/compiled.php(10322): call_user_func_array(Array, Array)
#13 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(10256): call_user_func_array(Object(Closure), Array)
#15 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('CachetHQ\\Cachet...')
#16 /var/www/Cachet/app/Bus/Handlers/Commands/Incident/UpdateIncidentCommandHandler.php(104): event(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(9947): CachetHQ\Cachet\Bus\Handlers\Commands\Incident\UpdateIncidentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(10066): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#19 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#20 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#21 /var/www/Cachet/bootstrap/cache/compiled.php(11956): Illuminate\Database\Connection->transaction(Object(Closure))
#22 /var/www/Cachet/bootstrap/cache/compiled.php(6468): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#23 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#24 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand), Object(Closure))
#25 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#26 /var/www/Cachet/bootstrap/cache/compiled.php(9954): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /var/www/Cachet/bootstrap/cache/compiled.php(9940): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#28 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(373): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#29 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(251): dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\UpdateIncidentCommand))
#30 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->editIncidentAction(Object(CachetHQ\Cachet\Models\Incident))
#31 /var/www/Cachet/bootstrap/cache/compiled.php(9574): call_user_func_array(Array, Array)
#32 /var/www/Cachet/bootstrap/cache/compiled.php(9601): Illuminate\Routing\Controller->callAction('editIncidentAct...', Array)
#33 /var/www/Cachet/bootstrap/cache/compiled.php(8655): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'editIncidentAct...')
#34 /var/www/Cachet/bootstrap/cache/compiled.php(8636): Illuminate\Routing\Route->runController()
#35 /var/www/Cachet/bootstrap/cache/compiled.php(8345): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#36 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/Cachet/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/Cachet/bootstrap/cache/compiled.php(10167): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/Cachet/bootstrap/cache/compiled.php(3312): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/Cachet/bootstrap/cache/compiled.php(13739): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/Cachet/bootstrap/cache/compiled.php(12145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/Cachet/bootstrap/cache/compiled.php(13485): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/bootstrap/cache/compiled.php(13422): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/Cachet/bootstrap/cache/compiled.php(8346): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /var/www/Cachet/bootstrap/cache/compiled.php(8337): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#61 /var/www/Cachet/bootstrap/cache/compiled.php(8328): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#62 /var/www/Cachet/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#63 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#64 /var/www/Cachet/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 /var/www/Cachet/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#72 /var/www/Cachet/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#73 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#74 {main} {"identification":{"id":"aa95659b-9684-4e7e-ae18-f0468a7a547f"}} 
```

**Comment by jbrooksuk** [comment]
The log is telling you the issue:

```
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.actions' doesn't exist (SQL: insert into `actions` (`class_name`, `user_id`, `username`, `description`, `updated_at`, `created_at`) values (CachetHQ\Cachet\Bus\Events\Incident\IncidentWasUpdatedEvent, 1, max.weaver, Incident was updated., 2017-02-20 12:01:39, 2017-02-20 12:01:39)) in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:770
```

You need to run `php artisan app:update` which will run the database migrations.

**Comment by max-l-weaver** [comment]
Thanks! Not sure how I could have come to that conclusion as obviously as you'd suggest from that line, but then again I'm not a developer.
