### ISSUE TITLE
Install Cachet on Heroku

### ISSUE THREAD

**Issue by saamo** [CachetHQ/Cachet#2391]
Hey guys, could anyone of you please tell me how to install it on Heroku step-by-step? I'm lost.

**Comment by brianjking** [comment]
@saamo -- AFAIK Cachet is no longer supported on Heroku. Check out #557 and [this blog post](https://blog.alt-three.com/dropping-native-heroku-support/).

If you're looking for a good PaaS that you can use with Cachet with an easy installer checkout [Openshift](https://www.openshift.com/) using [Openshift Cachet](https://github.com/ALinuxNinja/openshift-cachet) by @ALinuxNinja.

**Comment by jbrooksuk** [comment]
Yeah, Cachet no longer officially supports Heroku. 

Brian's comment should help other directions though.

**Comment by saamo** [comment]
Thanks, guys. I know that there is no Heroku Button anymore... But how can I install Cachet on Heroku manually? Is it even possible to run it successfully? I'm stuck on this now:

```
2017-03-02T22:04:15.935149+00:00 app[web.1]: [02-Mar-2017 22:04:15 UTC] [2017-03-02 22:04:15] production.ERROR: ErrorException: file_put_contents(/tmp/build_285d9e929ce0a78a18ef0231c0c45f79/storage/framework/sessions/cl1cL2apv5UtmoJSmPIKoYTmm6CQqZQOQ5C8Ic22): failed to open stream: No such file or directory in /app/bootstrap/cache/compiled.php:7512
2017-03-02T22:04:15.935185+00:00 app[web.1]: Stack trace:
2017-03-02T22:04:15.935314+00:00 app[web.1]: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/app/bootstrap/...', 7512, Array)
2017-03-02T22:04:15.935409+00:00 app[web.1]: #1 /app/bootstrap/cache/compiled.php(7512): file_put_contents('/tmp/build_285d...', 'a:4:{s:6:"_toke...', 2)
2017-03-02T22:04:15.935547+00:00 app[web.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/tmp/build_285d...', 'a:4:{s:6:"_toke...', true)
2017-03-02T22:04:15.935662+00:00 app[web.1]: #3 /app/bootstrap/cache/compiled.php(12345): Illuminate\Session\FileSessionHandler->write('cl1cL2apv5UtmoJ...', 'a:4:{s:6:"_toke...')
2017-03-02T22:04:15.935732+00:00 app[web.1]: #4 /app/bootstrap/cache/compiled.php(12165): Illuminate\Session\Store->save()
2017-03-02T22:04:15.935868+00:00 app[web.1]: #5 /app/bootstrap/cache/compiled.php(2531): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
2017-03-02T22:04:15.935949+00:00 app[web.1]: #6 /app/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
2017-03-02T22:04:15.936000+00:00 app[web.1]: #7 {main} {"identification":{"id":"3561b0b6-5d52-4e3c-9d8c-868aa9c04ffc"}}
```

**Comment by mkhorton** [comment]
Openshift Cachet is no longer maintained. Do you have any other suggestions for easy deployment?

**Comment by jbrooksuk** [comment]
Cachet itself should be fairly easy to install on a simple VPS. There is also the Docker repo.
