### ISSUE TITLE
500 Error when updating incident

### ISSUE THREAD

**Issue by max-l-weaver** [CachetHQ/Cachet#2409]
OS: Ubuntu 16:04
PHP Version: 7.1
Cachet Version: 2.4.0-Dev

Create an incident
User goes to update incident and gets a 500 error.
Subscribers still get a notification saying 'incident updated' yet the incident remains in the previous state.
Logs below:
```

[2017-03-06 17:08:47] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification::__construct() must be an instance of CachetHQ\Cachet\Models\IncidentUpdate, instance of CachetHQ\Cachet\Models\Incident given, called in /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php on line 77 in /var/www/Cachet/app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php:46
Stack trace:
#0 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(77): CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification->__construct(Object(CachetHQ\Cachet\Models\Incident))
#1 /var/www/Cachet/bootstrap/cache/compiled.php(12809): CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\{closure}(Object(CachetHQ\Cachet\Models\Subscriber), 24)
#2 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(78): Illuminate\Support\Collection->each(Object(Closure))
#3 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->handle(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(10322): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10256): call_user_func_array(Object(Closure), Array)
#7 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(478): Illuminate\Events\Dispatcher->fire('CachetHQ\\Cachet...')
#8 /var/www/Cachet/app/Bus/Handlers/Commands/IncidentUpdate/ReportIncidentUpdateCommandHandler.php(81): event(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#9 /var/www/Cachet/bootstrap/cache/compiled.php(9947): CachetHQ\Cachet\Bus\Handlers\Commands\IncidentUpdate\ReportIncidentUpdateCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#10 /var/www/Cachet/bootstrap/cache/compiled.php(10066): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#11 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#12 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#13 /var/www/Cachet/bootstrap/cache/compiled.php(11956): Illuminate\Database\Connection->transaction(Object(Closure))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(6468): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#15 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#16 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand), Object(Closure))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(9954): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/Cachet/bootstrap/cache/compiled.php(9940): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#20 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(373): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#21 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(315): dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\ReportIncidentUpdateCommand))
#22 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->createIncidentUpdateAction(Object(CachetHQ\Cachet\Models\Incident))
#23 /var/www/Cachet/bootstrap/cache/compiled.php(9574): call_user_func_array(Array, Array)
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9601): Illuminate\Routing\Controller->callAction('createIncidentU...', Array)
#25 /var/www/Cachet/bootstrap/cache/compiled.php(8655): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'createIncidentU...')
#26 /var/www/Cachet/bootstrap/cache/compiled.php(8636): Illuminate\Routing\Route->runController()
#27 /var/www/Cachet/bootstrap/cache/compiled.php(8345): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(10167): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(3312): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(13739): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(12145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(13485): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(13422): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/Cachet/bootstrap/cache/compiled.php(8346): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/Cachet/bootstrap/cache/compiled.php(8337): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(8328): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /var/www/Cachet/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/Cachet/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/Cachet/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main} {"identification":{"id":"af61505c-68c4-4d43-93b0-e8e953e092b2"}} 
```

**Comment by max-l-weaver** [comment]
I believe this is related to this recent enhancement:
https://github.com/CachetHQ/Cachet/blob/2.4/app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php#L77

**Comment by jbrooksuk** [comment]
Is this fixed on the most recent commits?

**Comment by max-l-weaver** [comment]
this is still happening.
Just checked out latest commit:

```
[2017-03-20 17:30:50] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification::__construct() must be an instance of CachetHQ\Cachet\Models\IncidentUpdate, instance of CachetHQ\Cachet\Models\Incident given, called in /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php on line 77 in /var/www/Cachet/app/Notifications/IncidentUpdate/IncidentUpdatedNotification.php:46
Stack trace:
#0 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(77): CachetHQ\Cachet\Notifications\IncidentUpdate\IncidentUpdatedNotification->__construct(Object(CachetHQ\Cachet\Models\Incident))
#1 /var/www/Cachet/bootstrap/cache/compiled.php(12809): CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\{closure}(Object(CachetHQ\Cachet\Models\Subscriber), 24)
#2 /var/www/Cachet/app/Bus/Handlers/Events/IncidentUpdate/SendIncidentUpdateEmailNotificationHandler.php(78): Illuminate\Support\Collection->each(Object(Closure))
#3 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\IncidentUpdate\SendIncidentUpdateEmailNotificationHandler->handle(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#4 /var/www/Cachet/bootstrap/cache/compiled.php(10322): call_user_func_array(Array, Array)
#5 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#6 /var/www/Cachet/bootstrap/cache/compiled.php(10256): call_user_func_array(Object(Closure), Array)
#7 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(480): Illuminate\Events\Dispatcher->fire('CachetHQ\\Cachet...')
#8 /var/www/Cachet/app/Bus/Handlers/Commands/IncidentUpdate/CreateIncidentUpdateCommandHandler.php(81): event(Object(CachetHQ\Cachet\Bus\Events\IncidentUpdate\IncidentUpdateWasReportedEvent))
#9 /var/www/Cachet/bootstrap/cache/compiled.php(9947): CachetHQ\Cachet\Bus\Handlers\Commands\IncidentUpdate\CreateIncidentUpdateCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#10 /var/www/Cachet/bootstrap/cache/compiled.php(10066): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#11 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#12 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(570): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#13 /var/www/Cachet/bootstrap/cache/compiled.php(11956): Illuminate\Database\Connection->transaction(Object(Closure))
#14 /var/www/Cachet/bootstrap/cache/compiled.php(6468): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#15 /var/www/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#16 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand), Object(Closure))
#17 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#18 /var/www/Cachet/bootstrap/cache/compiled.php(9954): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /var/www/Cachet/bootstrap/cache/compiled.php(9940): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#20 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(373): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#21 /var/www/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(315): dispatch(Object(CachetHQ\Cachet\Bus\Commands\IncidentUpdate\CreateIncidentUpdateCommand))
#22 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->createIncidentUpdateAction(Object(CachetHQ\Cachet\Models\Incident))
#23 /var/www/Cachet/bootstrap/cache/compiled.php(9574): call_user_func_array(Array, Array)
#24 /var/www/Cachet/bootstrap/cache/compiled.php(9601): Illuminate\Routing\Controller->callAction('createIncidentU...', Array)
#25 /var/www/Cachet/bootstrap/cache/compiled.php(8655): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'createIncidentU...')
#26 /var/www/Cachet/bootstrap/cache/compiled.php(8636): Illuminate\Routing\Route->runController()
#27 /var/www/Cachet/bootstrap/cache/compiled.php(8345): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/Cachet/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/Cachet/bootstrap/cache/compiled.php(10059): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/Cachet/bootstrap/cache/compiled.php(10167): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/Cachet/bootstrap/cache/compiled.php(3312): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/Cachet/bootstrap/cache/compiled.php(13739): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/Cachet/bootstrap/cache/compiled.php(12145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/Cachet/bootstrap/cache/compiled.php(13485): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/Cachet/bootstrap/cache/compiled.php(13422): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/Cachet/bootstrap/cache/compiled.php(8346): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /var/www/Cachet/bootstrap/cache/compiled.php(8337): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /var/www/Cachet/bootstrap/cache/compiled.php(8328): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /var/www/Cachet/bootstrap/cache/compiled.php(2575): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/Cachet/bootstrap/cache/compiled.php(3374): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/Cachet/bootstrap/cache/compiled.php(10059): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/Cachet/bootstrap/cache/compiled.php(10044): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /var/www/Cachet/bootstrap/cache/compiled.php(2519): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /var/www/Cachet/bootstrap/cache/compiled.php(2503): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#65 /var/www/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#66 {main} {"identification":{"id":"cf98b091-5ddb-435a-8a20-3d4a1a034106"}} 
```

**Comment by PietsHost** [comment]
i've got the same problem.. it was working yesterday and now i'm just getting "Internal Server Error"

**Comment by max-l-weaver** [comment]
It seems to be related to number of subscribers. Created a mirror test server with one sub and it worked fine. Copied over subs from production db (35 in total) and 500 error as above. Reduced number of subs by random increments and it appears to work with 4 subscribers.

Also, is there any ETA on a fix for this? At the moment we cannot update any fixed issues.

**Comment by max-l-weaver** [comment]
@PietsHost how many subscribers does yours have?

**Comment by PietsHost** [comment]
To be honest: just 1 😅

**Comment by max-l-weaver** [comment]
ah ok, maybe I'm clutching at straws then. Is a pretty frustrating bug though. Might have to see if downgrading to 2.3.9 is the best option

**Comment by jbrooksuk** [comment]
Okay, I'll look at this when I get a little time.

**Comment by jbrooksuk** [comment]
Oh, I had a quick look and... fixed! :)

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/commit/372c8e37b9e411a49f1ca26457fe4487e98b32f7
