### ISSUE TITLE
Class config does not exists, new install Debian 8, PHP5.6

### ISSUE THREAD

**Issue by Aldarone** [CachetHQ/Cachet#2479]
Hello !

I'm trying to install Cachet using the documentation.

I'm on tag v2.3.9, I'm using Debian Jessie on a RaspberryPi with php 5.6 from the official repository.

The command `composer install --no-dev -o` fails with this error : 

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/status.witches.town/vendor/graham-campbell/excepti in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize --force handling the post-install-cmd event returned with error code 255
```

Subsequently, when I'm launching `php artisan app:install` I get the same Exception : 

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/status.witches.town/vendor/graham-campbell/excepti in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
```

**Comment by jbrooksuk** [comment]
You need to run `rm -rf bootstrap/cache{,t}/*`.

**Comment by Aldarone** [comment]
Considering that it's a new install, those two directory are only containing .gitignore file at the time I first launched composer.

Anyway, that didn't work : 

```
$ sudo -u www-data rm -rf bootstrap/cache{,t}/* vendor/ && sudo -u www-data composer install --no-dev -o
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 69 installs, 0 updates, 0 removals
  - Installing vlucas/phpdotenv (v2.3.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.2.0): Loading from cache
  - Installing symfony/var-dumper (v3.0.9): Loading from cache
  - Installing symfony/translation (v3.0.9): Loading from cache
  - Installing symfony/routing (v3.0.9): Loading from cache
  - Installing symfony/process (v3.0.9): Loading from cache
  - Installing symfony/polyfill-util (v1.2.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.2.0): Loading from cache
  - Installing symfony/http-foundation (v3.0.9): Loading from cache
  - Installing symfony/event-dispatcher (v3.1.3): Loading from cache
  - Installing psr/log (1.0.0): Loading from cache
  - Installing symfony/debug (v3.0.9): Loading from cache
  - Installing symfony/http-kernel (v3.0.9): Loading from cache
  - Installing symfony/finder (v3.0.9): Loading from cache
  - Installing symfony/console (v3.0.9): Loading from cache
  - Installing swiftmailer/swiftmailer (v5.4.3): Loading from cache
  - Installing nikic/php-parser (v2.1.0): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing psy/psysh (v0.7.2): Loading from cache
  - Installing paragonie/random_compat (v1.4.1): Loading from cache
  - Installing nesbot/carbon (1.21.0): Loading from cache
  - Installing mtdowling/cron-expression (v1.1.0): Loading from cache
  - Installing monolog/monolog (1.21.0): Loading from cache
  - Installing league/flysystem (1.0.26): Loading from cache
  - Installing jeremeamia/superclosure (2.2.0): Loading from cache
  - Installing doctrine/inflector (v1.1.0): Loading from cache
  - Installing classpreloader/classpreloader (3.0.0): Loading from cache
  - Installing laravel/framework (v5.2.39): Loading from cache
  - Installing alt-three/badger (v3.1.0): Loading from cache
  - Installing alt-three/bus (v1.1.0): Loading from cache
  - Installing league/commonmark (0.13.4): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.3.1): Loading from cache
  - Installing guzzlehttp/promises (1.2.0): Loading from cache
  - Installing guzzlehttp/guzzle (6.2.1): Loading from cache
  - Installing alt-three/emoji (v3.1.0): Loading from cache
  - Installing alt-three/throttle (v1.0.6): Loading from cache
  - Installing alt-three/validator (v1.5.0): Loading from cache
  - Installing mtdowling/jmespath.php (2.3.0): Loading from cache
  - Installing aws/aws-sdk-php (3.18.37): Loading from cache
  - Installing backup-manager/backup-manager (1.1.1): Loading from cache
  - Installing backup-manager/laravel (1.1.1): Loading from cache
  - Installing barryvdh/laravel-cors (v0.8.1): Loading from cache
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing doctrine/annotations (v1.2.7): Loading from cache
  - Installing doctrine/cache (v1.6.0): Loading from cache
  - Installing doctrine/collections (v1.3.0): Loading from cache
  - Installing doctrine/common (v2.6.1): Loading from cache
  - Installing doctrine/dbal (v2.5.4): Loading from cache
  - Installing symfony/css-selector (v3.1.3): Loading from cache
  - Installing tijsverkoyen/css-to-inline-styles (1.5.5): Loading from cache
  - Installing fedeisas/laravel-mail-css-inliner (1.5): Loading from cache
  - Installing fideloper/proxy (3.1.0): Loading from cache
  - Installing graham-campbell/security (v3.6.0): Loading from cache
  - Installing graham-campbell/binput (v3.4.0): Loading from cache
  - Installing graham-campbell/core (v5.1.0): Loading from cache
  - Installing graham-campbell/exceptions (v8.8.0): Loading from cache
  - Installing graham-campbell/markdown (v6.1.0): Loading from cache
  - Installing jenssegers/date (v3.2.2): Loading from cache
  - Installing mccool/laravel-auto-presenter (4.3.0): Loading from cache
  - Installing bacon/bacon-qr-code (1.0.1): Loading from cache
  - Installing simplesoftwareio/simple-qrcode (1.3.3): Loading from cache
  - Installing christian-riesen/base32 (1.3.1): Loading from cache
  - Installing pragmarx/google2fa (v0.7.1): Loading from cache
  - Installing twig/twig (v1.24.1): Loading from cache
  - Installing rcrowe/twigbridge (v0.9.2): Loading from cache
  - Installing roumen/feed (v2.10.4): Loading from cache
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class config does not exist' in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('config')
#1 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('config', Array)
#2 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('config', Array)
#3 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1178): Illuminate\Foundation\Application->make('config')
#4 /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php(1223): Illuminate\Container\Container->offsetGet('config')
#5 /var/www/status.witches.town/vendor/graham-campbell/excepti in /var/www/status.witches.town/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize --force handling the post-install-cmd event returned with error code 255
```

After that, there's still nothing in those : 

```
$ tree bootstrap/cache{,t}
bootstrap/cache
bootstrap/cachet

0 directories, 0 files
```

Would you reopen the issue since it's not solved ?

**Comment by jbrooksuk** [comment]
> Would you reopen the issue since it's not solved ?

**Comment by Aldarone** [comment]
Yes they are : 

```
$ ls -l bootstrap/
total 16
-rw-r--r-- 1 www-data www-data 1385 avril 10 10:37 app.php
-rw-r--r-- 1 www-data www-data 1345 avril 10 10:36 autoload.php
drwxr-xr-x 2 www-data www-data 4096 avril 10 10:36 cache
drwxr-xr-x 2 www-data www-data 4096 avril 10 10:36 cachet
```

I'm launching every command as `www-data` or with `sudo -u www-data`

**Comment by jbrooksuk** [comment]
Does follow the instructions at https://www.rosehosting.com/blog/install-cachethq-on-debian-7-vps/ help?

**Comment by Aldarone** [comment]
Found it, it ws my bad. I had some spaces in my .env file that where not enclosed in "

Sorry for the trouble and thanks for you help !

**Comment by jbrooksuk** [comment]
Doh!
