### ISSUE TITLE
Banner picture does not work

### ISSUE THREAD

**Issue by shibumi** [CachetHQ/Cachet#2781]
Hello,
I tried different banners, but I have every time the same issue. I see the picture in the dashboard but I can't see it on the status page.

**Comment by jbrooksuk** [comment]
What version of Cachet?

**Comment by shibumi** [comment]
v2.3.12

**Comment by shibumi** [comment]
I tried to update to v2.4 now. I followed the steps described here:
https://docs.cachethq.io/v1.0/docs/updating-cachet

But `php artisan app:update` is crashing:
```
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/html/Cachet/bootstrap/cache/compiled.php(6451): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/html/Cachet/bootstrap/cache/compiled.php(12599): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#5 /var/www/html/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\NewExceptionHandle in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Foundation\Exceptions\{closure}(0, 'Illuminate\\Http...')
#1 /var/www/html/Cachet/bootstrap/cache/compiled.php(6451): call_user_func(Object(Closure), 0, 'Illuminate\\Http...')
#2 /var/www/html/Cachet/bootstrap/cache/compiled.php(12599): Illuminate\Support\Arr::first(Array, Object(Closure), NULL)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(40): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 /var/www/html/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\NewExceptionHandle in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php on line 96
```

**Comment by shibumi** [comment]
Note: I also can't delete the banner picture anymore.. when I remove it and save it it's there again. See my screencast:

![](https://paste.archlinux.de/XYe/)

**Comment by sgutermann** [comment]
Strange, am running the same Version and I can add, change and delete the banner as often as I please to.

**Comment by jimmybrancaccio** [comment]
This actually happened to me, however, I didn't have the patience to debug it. Ended up just reinstalling and now it works fine 😢

**Comment by jbrooksuk** [comment]
What size images are you guys using?
