### ISSUE TITLE
Cannot Access Dashboard. Error 500

### ISSUE THREAD

**Issue by joedguarino** [CachetHQ/Cachet#2783]
Before submitting your issue, please make sure that you've checked all of the checkboxes below.

- [ x]  You're running the latest release version of Cachet.
- [ x]  Ensure that you're running at least PHP 5.5.9, you can check this by running php -v
- [ x]  You've ran rm -rf bootstrap/cache/* from the root of your Cachet installation.

To help us better understand your issue, please answer the following — cheers!

**Your setup**

Cachet 2.3.9
MySQL
PHP 5.6.30

**Expected behaviour**

Access to dashboard.

**Actual behaviour**

Can't get to the dashboard page, get 500 error. The actual cachet status website is working. Confirmed DB is running, Confirmed PDO is enabled.

**Laravel Log**
```
[2017-10-26 16:34:10] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:569
Stack trace:
#0 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(569): PDO->exec('SAVEPOINT trans...')
#1 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(168): Illuminate\Database\Connection->beginTransaction()
#2 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(180): Illuminate\Queue\DatabaseQueue->pop()
#3 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(149): Illuminate\Queue\Worker->getNextJob(Object(Illuminate\Queue\DatabaseQueue), NULL)
#4 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, NULL, '2', '1', '3')
#5 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(87): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, NULL, '2', '1', '3')
#6 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(120): Illuminate\Queue\Worker->daemon(NULL, NULL, '2', 128, '1', '3')
#7 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(79): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, '2', 128, true)
#8 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#9 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#10 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#11 /var/www/status.firstlegal.com/html/Cachet/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/status.firstlegal.com/html/Cachet/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/status.firstlegal.com/html/Cachet/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/status.firstlegal.com/html/Cachet/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/status.firstlegal.com/html/Cachet/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 {main} {"identification":{"id":"7b113dc1-d1b8-4393-a9d5-e9dca9c2e0c7"}} 
```

**Comment by guikolt** [comment]
This has nothing to do with cachet.

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/status.firstlegal.com/html/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:569

You have a wrong mysql setting or your mysql server is gone.
