### ISSUE TITLE
View [dashboard.components.add-group] not found.

### ISSUE THREAD

**Issue by willdurand** [cachethq/Cachet#285]
Hi!

Wanted to give Cachet a try using Heroku. I can't create a component, looks like at least one component group is needed. So I tried to create one, but can't get the page:

```
2015-01-05T13:43:26.356309+00:00 app[web.1]: [2015-01-05 13:43:26] heroku.ERROR: exception 'InvalidArgumentException' with message 'View [dashboard.components.add-group] not found.' in /app/bootstrap/compiled.php:9486
2015-01-05T13:43:26.356313+00:00 app[web.1]: Stack trace:
2015-01-05T13:43:26.356315+00:00 app[web.1]: #0 /app/bootstrap/compiled.php(9459): Illuminate\View\FileViewFinder->findInPaths('dashboard.compo...', Array)
2015-01-05T13:43:26.356317+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/View/Factory.php(124): Illuminate\View\FileViewFinder->find('dashboard.compo...')
2015-01-05T13:43:26.356319+00:00 app[web.1]: #2 /app/bootstrap/compiled.php(3247): Illuminate\View\Factory->make('dashboard.compo...')
2015-01-05T13:43:26.356320+00:00 app[web.1]: #3 /app/src/Http/Controllers/DashComponentController.php(154): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
2015-01-05T13:43:26.356322+00:00 app[web.1]: #4 /app/src/Http/Controllers/DashComponentController.php(154): Illuminate\Support\Facades\View::make('dashboard.compo...')
2015-01-05T13:43:26.356323+00:00 app[web.1]: #5 [internal function]: CachetHQ\Cachet\Http\Controllers\DashComponentController->showAddComponentGroup()
2015-01-05T13:43:26.356324+00:00 app[web.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
2015-01-05T13:43:26.356326+00:00 app[web.1]: #7 /app/bootstrap/compiled.php(5822): Illuminate\Routing\Controller->callAction('showAddComponen...', Array)
2015-01-05T13:43:26.356328+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(5810): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\DashComponentController), Object(Illuminate\Routing\Route), 'showAddComponen...')
2015-01-05T13:43:26.356329+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(5015): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showAddComponen...')
2015-01-05T13:43:26.356331+00:00 app[web.1]: #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2015-01-05T13:43:26.356332+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(5373): call_user_func_array(Object(Closure), Array)
2015-01-05T13:43:26.356333+00:00 app[web.1]: #12 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356335+00:00 app[web.1]: #13 /app/bootstrap/compiled.php(5028): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356336+00:00 app[web.1]: #14 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356338+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356339+00:00 app[web.1]: #16 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356341+00:00 app[web.1]: #17 /app/bootstrap/compiled.php(7800): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T13:43:26.356342+00:00 app[web.1]: #18 /app/bootstrap/compiled.php(8407): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T13:43:26.356343+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(8354): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T13:43:26.356344+00:00 app[web.1]: #20 /app/bootstrap/compiled.php(11017): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T13:43:26.356345+00:00 app[web.1]: #21 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-05T13:43:26.356347+00:00 app[web.1]: #22 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-05T13:43:26.356349+00:00 app[web.1]: #23 {main} [] []
```

It can't find the view. Any hints?

Here is the issue related to the component creation fail:

```
2015-01-05T13:42:42.928509+00:00 app[web.1]: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("name", "status", "description", "group_id", "link", "tags", "user_id", "updated_at", "created_at") values (example.org, 1, The main website., , http://example.org, none, 1, 2015-01-05 13:42:42, 2015-01-05 13:42:42) returning "id")' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625

```

Regards,
William

**Comment by jbrooksuk** [comment]
Can you update and try again please :)

**Comment by willdurand** [comment]
@jbrooksuk I can create a component group now, but if I don't specify one in the component creation, it fails and I get a 500 error...

**Comment by GrahamCampbell** [comment]
Looks we're not catching the validation exception correctly.

**Comment by jbrooksuk** [comment]
@willdurand I'm able to create a component without adding it to a group.

**Comment by willdurand** [comment]
@jbrooksuk glad for you. Here is a new log output:

```
2015-01-05T14:05:04.774106+00:00 app[web.1]: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("name", "status", "description", "group_id", "link", "tags", "user_id", "updated_at", "created_at") values (Website, 1, foo, , http://example.org, , 1, 2015-01-05 14:05:04, 2015-01-05 14:05:04) returning "id")' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
2015-01-05T14:05:04.774174+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(11017): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774012+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T14:05:04.774034+00:00 app[web.1]: #22 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774151+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(5373): call_user_func_array(Object(Closure), Array)
2015-01-05T14:05:04.774120+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "co...', Array, 'id')
2015-01-05T14:05:04.774122+00:00 app[web.1]: #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
2015-01-05T14:05:04.774131+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T14:05:04.774142+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(5822): Illuminate\Routing\Controller->callAction('createComponent...', Array)
2015-01-05T14:05:04.774153+00:00 app[web.1]: #20 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774176+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.782753+00:00 app[web.1]: 193.49.118.103 - "POST /dashboard/components/add HTTP/1.1" 500 4409 "http://spotlist-status.herokuapp.com/dashboard/components/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
2015-01-05T14:05:04.774129+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
2015-01-05T14:05:04.774137+00:00 app[web.1]: #12 /app/src/Http/Controllers/DashComponentController.php(128): Illuminate\Database\Eloquent\Model::create(Array)
2015-01-05T14:05:04.774149+00:00 app[web.1]: #18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2015-01-05T14:05:04.774158+00:00 app[web.1]: #23 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774166+00:00 app[web.1]: #24 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774170+00:00 app[web.1]: #26 /app/bootstrap/compiled.php(8407): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774172+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(8354): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774140+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
2015-01-05T14:05:04.774139+00:00 app[web.1]: #13 [internal function]: CachetHQ\Cachet\Http\Controllers\DashComponentController->createComponentAction()
```

I filled in:

![screen shot 2015-01-05 at 15 06 11](https://cloud.githubusercontent.com/assets/217628/5614009/6aaa7f86-94ec-11e4-81be-9314083c23f2.png)

**Comment by jbrooksuk** [comment]
@GrahamCampbell it looks like PgSQL isn't filling in `null`?

**Comment by GrahamCampbell** [comment]
@jbrooksuk Are you using mysql? It's less string than postgresql on these things.

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell it looks like PgSQL isn't filling in null?

Yeh, it's not meant to. mysql is basically doing it wrong.

**Comment by jbrooksuk** [comment]
Ok, so I'll just add a condition to check for it existing? If it doesn't, manually set it to `null`?

**Comment by willdurand** [comment]
Don't you use an ORM?

**Comment by jbrooksuk** [comment]
Yeah, Eloquent.

**Comment by willdurand** [comment]
It should be its responsibility.

**Comment by jbrooksuk** [comment]
Which is why I'm confused. I thought Eloquent would be handling that, especially with the `doctrine/dbal` requirement.

**Comment by willdurand** [comment]
Should we reopen this issue or continue in a new one? but this is a pretty serious issue :p (at least, because it returns a 500)

**Comment by jbrooksuk** [comment]
Open a new one regarding this specific issue please. I'll take a look.

**Comment by willdurand** [comment]
conversation moved to: #287
