### ISSUE TITLE
[PostgreSQL] Can't add a component without group (500 error)

### ISSUE THREAD

**Issue by willdurand** [cachethq/Cachet#287]
See: #285 

```
2015-01-05T14:05:04.774106+00:00 app[web.1]: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("name", "status", "description", "group_id", "link", "tags", "user_id", "updated_at", "created_at") values (Website, 1, foo, , http://example.org, , 1, 2015-01-05 14:05:04, 2015-01-05 14:05:04) returning "id")' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
2015-01-05T14:05:04.774174+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(11017): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774012+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T14:05:04.774034+00:00 app[web.1]: #22 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774151+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(5373): call_user_func_array(Object(Closure), Array)
2015-01-05T14:05:04.774120+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "co...', Array, 'id')
2015-01-05T14:05:04.774122+00:00 app[web.1]: #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
2015-01-05T14:05:04.774131+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T14:05:04.774142+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(5822): Illuminate\Routing\Controller->callAction('createComponent...', Array)
2015-01-05T14:05:04.774153+00:00 app[web.1]: #20 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774176+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.782753+00:00 app[web.1]: 193.49.118.103 - "POST /dashboard/components/add HTTP/1.1" 500 4409 "http://spotlist-status.herokuapp.com/dashboard/components/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
2015-01-05T14:05:04.774129+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
2015-01-05T14:05:04.774137+00:00 app[web.1]: #12 /app/src/Http/Controllers/DashComponentController.php(128): Illuminate\Database\Eloquent\Model::create(Array)
2015-01-05T14:05:04.774149+00:00 app[web.1]: #18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2015-01-05T14:05:04.774158+00:00 app[web.1]: #23 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774166+00:00 app[web.1]: #24 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-05T14:05:04.774170+00:00 app[web.1]: #26 /app/bootstrap/compiled.php(8407): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774172+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(8354): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T14:05:04.774140+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
2015-01-05T14:05:04.774139+00:00 app[web.1]: #13 [internal function]: CachetHQ\Cachet\Http\Controllers\DashComponentController->createComponentAction()
```

I filled in:

![screen shot 2015-01-05 at 15 06 11](https://cloud.githubusercontent.com/assets/217628/5614009/6aaa7f86-94ec-11e4-81be-9314083c23f2.png)

**Comment by jbrooksuk** [comment]
Try now, I've just added a condition, if it's not set in the input, set it to `null`.

**Comment by willdurand** [comment]
Please reopen and don't close the issue until it is really fixed.

**Comment by willdurand** [comment]
So, the field seems not `nullable` and expects an integer. Setting `null` in PHP does not solve the issue because of that, here is the log output:

```
2015-01-05T14:39:58.306091+00:00 app[web.1]: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("name", "status", "description", "group_id", "link", "tags", "user_id", "updated_at", "created_at") values (Spotlist.io, 1, The main website., , https://spotlist.io, , 1, 2015-01-05 14:39:58, 2015-01-05 14:39:58) returning "id")' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
```

**Comment by GrahamCampbell** [comment]
Ping @cachethq/owners

**Comment by jbrooksuk** [comment]
Does pgsql not have any understanding of a nullable integer field?

**Comment by GrahamCampbell** [comment]
it does, but ours isn't nullable?

**Comment by GrahamCampbell** [comment]
also, i suspect eloquent translates `null` to empty string.

**Comment by jbrooksuk** [comment]
Will make it `0` then.

**Comment by GrahamCampbell** [comment]
This is hacky. There's probably a better way.

**Comment by jbrooksuk** [comment]
It is, but for now, if it's returning 500 errors I'd rather get it fixed whilst I'm at work.

@willdurand can you try again please.

**Comment by jbrooksuk** [comment]
Also:

```php
$table->integer('group_id')->nullable()->default(null)->after('order');
```

**Comment by willdurand** [comment]
Does not work. Here is an interesting log entry:

```
2015-01-05T15:37:33.094808+00:00 app[web.1]: [2015-01-05 15:37:33] heroku.ERROR: exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:301
```

I don't see why it talks about a "text representation". Is everything configured as it should be?

**Comment by willdurand** [comment]
Full log output:

```
2015-01-05T15:37:33.094808+00:00 app[web.1]: [2015-01-05 15:37:33] heroku.ERROR: exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:301
2015-01-05T15:37:33.094815+00:00 app[web.1]: Stack trace:
2015-01-05T15:37:33.094818+00:00 app[web.1]: #0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(301): PDOStatement->execute(Array)
2015-01-05T15:37:33.094820+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'insert into "co...', Array)
2015-01-05T15:37:33.094821+00:00 app[web.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into "co...', Array, Object(Closure))
2015-01-05T15:37:33.094823+00:00 app[web.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('insert into "co...', Array, Object(Closure))
2015-01-05T15:37:33.094824+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(279): Illuminate\Database\Connection->select('insert into "co...', Array, false)
2015-01-05T15:37:33.094826+00:00 app[web.1]: #5 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(18): Illuminate\Database\Connection->selectFromWriteConnection('insert into "co...', Array)
2015-01-05T15:37:33.094828+00:00 app[web.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "co...', Array, 'id')
2015-01-05T15:37:33.094829+00:00 app[web.1]: #7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
2015-01-05T15:37:33.094831+00:00 app[web.1]: #8 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
2015-01-05T15:37:33.094832+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
2015-01-05T15:37:33.094834+00:00 app[web.1]: #10 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
2015-01-05T15:37:33.094836+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T15:37:33.094837+00:00 app[web.1]: #12 /app/bootstrap/compiled.php(6835): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T15:37:33.094839+00:00 app[web.1]: #13 /app/bootstrap/compiled.php(6481): Illuminate\Database\Eloquent\Model->save()
2015-01-05T15:37:33.094840+00:00 app[web.1]: #14 /app/src/Http/Controllers/DashComponentController.php(128): Illuminate\Database\Eloquent\Model::create(Array)
2015-01-05T15:37:33.094841+00:00 app[web.1]: #15 [internal function]: CachetHQ\Cachet\Http\Controllers\DashComponentController->createComponentAction()
2015-01-05T15:37:33.094843+00:00 app[web.1]: #16 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
2015-01-05T15:37:33.094844+00:00 app[web.1]: #17 /app/bootstrap/compiled.php(5822): Illuminate\Routing\Controller->callAction('createComponent...', Array)
2015-01-05T15:37:33.094846+00:00 app[web.1]: #18 /app/bootstrap/compiled.php(5810): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\DashComponentController), Object(Illuminate\Routing\Route), 'createComponent...')
2015-01-05T15:37:33.094847+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(5015): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'createComponent...')
2015-01-05T15:37:33.094849+00:00 app[web.1]: #20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2015-01-05T15:37:33.094851+00:00 app[web.1]: #21 /app/bootstrap/compiled.php(5373): call_user_func_array(Object(Closure), Array)
2015-01-05T15:37:33.094852+00:00 app[web.1]: #22 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094853+00:00 app[web.1]: #23 /app/bootstrap/compiled.php(5028): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094868+00:00 app[web.1]: #24 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094870+00:00 app[web.1]: #25 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094871+00:00 app[web.1]: #26 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094874+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(7800): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094875+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(8407): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094884+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(8354): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094898+00:00 app[web.1]: #30 /app/bootstrap/compiled.php(11017): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094900+00:00 app[web.1]: #31 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094901+00:00 app[web.1]: #32 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-05T15:37:33.094902+00:00 app[web.1]: #33 {main}
2015-01-05T15:37:33.094904+00:00 app[web.1]:
2015-01-05T15:37:33.094905+00:00 app[web.1]: Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("name", "status", "description", "group_id", "link", "tags", "user_id", "updated_at", "created_at") values (Spotlist.io, 1, The main website, yep., , https://spotlist.io, , 1, 2015-01-05 15:37:33, 2015-01-05 15:37:33) returning "id")' in /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
2015-01-05T15:37:33.094907+00:00 app[web.1]: Stack trace:
2015-01-05T15:37:33.094908+00:00 app[web.1]: #0 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into "co...', Array, Object(Closure))
2015-01-05T15:37:33.094910+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('insert into "co...', Array, Object(Closure))
2015-01-05T15:37:33.094912+00:00 app[web.1]: #2 /app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(279): Illuminate\Database\Connection->select('insert into "co...', Array, false)
2015-01-05T15:37:33.094914+00:00 app[web.1]: #3 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(18): Illuminate\Database\Connection->selectFromWriteConnection('insert into "co...', Array)
2015-01-05T15:37:33.094915+00:00 app[web.1]: #4 /app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1896): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "co...', Array, 'id')
2015-01-05T15:37:33.094916+00:00 app[web.1]: #5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
2015-01-05T15:37:33.094918+00:00 app[web.1]: #6 /app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(935): call_user_func_array(Array, Array)
2015-01-05T15:37:33.094919+00:00 app[web.1]: #7 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
2015-01-05T15:37:33.094920+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(6888): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
2015-01-05T15:37:33.094921+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(6878): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T15:37:33.094923+00:00 app[web.1]: #10 /app/bootstrap/compiled.php(6835): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
2015-01-05T15:37:33.094924+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(6481): Illuminate\Database\Eloquent\Model->save()
2015-01-05T15:37:33.094925+00:00 app[web.1]: #12 /app/src/Http/Controllers/DashComponentController.php(128): Illuminate\Database\Eloquent\Model::create(Array)
2015-01-05T15:37:33.094934+00:00 app[web.1]: #13 [internal function]: CachetHQ\Cachet\Http\Controllers\DashComponentController->createComponentAction()
2015-01-05T15:37:33.094936+00:00 app[web.1]: #14 /app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
2015-01-05T15:37:33.094937+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(5822): Illuminate\Routing\Controller->callAction('createComponent...', Array)
2015-01-05T15:37:33.094938+00:00 app[web.1]: #16 /app/bootstrap/compiled.php(5810): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\DashComponentController), Object(Illuminate\Routing\Route), 'createComponent...')
2015-01-05T15:37:33.094939+00:00 app[web.1]: #17 /app/bootstrap/compiled.php(5015): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'createComponent...')
2015-01-05T15:37:33.094941+00:00 app[web.1]: #18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
2015-01-05T15:37:33.094943+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(5373): call_user_func_array(Object(Closure), Array)
2015-01-05T15:37:33.094944+00:00 app[web.1]: #20 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094946+00:00 app[web.1]: #21 /app/bootstrap/compiled.php(5028): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094947+00:00 app[web.1]: #22 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094948+00:00 app[web.1]: #23 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094953+00:00 app[web.1]: #24 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094954+00:00 app[web.1]: #25 /app/bootstrap/compiled.php(7800): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094955+00:00 app[web.1]: #26 /app/bootstrap/compiled.php(8407): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094957+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(8354): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094958+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(11017): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-05T15:37:33.094959+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-05T15:37:33.094960+00:00 app[web.1]: #30 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-05T15:37:33.094962+00:00 app[web.1]: #31 {main} [] []
2015-01-05T15:37:33.101683+00:00 app[web.1]: 193.49.118.103 - "POST /dashboard/components/add HTTP/1.1" 500 4403 "http://spotlist-status.herokuapp.com/dashboard/components/add" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"
```

**Comment by jbrooksuk** [comment]
That's a new one.

**Comment by GrahamCampbell** [comment]
yeh, it doesn't seem to be passing null, rather empty string

**Comment by jbrooksuk** [comment]
@GrahamCampbell I changed it to be `0`.

**Comment by GrahamCampbell** [comment]
Both are not correct.

**Comment by GrahamCampbell** [comment]
It needs to be `NULL`. That's a special sql thing.

**Comment by GrahamCampbell** [comment]
http://en.wikipedia.org/wiki/Null_%28SQL%29

**Comment by GrahamCampbell** [comment]
Not the same as 0.

**Comment by jbrooksuk** [comment]
Why both as `NULL`, the field is an integer.

**Comment by GrahamCampbell** [comment]
The field is nullable thus it must support this.

**Comment by jbrooksuk** [comment]
Ok. So we need to figure out what is going on then. I thought that Eloquent/dbal was supposed to support this?

**Comment by GrahamCampbell** [comment]
Yeh it is. Is it possible @willdurand migrated with an old version of the migration?

**Comment by jbrooksuk** [comment]
It's possible - @willdurand can you undo the recent migrations and try again please.

In the mean time, I'll re-push our demo and see if it works there.

**Comment by willdurand** [comment]
Let me trash the web app, and start again.

**Comment by jbrooksuk** [comment]
@willdurand the app itself should be ok, just the migrations may have gone wonky.

**Comment by willdurand** [comment]
You know.. migrations on heroku take more time than recreating an app..

**Comment by jbrooksuk** [comment]
As you've seen, we're running a custom buildpack. It may be something to do with that.

**Comment by willdurand** [comment]
Still the same issue after a fresh install. Should I run migrations again?

**Comment by jbrooksuk** [comment]
Closed by 751ba687d71fe03aa571a931ee09ff8e587cce21.

**Comment by willdurand** [comment]
So, how am I supposed to upgrade?

**Comment by GrahamCampbell** [comment]
delete all your tables in the db, then run the new migrations

**Comment by willdurand** [comment]
Great. It works now, but I can't update dashboard settings anymore... The form gets redirected from `/dashboard/settings` to `/dashboard/settings/setup`, and thus the POST request is gone, meaning it does not submit the form.
