### ISSUE TITLE
[Version 2.4] Creation incident with notify subcriber get 500 internal server

### ISSUE THREAD

**Issue by sontt710** [CachetHQ/Cachet#2968]
![image](https://user-images.githubusercontent.com/31494976/37946347-1b5ea7a0-31af-11e8-989a-3f5c99d66907.png)

**Comment by shurikanet** [comment]
I have the same issue.
Version of PHP: 7.2.0 

`[2018-03-27 06:27:59] production.ERROR: InvalidArgumentException: View [test] not found. in /var/www/...../Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
Stack trace:
#0 /var/www/...../Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('test', Array)
#1 /var/www/...../Cachet/vendor/laravel/framework/src/Illuminate/View/Factory.php(128): Illuminate\View\FileViewFinder->find('test')
#2 /var/www/...../Cachet/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(62): Illuminate\View\Factory->make('test', Array)
#3 /var/www/...../Cachet/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(78): Illuminate\Mail\Markdown->render('test', Array)...`

some parameters from config (connection with mailgun works perfectly):
```
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database
CACHET_EMOJI=false

MAIL_DRIVER=mailgun
MAILGUN_DOMAIN=mail.domain.com
MAILGUN_SECRET=key-c147fbe6........86f7436397d922
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=587
MAIL_USERNAME=mail.domain.com
MAIL_PASSWORD=key-c147fbe6..........86f7436397d922
MAIL_ADDRESS=postmaster@mail.domain.com
MAIL_NAME="Domain.com Services"
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
```

**Comment by jbrooksuk** [comment]
View `test` would be the test notification email. Are you sending a test?

**Comment by sontt710** [comment]
test: it's message content from creation incident. 
Example: I created a incident with message "Message", the error will show View [message] not found.

**Comment by sontt710** [comment]
![image](https://user-images.githubusercontent.com/31494976/37954000-a0c97ebe-31ce-11e8-845e-52484f1cd15c.png)

He had the same issue.

**Comment by uxen-ab** [comment]
I am able to reproduce the issue.

Content of the .env
```
APP_ENV=development
APP_DEBUG=true
APP_URL=http://cachet2.local
APP_KEY=base64:mykey

DB_DRIVER=mysql
DB_HOST=localhost
DB_UNIX_SOCKET=/myPath/mysql.sock
DB_DATABASE=cachet
DB_USERNAME=username
DB_PASSWORD=password
DB_PORT=3306
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=database
QUEUE_DRIVER=null

CACHET_BEACON=true
CACHET_EMOJI=false
CACHET_AUTO_TWITTER=true

MAIL_DRIVER=log
MAIL_HOST=
MAIL_PORT=null
MAIL_USERNAME=myUsername
MAIL_PASSWORD=mypassword
MAIL_ADDRESS=email@host.com
MAIL_NAME=null
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

NEXMO_KEY=null
NEXMO_SECRET=null
NEXMO_SMS_FROM=Cachet
```

Cachet 2.4 (0ebaa395c0a36e84f392559b2a8b68d56bb19b19).
PHP 5.6.32
MAMP 4.4
Apache 2.

When creating an incident, if the checkbox `notify subscribers` is **not** checked, the incident is created with no problem.
But if I create the incident and I check the checkbox, I have the error.

Here is the log:

```
[2018-03-27 07:55:21] production.ERROR: exception 'InvalidArgumentException' with message 'View [dddd] not found.' in /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137
Stack trace:
#0 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('dddd', Array)
#1 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/View/Factory.php(129): Illuminate\View\FileViewFinder->find('dddd')
#2 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(62): Illuminate\View\Factory->make('dddd', Array)
#3 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(78): Illuminate\Mail\Markdown->render('dddd', Array)
#4 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(58): Illuminate\Notifications\Channels\MailChannel->buildView(Object(Illuminate\Notifications\Messages\MailMessage))
#5 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(CachetHQ\Cachet\Models\Subscriber), Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification))
#6 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(CachetHQ\Cachet\Models\Subscriber), '28b7d97b-9fe2-4...', Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification), 'mail')
#7 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification))
#8 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(CachetHQ\Cachet\Models\Subscriber), Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification))
#9 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(CachetHQ\Cachet\Models\Subscriber), Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification))
#10 /Applications/MAMP/htdocs/Cachet/app/Bus/Handlers/Events/Incident/SendIncidentEmailNotificationHandler.php(73): CachetHQ\Cachet\Models\Subscriber->notify(Object(CachetHQ\Cachet\Notifications\Incident\NewIncidentNotification))
#11 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): CachetHQ\Cachet\Bus\Handlers\Events\Incident\SendIncidentEmailNotificationHandler->CachetHQ\Cachet\Bus\Handlers\Events\Incident\{closure}(Object(CachetHQ\Cachet\Models\Subscriber), 0)
#12 /Applications/MAMP/htdocs/Cachet/app/Bus/Handlers/Events/Incident/SendIncidentEmailNotificationHandler.php(74): Illuminate\Support\Collection->each(Object(Closure))
#13 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\Incident\SendIncidentEmailNotificationHandler->handle(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasCreatedEvent))
#14 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(368): call_user_func_array(Array, Array)
#15 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('CachetHQ\\Cachet...', Array)
#16 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(446): Illuminate\Events\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasCreatedEvent))
#17 /Applications/MAMP/htdocs/Cachet/app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php(132): event(Object(CachetHQ\Cachet\Bus\Events\Incident\IncidentWasCreatedEvent))
#18 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(90): CachetHQ\Cachet\Bus\Handlers\Commands\Incident\CreateIncidentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#19 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#20 /Applications/MAMP/htdocs/Cachet/vendor/alt-three/validator/src/ValidatingMiddleware.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#21 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): AltThree\Validator\ValidatingMiddleware->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand), Object(Closure))
#22 /Applications/MAMP/htdocs/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#23 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection))
#24 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(327): Illuminate\Database\Connection->transaction(Object(Closure))
#25 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#26 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\DatabaseManager->transaction(Object(Closure))
#27 /Applications/MAMP/htdocs/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#28 /Applications/MAMP/htdocs/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(36): Illuminate\Support\Facades\DB::transaction(Object(Closure))
#29 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand), Object(Closure))
#30 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#31 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#33 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(378): Illuminate\Bus\Dispatcher->dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#34 /Applications/MAMP/htdocs/Cachet/app/Http/Controllers/Dashboard/IncidentController.php(135): dispatch(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#35 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController->createIncidentAction()
#36 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#37 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('createIncidentA...', Array)
#38 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(CachetHQ\Cachet\Http\Controllers\Dashboard\IncidentController), 'createIncidentA...')
#39 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#40 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#41 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /Applications/MAMP/htdocs/Cachet/app/Http/Middleware/Authenticate.php(61): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#66 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#67 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#68 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#69 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /Applications/MAMP/htdocs/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#77 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#78 /Applications/MAMP/htdocs/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#79 {main} {"identification":{"id":"ae44af99-f139-46e3-9026-0ceb0b63744d"}}
```

(If it had worked, where would I find the mail, using the 'log' driver?)

**Comment by jbrooksuk** [comment]
> [2018-03-27 07:55:21] production.ERROR: exception 'InvalidArgumentException' with message 'View [dddd] not found.' in /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137

That's really weird. I'll take a look.
