### ISSUE TITLE
Breaking change in 2.4: `user_id` column not found when creating an incident

### ISSUE THREAD

**Issue by uxen-ab** [CachetHQ/Cachet#2979]
It seems a field `user_id` has been added into the `Incident` model. It's cool, it allows us to know who added a given incident.

It it's a breaking change because our databases don't have the `incidents.user_id` field. Perhaps it should have been added in 3.0?

I've ran a `git pull upstream 2.4` and then I was no longer able to create an incident.

Here is a sample of my log file:

```
[2018-03-29 08:51:40] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user_id' in 'field list'' in /Applications/MAMP/htdocs/Cachet/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:
#0 /Applications/MAMP/htdocs/Cachet/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('insert into `in...', Array)
#1 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(445): Doctrine\DBAL\Driver\PDOConnection->prepare('insert into `in...')
#2 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `in...', Array)
#3 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `in...', Array, Object(Closure))
#4 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(450): Illuminate\Database\Connection->run('insert into `in...', Array, Object(Closure))
#5 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(404): Illuminate\Database\Connection->statement('insert into `in...', Array)
#6 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `in...', Array)
#7 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `in...', Array, 'id')
#8 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(688): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#13 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(734): Illuminate\Database\Eloquent\Model->save()
#14 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Support/helpers.php(964): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(CachetHQ\Cachet\Models\Incident))
#15 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(735): tap(Object(CachetHQ\Cachet\Models\Incident), Object(Closure))
#16 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1374): Illuminate\Database\Eloquent\Builder->create(Array)
#17 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1386): Illuminate\Database\Eloquent\Model->__call('create', Array)
#18 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1386): CachetHQ\Cachet\Models\Incident->create(Array)
#19 /Applications/MAMP/htdocs/Cachet/app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php(103): Illuminate\Database\Eloquent\Model::__callStatic('create', Array)
#20 /Applications/MAMP/htdocs/Cachet/app/Bus/Handlers/Commands/Incident/CreateIncidentCommandHandler.php(103): CachetHQ\Cachet\Models\Incident::create(Array)
#21 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(90): CachetHQ\Cachet\Bus\Handlers\Commands\Incident\CreateIncidentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#22 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#23 /Applications/MAMP/htdocs/Cachet/vendor/alt-three/validator/src/ValidatingMiddleware.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
#24 /Applications/MAMP/htdocs/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): AltThree\Validator\ValidatingMiddleware->handle(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand), Object(Closure))
#25 /Applications/MAMP/htdocs/Cachet/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Incident\CreateIncidentCommand))
```

I've done a quickfix, running these queries on my Cachet database.

```SQL
ALTER TABLE `incidents` ADD COLUMN `user_id` int(10) unsigned;
ALTER TABLE `incidents` ADD FOREIGN KEY (`user_id`) REFERENCES users(`id`);
```

Cachet 2.4 3209df42d68d42f9439663102fb41d098ee55c72

**Comment by sontt710** [comment]
I confirm this quick fix resolved the problem. New feature in dashboard.

![image](https://user-images.githubusercontent.com/31494976/38081284-da4fc3fa-336d-11e8-9031-3ad66e3c3df6.png)

**Comment by jbrooksuk** [comment]
> It it's a breaking change because our databases don't have the incidents.user_id field. Perhaps it should have been added in 3.0?

2.4 will likely become 3.0 but it's still in dev, so really we're free to do as we wish currently ;)

You need to run `php artisan app:update` when updatig Cachet, that'll create the new column for you.

**Comment by uxen-ab** [comment]
I had not seen that, indeed it's written in the [documentation][1].

[1]: https://docs.cachethq.io/docs/updating-cachet#section-update-the-app
