### ISSUE TITLE
Error Running Composer Install Command

### ISSUE THREAD

**Issue by TheoBearman** [CachetHQ/Cachet#3078]
When running _composer install -o_ after pulling the latest commits:

`[2018-06-15 09:47:45] local.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'CachetHQ\Cachet\Foundation\Providers\ModuleServiceProvider' not found in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:208
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('CachetHQ\\Cachet...')
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /var/www/html/Cachet/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main} {"identification":{"id":"a3b4f0cc-661c-46a9-9b07-dc242c16f548"}} 
`

**Comment by jbrooksuk** [comment]
Try running `rm -rf bootstrap/cache{,t}/*` as `ModuleServiceProvider` is no longer in `./config/app.php`.
