### ISSUE TITLE
Error 500 after upgrade

### ISSUE THREAD

**Issue by Metreas** [CachetHQ/Cachet#3160]
Hello,

after an upgrade from 2.3.8 to 2.3.9 and set of smtp port in .env I recieved an Error 500.

.env-file
```
APP_ENV=production
APP_DEBUG=false
APP_URL=https://cachet.studydev.de
APP_KEY=base64:****=

DB_DRIVER=mysql
DB_HOST=****
DB_DATABASE=****
DB_USERNAME=****
DB_PASSWORD=****
DB_PORT=3306
DB_PREFIX=null

CACHE_DRIVER=apc
SESSION_DRIVER=apc
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=mail.studydev.de
MAIL_PORT=25
MAIL_USERNAME=****
MAIL_PASSWORD=****
MAIL_ADDRESS=****
MAIL_NAME=****
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null
```

This error was shown after start "php artisan app:update":
```
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/sites/...', 51, Array)
#1 /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /var/www/sites/cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/sites/...', 51, Array)
#1 /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /var/www/sites/cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /var/www/sites/cachet/bootstrap/cache/compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorExcepti in /var/www/sites/cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
```

Unfortunately, this problem is completely unknown to me.
Could you help, please?

**Comment by Metreas** [comment]
I also could provide the laravel-log.
[laravel-2018-07-04.log](https://github.com/CachetHQ/Cachet/files/2162996/laravel-2018-07-04.log)

**Comment by Atriusftw** [comment]
Have you tried clearing the cache?

Run the following commands;
`rm -rf bootstrap/cache/*`
`php artisan cache:clear`

**Comment by Metreas** [comment]
yes, i've tried both commands

**Comment by Atriusftw** [comment]
Hm. From the log file it appears to be some issue related to APCu.

Did you follow the [upgrade docs](https://docs.cachethq.io/docs/updating-cachet)?
You could also try a different queue driver, like file. (Change it in `.env` and run `php artisan config:clear`)

**Comment by jbrooksuk** [comment]
Cachet 2.3 doesn't support PHP 7. You need to use PHP 5.6.
