### ISSUE TITLE
Docker error 500

### ISSUE THREAD

**Issue by DrPreobrazhensky** [CachetHQ/Cachet#3227]
I've tried to install Cachet with docker as [described](https://docs.cachethq.io/docs/get-started-with-docker) and get error 500

>Docker version 18.06.1-ce, build e68fc7a

Also I've tried with
>args:
>        - cachet_ver=v2.3.15

Problem the same

```2018-08-27 11:57:49,295 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cachet_1    | 2018-08-27 11:57:49,296 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cachet_1    | 2018-08-27 11:57:49,296 INFO success: queue-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "NOTICE: PHP message: [2018-08-27 11:58:00] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "Stack trace:"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#4 /var/www/html/vendor/laravel/frame..."
cachet_1    | 2018/08/27 11:58:00 [error] 69#69: *1 FastCGI sent in stderr: "PHP message: [2018-08-27 11:58:00] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45
cachet_1    | Stack trace:
cachet_1    | #0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')
cachet_1    | #1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
cachet_1    | #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)
cachet_1    | #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)
cachet_1    | #4 /var/www/html/vendor/laravel/framework/src" while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "NOTICE: PHP message: [2018-08-27 11:58:00] development.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:45"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "Stack trace:"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(25): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher(NULL, 'AES-256-CBC')"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build(Object(Closure), Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('encrypter', Array)"
cachet_1    | [27-Aug-2018 11:58:00] WARNING: [pool www] child 86 said into stderr: "#4 /var/www/html/vendor/laravel/frame..."
cachet_1    | 172.19.0.1 - - [27/Aug/2018:11:58:00 +0000] "GET / HTTP/1.1" 500 3165 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
```

**Comment by cdhowie** [comment]
I think you missed the step of running `php artisan key:generate`.

**Comment by cdhowie** [comment]
It's part of the steps in the [main install guide](https://docs.cachethq.io/docs/installing-cachet).  The documentation can be kind of lacking; I think some of those steps need to be copied to the Docker installation guide.

**Comment by jbrooksuk** [comment]
Docker errors need to be opened at https://github.com/CachetHQ/Docker, thanks.
