### ISSUE TITLE
Install Error running `gulp`

### ISSUE THREAD

**Issue by ajtrichards** [cachethq/Cachet#323]
During the install process after running the `gulp` command i'm getting an error:

```
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/status.evaluagent.net/node_modules/laravel-elixir-jshint/node_modules/gulp-jshint/node_modules/jshint/src/cli.js:3:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

When I ran the `bower install` command I did get a warning/error during that phase

```
bower bootstrap-sass-official#~3.3.1       not-cached git://github.com/twbs/bootstrap-sass.git#~3.3.1
bower bootstrap-sass-official#~3.3.1          resolve git://github.com/twbs/bootstrap-sass.git#~3.3.1
bower jquery-minicolors#~2.1.10            not-cached git://github.com/claviska/jquery-minicolors.git#~2.1.10
bower jquery-minicolors#~2.1.10               resolve git://github.com/claviska/jquery-minicolors.git#~2.1.10
bower humane-js#~3.2.2                     not-cached git://github.com/wavded/humane-js.git#~3.2.2
bower humane-js#~3.2.2                        resolve git://github.com/wavded/humane-js.git#~3.2.2
bower ionicons#~2.0.0                      not-cached git://github.com/driftyco/ionicons.git#~2.0.0
bower ionicons#~2.0.0                         resolve git://github.com/driftyco/ionicons.git#~2.0.0
bower jquery#~2.1.1                        not-cached git://github.com/jquery/jquery.git#~2.1.1
bower jquery#~2.1.1                           resolve git://github.com/jquery/jquery.git#~2.1.1
bower lodash#~2.4.1                        not-cached git://github.com/lodash/lodash.git#~2.4.1
bower lodash#~2.4.1                           resolve git://github.com/lodash/lodash.git#~2.4.1
bower messenger#~1.4.1                     not-cached git://github.com/HubSpot/messenger.git#~1.4.1
bower messenger#~1.4.1                        resolve git://github.com/HubSpot/messenger.git#~1.4.1
bower jquery-serialize-object#~2.4.3       not-cached git://github.com/macek/jquery-serialize-object.git#~2.4.3
bower jquery-serialize-object#~2.4.3          resolve git://github.com/macek/jquery-serialize-object.git#~2.4.3
bower Sortable#~1.0.0                      not-cached git://github.com/RubaXa/Sortable.git#~1.0.0
bower Sortable#~1.0.0                         resolve git://github.com/RubaXa/Sortable.git#~1.0.0
bower animate-sass#~0.6.2                  not-cached git://github.com/tgdev/animate-sass.git#~0.6.2
bower animate-sass#~0.6.2                     resolve git://github.com/tgdev/animate-sass.git#~0.6.2
bower ionicons#~2.0.0                        download https://github.com/driftyco/ionicons/archive/v2.0.0.tar.gz
bower jquery-minicolors#~2.1.10              download https://github.com/claviska/jquery-minicolors/archive/2.1.10.tar.gz
bower humane-js#~3.2.2                       download https://github.com/wavded/humane-js/archive/3.2.2.tar.gz
bower bootstrap-sass-official#~3.3.1         download https://github.com/twbs/bootstrap-sass/archive/v3.3.1.tar.gz
bower messenger#~1.4.1                       download https://github.com/HubSpot/messenger/archive/v1.4.1.tar.gz
bower jquery-serialize-object#~2.4.3         download https://github.com/macek/jquery-serialize-object/archive/2.4.3.tar.gz
bower lodash#~2.4.1                          download https://github.com/lodash/lodash/archive/2.4.1.tar.gz
bower jquery#~2.1.1                          download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower animate-sass#~0.6.2                    download https://github.com/tgdev/animate-sass/archive/v0.6.2.tar.gz
bower Sortable#~1.0.0                        download https://github.com/RubaXa/Sortable/archive/1.0.0.tar.gz
bower humane-js#~3.2.2                        extract archive.tar.gz
bower humane-js#~3.2.2                   invalid-meta humane-js is missing "ignore" entry in bower.json
bower humane-js#~3.2.2                       resolved git://github.com/wavded/humane-js.git#3.2.2
bower jquery-serialize-object#~2.4.3          extract archive.tar.gz
bower jquery-serialize-object#~2.4.3         resolved git://github.com/macek/jquery-serialize-object.git#2.4.3
bower jquery#^1.11.1                       not-cached git://github.com/jquery/jquery.git#^1.11.1
bower jquery#^1.11.1                          resolve git://github.com/jquery/jquery.git#^1.11.1
bower jquery#^1.11.1                         download https://github.com/jquery/jquery/archive/1.11.2.tar.gz
bower jquery-minicolors#~2.1.10               extract archive.tar.gz
bower jquery-minicolors#~2.1.10              resolved git://github.com/claviska/jquery-minicolors.git#2.1.10
bower bootstrap-sass-official#~3.3.1          extract archive.tar.gz
bower animate-sass#~0.6.2                     extract archive.tar.gz
bower bootstrap-sass-official#~3.3.1         resolved git://github.com/twbs/bootstrap-sass.git#3.3.1
bower jquery#>= 1.9.0                      not-cached git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.9.0                         resolve git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.9.0                        download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower animate-sass#~0.6.2                    resolved git://github.com/tgdev/animate-sass.git#0.6.2
bower lodash#~2.4.1                           extract archive.tar.gz
bower Sortable#~1.0.0                         extract archive.tar.gz
bower lodash#~2.4.1                          resolved git://github.com/lodash/lodash.git#2.4.1
bower messenger#~1.4.1                        extract archive.tar.gz
bower ionicons#~2.0.0                         extract archive.tar.gz
bower jquery#~2.1.1                           extract archive.tar.gz
bower Sortable#~1.0.0                        resolved git://github.com/RubaXa/Sortable.git#1.0.0
bower messenger#~1.4.1                       resolved git://github.com/HubSpot/messenger.git#1.4.1
bower jquery#*                             not-cached git://github.com/jquery/jquery.git#*
bower jquery#*                                resolve git://github.com/jquery/jquery.git#*
bower jquery#*                               download https://github.com/jquery/jquery/archive/2.1.3.tar.gz
bower jquery#^1.11.1                          extract archive.tar.gz
bower jquery#~2.1.1                          resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.0                         extract archive.tar.gz
bower jquery#^1.11.1                         resolved git://github.com/jquery/jquery.git#1.11.2
bower jquery#>= 1.9.0                        resolved git://github.com/jquery/jquery.git#2.1.3
bower jquery#*                                extract archive.tar.gz
bower jquery#*                               resolved git://github.com/jquery/jquery.git#2.1.3
bower ionicons#~2.0.0                        resolved git://github.com/driftyco/ionicons.git#2.0.0

Please note that,
    jquery-serialize-object#2.4.3 depends on jquery#^1.11.1 which resolved to jquery#1.11.2
    Cachet depends on jquery#~2.1.1 which resolved to jquery#2.1.3
    bootstrap-sass-official#3.3.1 depends on jquery#>= 1.9.0 which resolved to jquery#2.1.3
    messenger#1.4.1 depends on jquery#* which resolved to jquery#2.1.3
Resort to using jquery#~2.1.1 which resolved to jquery#2.1.3
Code incompatibilities may occur.

bower humane-js#~3.2.2                        install humane-js#3.2.2
bower jquery-serialize-object#~2.4.3          install jquery-serialize-object#2.4.3
bower jquery-minicolors#~2.1.10               install jquery-minicolors#2.1.10
bower bootstrap-sass-official#~3.3.1          install bootstrap-sass-official#3.3.1
bower animate-sass#~0.6.2                     install animate-sass#0.6.2
bower lodash#~2.4.1                           install lodash#2.4.1
bower Sortable#~1.0.0                         install Sortable#1.0.0
bower messenger#~1.4.1                        install messenger#1.4.1
bower jquery#~2.1.1                           install jquery#2.1.3
bower ionicons#~2.0.0                         install ionicons#2.0.0
``

**Comment by joecohens** [comment]
This is a npm error, can you run `npm install` please?

**Comment by ajtrichards** [comment]
When i'm running that command I get:

```nodejs
npm WARN package.json @ No repository field.
npm WARN unmet dependency /var/www/html/status.evaluagent.net/node_modules/bower/node_modules/bower-registry-client/node_modules/request/node_modules/form-data requires async@'~0.9.0' but will load
npm WARN unmet dependency /var/www/html/status.evaluagent.net/node_modules/bower/node_modules/bower-registry-client/node_modules/async,
npm WARN unmet dependency which is version 0.2.10
```

**Comment by Crash--** [comment]
Can you : 
- `rm -f /var/www/html/status.evaluagent.net/node_modules/` (in the case of the first installation failed due to a network error) 
- `npm cache clear`
- `npm install`

**Comment by jbrooksuk** [comment]
I wonder if one of the other modules is clashing?

**Comment by jbrooksuk** [comment]
Can you try again, #324 has added `array-union` which could help fix any Gulp install errors :)

**Comment by jbrooksuk** [comment]
Also, you're not running Debian Wheezy or CentOS 6 are you? If so, see #275.

**Comment by ajtrichards** [comment]
Hi James,

Works fine now - followed @Crash-- instructions and re-run Gulp and i'm in.

I was running this on Homestead.

Thanks

**Comment by jbrooksuk** [comment]
Good news :)
