### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by kaipitu** [CachetHQ/Cachet#3301]
Hi,

After some days successfully running cachet, it always throws an `500 Internal Server Error`.
This can be fixed by running either `php artisan config:cache` or `rm -Rf bootstrap/cache/*`.
But after some days the same error occurs again.

cachet version: 2.3.15
php version: 7.0.31

.env file:
```
APP_ENV=production
APP_DEBUG=false
APP_URL=status.my_domain.tld
APP_KEY=base64:lGqDp**********************************AcBP=

DB_DRIVER=mysql
DB_HOST=my_db_host
DB_DATABASE=my_database
DB_USERNAME=my_user
DB_PASSWORD=my_password
DB_PORT=3306
DB_PREFIX=null
MYSQL_SSL_CA=/path/to/my_certificate.crt

CACHE_DRIVER=redis
SESSION_DRIVER=redis
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls

REDIS_HOST=my_redis_host
REDIS_PORT=6379

GITHUB_TOKEN=null
```

laravel logs:
```
[2018-11-02 13:41:01] production.ERROR: InvalidArgumentException: View [index] not found. in /home/vcap/app/bootstrap/cache/compiled.php:14401
Stack trace:
#0 /home/vcap/app/bootstrap/cache/compiled.php(14374): Illuminate\View\FileViewFinder->findInPaths('index', Array)
#1 /home/vcap/app/bootstrap/cache/compiled.php(14504): Illuminate\View\FileViewFinder->find('index')
#2 /home/vcap/app/bootstrap/cache/compiled.php(6325): Illuminate\View\Factory->make('index')
#3 /home/vcap/app/app/Http/Controllers/StatusPageController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 [internal function]: CachetHQ\Cachet\Http\Controllers\StatusPageController->showIndex()
#5 /home/vcap/app/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#6 /home/vcap/app/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('showIndex', Array)
#7 /home/vcap/app/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\StatusPageController), Object(Illuminate\Routing\Route), 'showIndex')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home/vcap/app/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /home/vcap/app/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /home/vcap/app/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\StatusPageController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showIndex')
#14 /home/vcap/app/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showIndex')
#15 /home/vcap/app/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#16 /home/vcap/app/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /home/vcap/app/app/Http/Middleware/Localize.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: CachetHQ\Cachet\Http\Middleware\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /home/vcap/app/app/Http/Middleware/ReadyForUse.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: CachetHQ\Cachet\Http\Middleware\ReadyForUse->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /home/vcap/app/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /home/vcap/app/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /home/vcap/app/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /home/vcap/app/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /home/vcap/app/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /home/vcap/app/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /home/vcap/app/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /home/vcap/app/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#58 /home/vcap/app/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#59 /home/vcap/app/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#61 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /home/vcap/app/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /home/vcap/app/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /home/vcap/app/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#70 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /home/vcap/app/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /home/vcap/app/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 /home/vcap/app/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /home/vcap/app/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#76 /home/vcap/app/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#77 {main} {"identification":{"id":"8571623e-34dd-4968-b9cd-44c839b6ef24"}}
```

I already switched the cache and session drivers from file to redis, tried different php versions but it did not help.
I hope someone can point me in a direction (cachet - php version incompatibility, configuration error). Thx.

**Comment by GrahamCampbell** [comment]
Does the user running php-fpm have permission to read the files in https://github.com/CachetHQ/Cachet/tree/2.3/resources/views?

**Comment by kaipitu** [comment]
@GrahamCampbell yes:
```
vcap@62ec7ccb-cfcf-44f5-568f-cb0e:~$ ps -ef | grep php-fpm
vcap          43      18  0 Nov06 ?        00:00:00 /bin/sh -c $HOME/php/sbin/php-fpm -p "$HOME/php/etc" -y "$HOME/php/etc/php-fpm.conf" -c "$HOME/php/etc"
vcap          49      43  0 Nov06 ?        00:00:06 php-fpm: master process (/home/vcap/app/php/etc/php-fpm.conf)                                                             
vcap         134      49  0 Nov06 ?        00:00:00 php-fpm: pool www                                                                                                         
vcap         135      49  0 Nov06 ?        00:00:00 php-fpm: pool www                                                                                                         
vcap         271     245  0 08:07 pts/0    00:00:00 grep php-fpm

vcap@62ec7ccb-cfcf-44f5-568f-cb0e:~$ whoami
vcap

vcap@62ec7ccb-cfcf-44f5-568f-cb0e:~$ ls -ltr resources/views/*
-rw-r--r--  1 vcap vcap   905 Nov  2 15:02 resources/views/single-incident.blade.php
-rw-r--r--  1 vcap vcap  1815 Nov  2 15:02 resources/views/signup.blade.php
-rw-r--r--  1 vcap vcap 12954 Nov  2 15:02 resources/views/setup.blade.php
-rw-r--r--  1 vcap vcap  1578 Nov  2 15:02 resources/views/index.blade.php

resources/views/subscribe:
total 8
-rw-r--r-- 1 vcap vcap 1055 Nov  2 15:02 subscribe.blade.php
-rw-r--r-- 1 vcap vcap 2287 Nov  2 15:02 manage.blade.php

resources/views/partials:
total 60
-rw-r--r-- 1 vcap vcap 3629 Nov  2 15:02 stylesheet.blade.php
-rw-r--r-- 1 vcap vcap  705 Nov  2 15:02 schedule.blade.php
-rw-r--r-- 1 vcap vcap 1347 Nov  2 15:02 nav.blade.php
drwxr-xr-x 2 vcap vcap   33 Nov  2 15:02 modals
-rw-r--r-- 1 vcap vcap 6140 Nov  2 15:02 metrics.blade.php
-rw-r--r-- 1 vcap vcap 1048 Nov  2 15:02 incidents.blade.php
-rw-r--r-- 1 vcap vcap 1470 Nov  2 15:02 incident.blade.php
-rw-r--r-- 1 vcap vcap 1579 Nov  2 15:02 footer.blade.php
-rw-r--r-- 1 vcap vcap 2932 Nov  2 15:02 email-css.blade.php
-rw-r--r-- 1 vcap vcap  215 Nov  2 15:02 crowdin.blade.php
-rw-r--r-- 1 vcap vcap 1269 Nov  2 15:02 components.blade.php
-rw-r--r-- 1 vcap vcap  750 Nov  2 15:02 component.blade.php
-rw-r--r-- 1 vcap vcap  725 Nov  2 15:02 banner.blade.php
-rw-r--r-- 1 vcap vcap 1576 Nov  2 15:02 analytics.blade.php
-rw-r--r-- 1 vcap vcap  129 Nov  2 15:02 about-app.blade.php

resources/views/layout:
total 20
-rw-r--r-- 1 vcap vcap 3174 Nov  2 15:02 master.blade.php
-rw-r--r-- 1 vcap vcap 7237 Nov  2 15:02 emails.blade.php
-rw-r--r-- 1 vcap vcap  282 Nov  2 15:02 dashboard.blade.php
-rw-r--r-- 1 vcap vcap  184 Nov  2 15:02 clean.blade.php

resources/views/emails:
total 0
drwxr-xr-x 2 vcap vcap  64 Nov  2 15:02 users
drwxr-xr-x 2 vcap vcap  64 Nov  2 15:02 subscribers
drwxr-xr-x 2 vcap vcap 126 Nov  2 15:02 incidents
drwxr-xr-x 2 vcap vcap  64 Nov  2 15:02 components

resources/views/dashboard:
total 8
drwxr-xr-x 2 vcap vcap   29 Nov  2 15:02 user
drwxr-xr-x 2 vcap vcap   72 Nov  2 15:02 templates
drwxr-xr-x 2 vcap vcap   96 Nov  2 15:02 team
drwxr-xr-x 2 vcap vcap   50 Nov  2 15:02 subscribers
drwxr-xr-x 2 vcap vcap  223 Nov  2 15:02 settings
drwxr-xr-x 2 vcap vcap   72 Nov  2 15:02 schedule
drwxr-xr-x 2 vcap vcap  216 Nov  2 15:02 partials
drwxr-xr-x 2 vcap vcap   29 Nov  2 15:02 notifications
drwxr-xr-x 2 vcap vcap   72 Nov  2 15:02 metrics
-rw-r--r-- 1 vcap vcap 4302 Nov  2 15:02 index.blade.php
drwxr-xr-x 2 vcap vcap   72 Nov  2 15:02 incidents
drwxr-xr-x 3 vcap vcap   86 Nov  2 15:02 components

resources/views/auth:
total 20
-rw-r--r-- 1 vcap vcap 12883 Nov  2 15:02 two-factor-auth.blade.php
-rw-r--r-- 1 vcap vcap  2227 Nov  2 15:02 login.blade.php
```

**Comment by SybilSystem** [comment]
I too am having this same issue. [The logs](https://gist.github.com/SybilSystem/9325fbba82c4889e0a565a499cc37918) are here if you need them.

**Comment by GrahamCampbell** [comment]
@SybilSystem Looks like your using an old version of Cachet that only is compatible with up to PHP 7.1, not 7.2.

**Comment by SybilSystem** [comment]
@GrahamCampbell So the latest version is 2.4 and that is compatible with up to 7.1?

**Comment by jbrooksuk** [comment]
Correct!

**Comment by GrahamCampbell** [comment]
> @GrahamCampbell So the latest version is 2.4 and that is compatible with up to 7.1?

No, **2.3** is the latest release, and will work on PHP upto 7.1. Very latest unreleased **2.4** will work on up to PHP 7.3.
