### ISSUE TITLE
Error PHP fatal error

### ISSUE THREAD

**Issue by Dream-cake** [CachetHQ/Cachet#3318]
when i go to http://status.dreaming.ga/ it sends me to http://status.dreaming.ga/setup but it gives an 500 so i looked at the apache2 logs and i get this

```
[Sat Nov 10 20:10:43.600118 2018] [mpm_prefork:notice] [pid 4510] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sat Nov 10 20:10:43.600175 2018] [core:notice] [pid 4510] AH00094: Command line: '/usr/sbin/apache2'
[Sat Nov 10 20:10:45.751097 2018] [php7:error] [pid 4519] [client 107.3.16.135:57697] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/C...', 51, Array)\n#1 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)\n#2 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 /var/www/html/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
[Sat Nov 10 20:10:45.751551 2018] [php7:error] [pid 4519] [client 107.3.16.135:57697] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/html/C...', 51, Array)\n#1 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)\n#2 /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#3 /var/www/html/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n#4 /var/www/html/Cachet/bootstrap/cache/compiled.php(2181): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException))\n in /var/www/html/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
```
[error in a hastebin](https://codeformat.dreaming.ga/gewomijozu.cs)

How do i fix this please help.

-Spooder#1111

**Comment by Dream-cake** [comment]
new error

```
[Sat Nov 10 21:31:38.328340 2018] [php7:error] [pid 6045] [client 107.3.16.135:49283] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/Cachet/storage/logs/laravel-2018-11-10.log" could not be opened: failed to open stream: Permission denied in /var/www/html/Cachet/bootstrap/cache/compiled.php:13832\nStack trace:\n#0 /var/www/html/Cachet/bootstrap/cache/compiled.php(13933): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/Cachet/bootstrap/cache/compiled.php(13762): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/Cachet/bootstrap/cache/compiled.php(13522): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/Cachet/bootstrap/cache/compiled.php(13620): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#4 /var/www/html/Cachet/bootstrap/cache/compiled.php(13315): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#5 /var/www/html/Cachet/bootstrap/cache/compiled.php(13286): Illuminate\\Log\\Writer->writeLog('error', Object(UnexpectedValueException), Array)\n#6 /var/www/html/Cachet/vendor/graham-campb in /var/www/html/Cachet/bootstrap/cache/compiled.php on line 13832
[Sat Nov 10 21:31:38.328553 2018] [php7:error] [pid 6045] [client 107.3.16.135:49283] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/Cachet/storage/logs/laravel-2018-11-10.log" could not be opened: failed to open stream: Permission denied in /var/www/html/Cachet/bootstrap/cache/compiled.php:13832\nStack trace:\n#0 /var/www/html/Cachet/bootstrap/cache/compiled.php(13933): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/Cachet/bootstrap/cache/compiled.php(13762): Monolog\\Handler\\RotatingFileHandler->write(Array)\n#2 /var/www/html/Cachet/bootstrap/cache/compiled.php(13522): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#3 /var/www/html/Cachet/bootstrap/cache/compiled.php(13628): Monolog\\Logger->addRecord(500, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/html/Cachet/bootstrap/cache/compiled.php(13315): Monolog\\Logger->critical(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/html/Cachet/bootstrap/cache/compiled.php(13282): Illuminate\\Log\\Writer->writeLog('critical', Object(Symfony\\Compo in /var/www/html/Cachet/bootstrap/cache/compiled.php on line 13832
```

**Comment by Dream-cake** [comment]
New error

I tried reinstalling it and i got this

![image](https://user-images.githubusercontent.com/31389391/48306431-6614be00-e506-11e8-95af-652c6c5771cf.png)

**Comment by Dream-cake** [comment]
Nvm i changed to 7.1 :D

**Comment by Dream-cake** [comment]
new error when i go to http://status.dreaming.ga/dashboard

```
[2018-11-11 00:17:53] production.CRITICAL: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function CachetHQ\Cachet\Integrations\simplexml_load_string() in /var/www/html/Cachet/app/Integrations/Feed.php:76
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(292): CachetHQ\Cachet\Integrations\Feed->CachetHQ\Cachet\Integrations\{closure}()
#1 /var/www/html/Cachet/app/Integrations/Feed.php(84): Illuminate\Cache\Repository->remember('feeds', 720, Object(Closure))
#2 /var/www/html/Cachet/app/Http/Controllers/Dashboard/DashboardController.php(87): CachetHQ\Cachet\Integrations\Feed->latest()
#3 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController->showDashboard()
#4 /var/www/html/Cachet/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#5 /var/www/html/Cachet/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('showDashboard', Array)
#6 /var/www/html/Cachet/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Routing\Route), 'showDashboard')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /var/www/html/Cachet/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/html/Cachet/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showDashboard')
#13 /var/www/html/Cachet/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showDashboard')
#14 /var/www/html/Cachet/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#15 /var/www/html/Cachet/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /var/www/html/Cachet/app/Http/Middleware/Authenticate.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /var/www/html/Cachet/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/html/Cachet/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /var/www/html/Cachet/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/html/Cachet/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /var/www/html/Cachet/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /var/www/html/Cachet/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/html/Cachet/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /var/www/html/Cachet/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /var/www/html/Cachet/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/html/Cachet/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/html/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/html/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /var/www/html/Cachet/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /var/www/html/Cachet/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /var/www/html/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 {main} {"identification":{"id":"17776e01-87a0-4b8d-ae9d-6eec4fb53175"}} 
```

**Comment by Dream-cake** [comment]
I got it working but does it accuracy monitor sites and ips and report it?

**Comment by Dream-cake** [comment]
and i have subscirber button on and its adding the user but its not sending the email to verfiy them self and i check spam and the logs nothing :/

**Comment by jbrooksuk** [comment]
Do you have the cron running?
