### ISSUE TITLE
Error 500 when trying to access /setup

### ISSUE THREAD

**Issue by Flusinerd** [CachetHQ/Cachet#3346]
Hello, Im trying to install Cachet on my Windows Apache-Webserver.
I am getting the following error, when trying to run the `composer install --no-dev -o` command: 

`Script php artisan optimize --force handling the post-install-cmd event returned with error code 255`

I can run the same command with the `-no-scripts` flag without issues. But I cannot access the page after install, when it redirects me to `/setup`.

My access.log:
```
84.118.113.207 - - [27/Nov/2018:10:44:17 +0100] "GET / HTTP/1.1" 302 364
84.118.113.207 - - [27/Nov/2018:10:44:18 +0100] "GET /setup HTTP/1.1" 500 
```

My VHost:
```
DocumentRoot "C:\Apache24\htdocs\status\public"
DirectoryIndex index.php
<Directory "C:\Apache24\htdocs\status\public">
	Options Indexes MultiViews FollowSymLinks
	AllowOverride all
	Require all granted
</Directory>
```

My enabled modules:
```
LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule allowmethods_module modules/mod_allowmethods.so
LoadModule asis_module modules/mod_asis.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule autoindex_module modules/mod_autoindex.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule include_module modules/mod_include.so
LoadModule info_module modules/mod_info.so
LoadModule isapi_module modules/mod_isapi.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule negotiation_module modules/mod_negotiation.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule ssl_module modules/mod_ssl.so
LoadModule status_module modules/mod_status.so
```

The php_errors.log in the project folder:
```
[27-Nov-2018 10:00:24 UTC] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'C:\\Apache24\\htd...', 51, Array)
#1 C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(51): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 C:\Apache24\htdocs\status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
[27-Nov-2018 10:00:24 UTC] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'C:\\Apache24\\htd...', 51, Array)
#1 C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(51): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 C:\Apache24\htdocs\status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 C:\Apache24\htdocs\status\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(118): in C:\Apache24\htdocs\status\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
````

My Apache2 Error.log is clean

Any suggestions on how to fix this?
I am trying to install the latest version

Sincerly,
Jan

**Comment by Flusinerd** [comment]
Sry, I forgot my .env

APP_ENV=production
APP_DEBUG=false
APP_URL=http://62.138.21.253:502/
APP_KEY=d08huzFBvyfuobsV2D0fn4EeTwZnsAVX

DB_DRIVER=mysql
DB_HOST=130.180.31.138
DB_DATABASE=navigatemStatus
DB_USERNAME=###
DB_PASSWORD=###
DB_PORT=3306

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=database
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

Yes, the SQL-Server runs on a different machine, but there are no issues with that server, since my other services are working fine

**Comment by Didr** [comment]
Can you post a list of your loaded PHP extensions?

**Comment by Extarys** [comment]
I face the same issue.

`php -v`
PHP 7.2.13 (cli) (built: Dec  8 2018 12:11:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies


`php -m` returns:
```
[PHP Modules]
apc
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
openssl
pcntl
pcre
PDO
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zlib
```

public folder have permission 770
status.domain.com folder have 750 persmission
status.domain.com/storage folder have 777 permission

**Comment by agentcobra** [comment]
see #3301
> No, 2.3 is the latest release, and will work on PHP upto 7.1. Very latest unreleased 2.4 will work on up to PHP 7.3.

**Comment by Extarys** [comment]
I couldn't install version 2.4 as it didn't appear in the list of available versions, but I'll be patient :D

**Comment by MayhemBill** [comment]
I have this issue, but I am running the latest git commit to 2.4?

**Comment by shengbinxu** [comment]
I have the same error。
as @agentcobra say, my php version is 7.2. and after I change branch to 2.4, and execute 'composer install', and all is ok
