### ISSUE TITLE
Timeout for cURL / GuzzleHttp

### ISSUE THREAD

**Issue by diekmanu** [CachetHQ/Cachet#3354]
When opening the dashboard the webserver tries to get the lastest release/build info:

```
[2018-12-04 10:17:55] production.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to api.github.com port 443: Timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:185
Stack trace:
#0 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Handler\Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#13 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\guzzlehttp\guzzle\src\Client.php(89): GuzzleHttp\Client->request('get', 'https://api.git...', Array)
#14 D:\SYSTEM\WPN-XM\www\cachet_v2\app\Integrations\GitHub\Releases.php(89): GuzzleHttp\Client->__call('get', Array)
#15 D:\SYSTEM\WPN-XM\www\cachet_v2\vendor\laravel\framework\src\Illuminate\Cache\Repository.php(327): CachetHQ\Cachet\Integrations\GitHub\Releases->CachetHQ\Cachet\Integrations\GitHub\{closure}()
#16 D:\SYSTEM\WPN-XM\www\cachet_v2\app\Integrations\GitHub\Releases.php(91): Illuminate\Cache\Repository->remember('release.latest', 720, Object(Closure))
#17 D:\SYSTEM\WPN-XM\www\cachet_v2\app\Http\Controllers\Api\GeneralController.php(41): CachetHQ\Cachet\Integrations\GitHub\Releases->latest()
#18 [internal function]: CachetHQ\Cachet\Http\Controllers\Api\GeneralController->version()
```
This is quite annoying, when the webserver has no access to the outside world and leads to timeouts (>30secs) while browsing the dashboard.

Can this be disabled for internal servers? 

Third Party Dependencies (Google Fonts, Trackers, etc...) are disabled.

Thanks!

**Comment by jbrooksuk** [comment]
This is one of a few things:

1. Checking for updates.
2. Checking for blog posts.
3. Finding the list of contributors / donators.

Which dashboard page is it?

**Comment by GrahamCampbell** [comment]
Looks like you have emojis enabled, but are blocking web access for your sever. Please turn off emojis, and your issue will be resolved.

**Comment by GrahamCampbell** [comment]
Done in https://github.com/AltThree/Emoji/commit/d1ceb83ca11c0c5b2fef505772e96d9061d942c0.
