### ISSUE TITLE
Failed to update Cachet Dashboard due to SSL Error 112

### ISSUE THREAD

**Issue by harika224121** [CachetHQ/Cachet#3419]
Hi,

Our cachet Dashboard is not getting updated even after the service comes up and running. The status of the service remains same as non-operational. We need to manually change it to operational after recovering the service from failure. I found this error message in the logs:-

Error:

Failed to update external Cachet dashboard: { Error: write EPROTO 140431734950016:error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name:s3_pkt.c:1493:SSL alert number 112
140431734950016:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:659:

at exports._errnoException (util.js:1020:11)
at WriteWrap.afterWrite (net.js:806:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write'

I think this might be the reason for not getting updated. Can anyone please help us with this issue.

**Comment by harika224121** [comment]
Hi @jbrooksuk  thanks for responding to my query we are using api-dashboard-engine to automatically updtae the cachet dashboard.  So whenever the service comes up and running it should update the component status from major outage to operational but for few services it is not updating then we need to manually change the status of the component. This is the issue we are facing currently. can you help us with this issue please.
