### ISSUE TITLE
Cannot install due to php fatal error

### ISSUE THREAD

**Issue by iniOr** [CachetHQ/Cachet#3527]
Hi,

trying to install on Scientific Linux release 7.5 (Nitrogen)

when running the following command : 

`composer install --no-dev -o`

i get this error :

```
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Package graham-campbell/core is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize --force
**PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734**
Stack trace:
#0 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /var/www/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Foundation\Application->make('log')
#4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application))
#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)
#6 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
Script php artisan optimize --force handling the post-install-cmd event returned with error code 255
```

- .env file with no spaces, I even tested with all values between double quotes.

- rpm -qa |grep php :

```
php-7.2.16-1.el7.remi.x86_64
php-gd-7.2.16-1.el7.remi.x86_64
php72-php-mysqlnd-7.2.16-1.el7.remi.x86_64
php72-php-json-7.2.16-1.el7.remi.x86_64
php-common-7.2.16-1.el7.remi.x86_64
php-xml-7.2.16-1.el7.remi.x86_64
php72-php-common-7.2.16-1.el7.remi.x86_64
php-cli-7.2.16-1.el7.remi.x86_64
php72-php-pdo-7.2.16-1.el7.remi.x86_64
php72-runtime-2.0-1.el7.remi.x86_64
php-json-7.2.16-1.el7.remi.x86_64
php-mbstring-7.2.16-1.el7.remi.x86_64

```
Tested with 2.3.14 same issue, how can I install this app ?
Thanks for any help...

**Comment by iniOr** [comment]
On previous deployment I had to run the composer install command as httpd user but here on Scientific Linux even while running this as httpd user I get the exact same error :

`PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734`

**Comment by iniOr** [comment]
Doing more test with nginx but can't issue this command succesfully :
`
php72 artisan optimize --force`

result :
```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Foundation\Application->make('log')
#4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application))
#5 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)
#6 /usr/share/nginx/Cachet/ven in /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
```
Don't know how to debug further.

**Comment by iniOr** [comment]
Same error whit the next command :

php72 artisan key:generate

result 

```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:734
Stack trace:
#0 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(734): ReflectionClass->__construct('log')
#1 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build('log', Array)
#2 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandler.php(60): Illuminate\Foundation\Application->make('log')
#4 [internal function]: GrahamCampbell\Exceptions\ExceptionHandler->__construct(Object(Illuminate\Foundation\Application))
#5 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->newInstanceArgs(Array)
#6 /usr/share/nginx/Cachet/ven in /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 734
```

**Comment by iniOr** [comment]
Finally I found that tag 2.3.15 installs Laravel version 5.2 witch is not compatible with PHP72.

Going on branch 2.4 allowed me to solve this.
