### ISSUE TITLE
The component update fails (apparently) due to a temporary mail delivery error

### ISSUE THREAD

**Issue by sdinot** [CachetHQ/Cachet#3614]
Dear developers,

I use Cachet 2.3.18 (but I got the same error before update with version 2.3.9)

When I try to update the properties of a component (for example, its link), I get a "Error 500, Internal Server Error" due to a temporary error on mail delivery (4.7.1 Try again later).

Here is the first lines of the log:
```log
[2019-05-21 20:34:29] production.ERROR: Swift_TransportException: Expected response code 250 but got code "451", with message "451 4.7.1 Try again later
" in /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('451 4.7.1 Try a...', Array)
#1 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('\r\n.\r\n', Array, Array)
#2 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(333): Swift_Transport_EsmtpTransport->executeCommand('\r\n.\r\n', Array)
#3 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(428): Swift_Transport_AbstractSmtpTransport->_streamMessage(Object(Swift_Message))
#4 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(444): Swift_Transport_AbstractSmtpTransport->_doMailTransaction(Object(Swift_Message), 'cachet@orfeo-to...', Ar
ray, Array)
#5 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(176): Swift_Transport_AbstractSmtpTransport->_sendTo(Object(Swift_Message), 'cachet@orfeo-to...', Array, Array)
#6 /var/www/status.orfeo-toolbox.org/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(85): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(276): Illuminate\Mail\Mailer->send('emails.componen...', Array, Object(Closure))
#10 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(130): Illuminate\Mail\Mailer->handleQueuedMessage(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#11 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Queue/Jobs/SyncJob.php(44): Illuminate\Queue\Jobs\Job->resolveAndFire(Array)
#12 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(30): Illuminate\Queue\Jobs\SyncJob->fire()
#13 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(187): Illuminate\Queue\SyncQueue->push('mailer@handleQu...', Array, NULL)
#14 /var/www/status.orfeo-toolbox.org/app/Bus/Handlers/Events/Component/SendComponentUpdateEmailNotificationHandler.php(111): Illuminate\Mail\Mailer->queue(Array, Array, 'C:32:"SuperClos...')
#15 /var/www/status.orfeo-toolbox.org/app/Bus/Handlers/Events/Component/SendComponentUpdateEmailNotificationHandler.php(66): CachetHQ\Cachet\Bus\Handlers\Events\Component\SendComponentUpdateEmailNotificationHandler->notify(Object(Cac
hetHQ\Cachet\Presenters\ComponentPresenter), Object(CachetHQ\Cachet\Models\Subscriber))
#16 [internal function]: CachetHQ\Cachet\Bus\Handlers\Events\Component\SendComponentUpdateEmailNotificationHandler->handle(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent))
#17 /var/www/status.orfeo-toolbox.org/bootstrap/cache/compiled.php(10179): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent))
#19 /var/www/status.orfeo-toolbox.org/bootstrap/cache/compiled.php(10124): call_user_func_array(Object(Closure), Array)
#20 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(419): Illuminate\Events\Dispatcher->fire('CachetHQ\\Cachet...', Array, false)
#21 /var/www/status.orfeo-toolbox.org/app/Bus/Handlers/Commands/Component/UpdateComponentCommandHandler.php(33): event(Object(CachetHQ\Cachet\Bus\Events\Component\ComponentWasUpdatedEvent))
#22 [internal function]: CachetHQ\Cachet\Bus\Handlers\Commands\Component\UpdateComponentCommandHandler->handle(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#23 /var/www/status.orfeo-toolbox.org/vendor/alt-three/bus/src/Dispatcher.php(225): call_user_func(Array, Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#24 [internal function]: AltThree\Bus\Dispatcher->AltThree\Bus\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#25 /var/www/status.orfeo-toolbox.org/bootstrap/cache/compiled.php(9960): call_user_func(Object(Closure), Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#26 /var/www/status.orfeo-toolbox.org/app/Bus/Middleware/UseDatabaseTransactions.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(CachetHQ\Cachet\Bus\Commands\Component\UpdateComponentCommand))
#27 /var/www/status.orfeo-toolbox.org/vendor/laravel/framework/src/Illuminate/Database/Connection.php(527): CachetHQ\Cachet\Bus\Middleware\UseDatabaseTransactions->CachetHQ\Cachet\Bus\Middleware\{closure}(Object(Illuminate\Database\M
ySqlConnection))
#28 [internal function]: Illuminate\Database\Connection->transaction(Object(Closure))
```

It's an embarrassing bug, but your great tool provides a valuable service to the Orfeo Toolbox community! Thanks a lot!

**Comment by jbrooksuk** [comment]
Hi @sdinot! Thanks for reporting this. 

I have to ask, but have you confirmed that the mail details you provided to Cachet do in fact work?

**Comment by sdinot** [comment]
> I have to ask, but have you confirmed that the mail details you provided to Cachet do in fact work?

Yes, of course! ;)

Actually, several recipients work for the same company. The mail server of this company performs in the same way for all recipients: the first message of the day from a given address causes a temporary error, asking the SMTP server that sends the message to try again later ("4.7.1 Try again later"). If the SMTP send the same message a few minutes later, this second send is accepted without error. Other messages of the day from the same sender (email, not SMTP server) to the same recipient are accepted immediately, without temporary error. This behaviour is a pretty good protection against spam.

When I first update the component properties, the temporary message delivery error occurs for the first recipient of this company. If I make a second update attempt, the message sent to the first recipient of this company passes, but not the one sent to the second recipient of this company.

So, the configuration is right.

But even if an email is obsolete or wrong, or if a SMTP server is unavailable, the update of the component must not fail. However, here, it fails. ;)

**Comment by sdinot** [comment]
@jbrooksuk : I'm seeing in the issue history that you added the resolution of this issue to the v2.3.14 milestone but I already use v2.3.18. :)

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
