### ISSUE TITLE
Cannot finish setup, error 500

### ISSUE THREAD

**Issue by Cypaubr** [CachetHQ/Cachet#3719]
I searched in the logs the error is:
`Parameter must be an array or an object that implements Countable`

**Comment by peterlewis** [comment]
Just checking, have you tried the troubleshooting steps under "Getting a 500 - Internal Server Error?" from the [installation guide](https://docs.cachethq.io/docs/installing-cachet). Clearing the cache folder resolved this issue, for me.

**Comment by drewklein20** [comment]
Check out #3623

**Comment by Cypaubr** [comment]
@drewklein20 I saw thi issue but "Use PHP 7.1" is not a true solution...

**Comment by diegosouza** [comment]
@drewklein20 a true solution (following your thinking) is to have some full time devs on the project. They'd care about project dependencies and the compatibility to most PHP versions. Unfortunately it seems not to be the case.

Could you provide some more details?

- O.S and PHP version
- Installation from sources or docker
- Cachet version (or last commit from a dev branch you're using)
- Link/url/step you called (maybe with the data you've passed)
- Full log entries, not ony the main message

**Comment by ogelpre** [comment]
I have the same issue with Cachet 2.3.18, nginx 1.16.1, php 7.2.22, MariaDB 10.3.1 on FreeBSD 11.2p. Full Trace:

```
[2019-10-18 20:12:03] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1161
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/scc.fa...', 1161, Array)
#1 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1161): count(NULL)
#2 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1192): Illuminate\Database\Eloquent\Builder->callScope(Object(Closure))
#3 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(314): Illuminate\Database\Eloquent\Builder->applyScopes()
#4 /var/www/scc.fail/app/Http/Controllers/Dashboard/DashboardController.php(79): Illuminate\Database\Eloquent\Builder->get()
#5 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController->showDashboard()
#6 /var/www/scc.fail/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#7 /var/www/scc.fail/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('showDashboard', Array)
#8 /var/www/scc.fail/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Routing\Route), 'showDashboard')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/scc.fail/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/scc.fail/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/scc.fail/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showDashboard')
#15 /var/www/scc.fail/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showDashboard')
#16 /var/www/scc.fail/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#17 /var/www/scc.fail/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/scc.fail/app/Http/Middleware/Authenticate.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /var/www/scc.fail/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/scc.fail/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /var/www/scc.fail/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /var/www/scc.fail/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/scc.fail/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/scc.fail/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/scc.fail/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/scc.fail/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#54 /var/www/scc.fail/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 /var/www/scc.fail/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 /var/www/scc.fail/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 /var/www/scc.fail/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/scc.fail/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /var/www/scc.fail/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /var/www/scc.fail/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 /var/www/scc.fail/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#71 /var/www/scc.fail/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 /var/www/scc.fail/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#73 {main} {"identification":{"id":"301e2bfe-f602-470d-8c15-50699cb4668f"}} 
```

**Comment by diegosouza** [comment]
@ogelpre it is a bug in `illuminate\database` module (for php > 7.2), that was already fixed after some Laravel releases. Unfortunately the activity in this project is low, so it may not be fixed soon.

**Comment by brocasm** [comment]
I have same problem with php 7.3 and same with new install with php 7.0

**Comment by defulmere** [comment]
I had this same problem with PHP 7.3 and solved it by switching to the 2.4 branch immediately after checkout and prior to doing anything else:

```
git clone https://github.com/cachethq/Cachet.git
cd Cachet
git checkout 2.4
```

After doing so I was able to complete setup using the [v2.4 installation instructions](https://github.com/CachetHQ/Cachet/blob/2.4/docs/setup/installation.md).

**Comment by JaggedJax** [comment]
I was able to hack this into working by changing the error_reporting level in: vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php

By setting line 31 to: `error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);` instead of `error_reporting(-1);`

This turns off PHP Notices and Warnings. Yes this is bad, but you gotta do what you gotta do.

**Comment by rohanlucifer** [comment]
I am getting this 500 error .....while adding subscriber...testing emails
please help me!!!
can anyone plz describe me setting smtp server

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
