### ISSUE TITLE
Fails to load dashboard because of a Feed that returns 1

### ISSUE THREAD

**Issue by tomecho** [CachetHQ/Cachet#3844]
# Versions
* cachethq/docker:2.3.15

This only appears to be an issue on 2.3, which is the latest available of the docker image.  Not sure if it's worth maintaining 2.3.

# Steps to reproduce 
1. open cachet
2. click dashboard
3. login
4. observe 500 error

# Digging deeper
Line 88 `entries = array_slice($feed->channel->item, 0, 5);` seems to run into an error because $feed->channel is null.
![image](https://user-images.githubusercontent.com/2114323/68241992-b28dbf00-ffdd-11e9-91b1-5b2e348d78af.png)

When i comment out entries assignment (letting it be null to render the view) and `var_dump` the feed. I find out feed is equal to `string(1) "1" `
![image](https://user-images.githubusercontent.com/2114323/68242066-d4874180-ffdd-11e9-839c-6e31be41c5a0.png)

Adding a `var_dump($this->url)` to `Feed->latest()` shows `string(41) "https://blog.alt-three.com/tag/cachet/rss"`  Which resolves to a redirect currently.
![image](https://user-images.githubusercontent.com/2114323/68242312-4a8ba880-ffde-11e9-946f-d7e681eff460.png)

# Overall issue
I think the Feed class should have a different url registered I did a `grep` on the codebase looking for where we might register the url for Feed (other than that in class default) but was unable to find anything.  What probably made this issue just start happening now was the default url actually had something on it but now it's a redirect to a twitter account.

# Server logs
```
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: 2019/11/05 19:02:42 [error] 68#68: *40 FastCGI sent in stderr: "PHP message: [2019-11-05 19:02:42] development.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/app/Http/Controllers/Dashboard/DashboardController.php:88
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: Stack trace:
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: #0 /var/www/html/app/Http/Controllers/Dashboard/DashboardController.php(88): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/html/a...', 88, Array)
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: #1 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController->showDashboard()
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: #2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: #3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('showDashboard', Array)
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: 10.120.1.40 - - [05/Nov/2019:19:02:42 +0000] "GET /dashboard HTTP/1.1" 500 3183 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" "108.20.193.6"
Nov 05 11:02:42 status-page[cachet] cachet-85df6f7b9d-x4rrm: #4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Routing\Rou" while reading response header from upstream, client: 10.120.1.40, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "status.rediker.com"
Nov 05 11:02:43 status-page[cachet] cachet-85df6f7b9d-x4rrm: 10.120.1.40 - - [05/Nov/2019:19:02:43 +0000] "GET /favicon.ico HTTP/1.1" 200 952 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" "108.20.193.6"
Nov 05 11:02:43 status-page[cachet] cachet-85df6f7b9d-x4rrm: 10.120.1.38 - - [05/Nov/2019:19:02:43 +0000] "POST /auth/2fa HTTP/1.1" 302 396 "https://status.rediker.com/auth/2fa" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "66.189.98.66"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "NOTICE: PHP message: [2019-11-05 19:02:46] development.ERROR: ErrorException: Trying to get property of non-object in /var/www/html/app/Http/Controllers/Dashboard/DashboardController.php:88"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "Stack trace:"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "#0 /var/www/html/app/Http/Controllers/Dashboard/DashboardController.php(88): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www/html/a...', 88, Array)"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "#1 [internal function]: CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController->showDashboard()"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(80): call_user_func_array(Array, Array)"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('showDashboard', Array)"
Nov 05 11:02:46 status-page[cachet] cachet-85df6f7b9d-x4rrm: [05-Nov-2019 19:02:46] WARNING: [pool www] child 95 said into stderr: "#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Dashboard\DashboardController), Object(Illuminate\Rou..." 
```

# Mitigation
Leaving the entries assignment in the dasboard controller seems to be fine for now.

**Comment by tomecho** [comment]
FWIW i dont mind making changes to fix this issue.  Possibly setting the default url to null on Feed and returning null from latest (then handling it in dashboard controller of whatever else needs it)  I would just want someone to double check my proposed fix before i implemented it.
