### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by TutoRapide** [CachetHQ/Cachet#3885]
Hello 
I have a problem, I have a blank page. How to, fix error  ?
Ngnix: 1.16.1
debian 9
php 7.3
stamp: 2.3.9
`2019/12/07 22:05:41 [error] 43542#43542: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /usr/share/nginx/Cachet/v...PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /usr/share/nginx/Cachet/vendor/
2019/12/07 22:05:43 [error] 43542#43542: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /usr/share/nginx/Cachet/v...PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /usr/share/nginx/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /usr/share/nginx/Cachet/vendor/
`

**Comment by TutoRapide** [comment]
up
