### ISSUE TITLE
500 Error PHP 7.1

### ISSUE THREAD

**Issue by iburrows** [CachetHQ/Cachet#3892]
Hi,
I receive a 500 server error now and checking Apache logs I see:
```text
[Fri Dec 13 13:44:41.779836 2019] [php7:error] [pid 35157] [client 10.65.155.13:54076] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /opt/appl/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51\nStack trace:\n#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/opt/appl/Cache...', 51, Array)\n#1 /opt/appl/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)\n#2 /opt/appl/Cachet/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\\Exceptions\\ExceptionIdentifier->identify(Object(ErrorException))\n#3 /opt/appl/Cachet/bootstrap/cache/compiled.php(2163): GrahamCampbell\\Exceptions\\ExceptionHandler->report(Object(ErrorException))\n#4 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException(Object(ErrorException))\n#5 {main}\n  thrown in /opt/appl/Cachet/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
```
All other issues are using PHP7.2

I am using: 
PHP 7.1
Cachet 2.3.9

I also tried install Cachet 2.4 but I receive this error when running `composer install`
```text
Class 'BackupManager\Laravel\Laravel5ServiceProvider' not found
```

Thanks for any support.

**Comment by jbrooksuk** [comment]
Cachet 2.3 is not compatible with PHP 7.4
