### ISSUE TITLE
HTTP 500 error - php problem

### ISSUE THREAD

**Issue by Maxouxax** [CachetHQ/Cachet#3937]
Hey ! 
I just installed CachetHQ on my server, everything was going nice while installing, but when I tried to go the the website, I got an 500 error.

I checked the logs of nginx, and apparently it's an error with php.
Here are the logs:

```
2020/02/09 12:50:50 [error] 4356#4356: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /usr/share/nginx/html/STATUS/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in /usr/share/ng...
PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/usr/share/ngin...', 51, Array)
#1 /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /usr/share/nginx/html/STATUS/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 /usr/share/nginx/html/STATUS/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 /us
````

I did try running a `php artisan app:update` but it didn't fixed the issue.
What should I do ?

**Comment by DavidGoodwin** [comment]
probably a duplicate of https://github.com/CachetHQ/Cachet/issues/3907

Cachet doesn't support PHP 7.4 yet; you need to use PHP 7.1 :-(

**Comment by Maxouxax** [comment]
So I have to wait for Cachet to support php7.3 alright.
Thank for the answer ! :D
