### ISSUE TITLE
InvalidArgumentException: View [setup] not found.

### ISSUE THREAD

**Issue by Tealk** [CachetHQ/Cachet#3973]
Hello,
nginx FPM
PHP 7.1.33

i wanted to install at Cachet at NetCup but i get this error at the first call:
```
[2020-04-02 06:45:11] production.ERROR: InvalidArgumentException: View [setup] not found. in /httpdocs/Cachet/bootstrap/cache/compiled.php:14477
Stack trace:
#0 /httpdocs/Cachet/bootstrap/cache/compiled.php(14450): Illuminate\View\FileViewFinder->findInPaths('setup', Array)
#1 /httpdocs/Cachet/bootstrap/cache/compiled.php(14580): Illuminate\View\FileViewFinder->find('setup')
#2 /httpdocs/Cachet/bootstrap/cache/compiled.php(6325): Illuminate\View\Factory->make('setup')
#3 /httpdocs/Cachet/app/Http/Controllers/SetupController.php(129): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#4 [internal function]: CachetHQ\Cachet\Http\Controllers\SetupController->getIndex()
#5 /httpdocs/Cachet/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#6 /httpdocs/Cachet/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('getIndex', Array)
#7 /httpdocs/Cachet/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\SetupController), Object(Illuminate\Routing\Route), 'getIndex')
#8 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /httpdocs/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 /httpdocs/Cachet/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 /httpdocs/Cachet/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\SetupController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getIndex')
#14 /httpdocs/Cachet/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'getIndex')
#15 /httpdocs/Cachet/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#16 /httpdocs/Cachet/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /httpdocs/Cachet/app/Http/Middleware/SetupAlreadyCompleted.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: CachetHQ\Cachet\Http\Middleware\SetupAlreadyCompleted->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /httpdocs/Cachet/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /httpdocs/Cachet/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /httpdocs/Cachet/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#37 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /httpdocs/Cachet/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /httpdocs/Cachet/bootstrap/cache/compiled.php(13076): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#47 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /httpdocs/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /httpdocs/Cachet/bootstrap/cache/compiled.php(8219): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /httpdocs/Cachet/bootstrap/cache/compiled.php(8210): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /httpdocs/Cachet/bootstrap/cache/compiled.php(8200): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /httpdocs/Cachet/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 /httpdocs/Cachet/bootstrap/cache/compiled.php(3286): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /httpdocs/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /httpdocs/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 /httpdocs/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /httpdocs/Cachet/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /httpdocs/Cachet/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /httpdocs/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main} {"identification":{"id":"88a45609-b038-4d68-93c3-2224bc4c3fc5"}} 
[2020-04-02 06:45:11] production.ERROR: ErrorException: file_put_contents(/httpdocs/Cachet/storage/framework/sessions/556b4f504fed4a9126dd4fcc5b4cbb7a9f44bf15): failed to open stream: No such file or directory in /httpdocs/Cachet/bootstrap/cache/compiled.php:7366
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/vhosts...', 7366, Array)
#1 /httpdocs/Cachet/bootstrap/cache/compiled.php(7366): file_put_contents('/httpdocs/Cache...', 'a:4:{s:6:"_toke...', 2)
#2 /httpdocs/Cachet/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/httpdocs/Cache...', 'a:4:{s:6:"_toke...', true)
#3 /httpdocs/Cachet/bootstrap/cache/compiled.php(12133): Illuminate\Session\FileSessionHandler->write('556b4f504fed4a9...', 'a:4:{s:6:"_toke...')
#4 /httpdocs/Cachet/bootstrap/cache/compiled.php(11954): Illuminate\Session\Store->save()
#5 /httpdocs/Cachet/bootstrap/cache/compiled.php(2375): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /httpdocs/Cachet/public/index.php(57): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 {main} {"identification":{"id":"404be4c3-957d-4f99-b031-a105f99a33db"}} 
```

**Comment by jbrooksuk** [comment]
Works here on the 2.4 branch.
