### ISSUE TITLE
Getting 500 Error after installation

### ISSUE THREAD

**Issue by ProfessorVarox** [CachetHQ/Cachet#4030]
Hello everyone. I just installed Cachet but when I try to enter the config at the website the 500 Error appears again and again. I already tried `chmod -R 777`, `rm -rf bootstrap/cache/*` and `chmod -R 777 bootstrap/` but the problem exists

I tried it now on another server from another hoster but the same problem

Here is my laravel stack trace
```
Next ErrorException: Trying to access array offset on value of type null (View: /var/www/html/Cachet/resources/views/setup.blade.php) in /var/www/html/Cachet/storage/framework/views/d81ba22b4713ea3a528f05f3923a3d421ecb60db.php:151
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(44): Illuminate\View\Engines\CompilerEngine->handleViewException()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php(149): Illuminate\View\Engines\CompilerEngine->get()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php(120): Illuminate\View\View->getContents()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Http/Response.php(53): Illuminate\View\View->render()
#6 /var/www/html/Cachet/vendor/symfony/http-foundation/Response.php(201): Illuminate\Http\Response->setContent()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1085): Symfony\Component\HttpFoundation\Response->__construct()
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(94): Illuminate\Routing\Router->prepareResponse()
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}()
#10 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#11 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#12 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#13 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then()
#14 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack()
#15 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch()
#16 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Route.php(140): Illuminate\Routing\Route->runController()
#17 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\Routing\Route->run()
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#19 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#20 /var/www/html/Cachet/app/Http/Middleware/SetupAlreadyCompleted.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#21 [internal function]: CachetHQ\Cachet\Http\Middleware\SetupAlreadyCompleted->handle()
#22 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#25 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#26 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#27 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#30 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#31 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#32 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#35 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle()
#37 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#40 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#42 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#45 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle()
#47 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#51 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#52 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#53 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(699): Illuminate\Routing\Router->runRouteWithinStack()
#54 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute()
#55 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch()
#56 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#57 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func()
#58 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#59 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#60 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#62 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#63 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#64 [internal function]: Fideloper\Proxy\TrustProxies->handle()
#65 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array()
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#67 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func()
#68 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#69 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func()
#70 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then()
#71 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#72 /var/www/html/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#73 {main} {"identification":{"id":"7d3fb7cb-f055-4678-bd31-76508ab9ac16"}}
```
OS: `Debian 10`
PHP version: `7.4`
Cachet version: `v2.3.18`

Here's my .env file (passwords aren't correct in this copy)
```
APP_ENV=production
APP_DEBUG=false
APP_URL=http://status.infinity-systems.show
APP_KEY=base64:TnXEMN7p9Q1uzg/8zo8tg8ZG1QjT7e/fq6xSXgujeSo7B3KQ=

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=StatusDB
DB_USERNAME=cachet
DB_PASSWORD=uzfkIU/TIO7gfzfoi7goZGVFUZvf
DB_PORT=3306
DB_PREFIX=status_

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=smtp.webhost-02.my-host.network
MAIL_PORT=25
MAIL_USERNAME=status@infinity-systems.show
MAIL_PASSWORD=kgriurg8/)(G/GIUGiuho8hrfe
MAIL_ADDRESS=status@infinity-systems.show
MAIL_NAME="Infinity Systemstatus"
MAIL_ENCRYPTION=null

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null
```

I hope you have every infomration you need
And yes, I looked at other 500 issues but nothing worked

**Comment by MrXermon** [comment]
Jumping back to PHP 7.1 fixed it for me.

**Comment by ProfessorVarox** [comment]
Thanks, I changed to PHP 7.1 and it works now
