### ISSUE TITLE
 HTTP 500 Error

### ISSUE THREAD

**Issue by anees78692** [CachetHQ/Cachet#4046]
Hi

I'm getting a HTTP 500 Error when browsing to my new created site, before the setup wizard.

PHP Version: 7.1.33
Apache 2.4.6
Centos OS 7
Cachet 2.3.18

**Comment by PersonalDom** [comment]
I'm getting the same issue:
Cachet 2.3.18
PHP 7.3

Error: 
`#4 /ho in /home/cortexm1/public_html/domains/status.heartrp.com/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php on line 51
#3 /home/cortexm1/public_html/domains/status.heartrp.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 /home/cortexm1/public_html/domains/status.heartrp.com/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /home/cortexm1/public_html/domains/status.heartrp.com/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/home/cortexm1/...', 51, Array)
2020-06-11 18:11:24.390625 [NOTICE] [627092] [90.199.26.184:49464:HTTP2-1#APVH_status.heartrp.com:443] [STDERR] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /home/cortexm1/public_html/domains/status.heartrp.com/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
2020-06-11 18:10:23.976114 [INFO] [627092] [91.134.248.230:34810#APVH_cloudred.xyz:443] File not found [/home/cortexm1/public_html/404.shtml] 
2020-06-11 18:10:23.976069 [INFO] [627092] [91.134.248.230:34810#APVH_cloudred.xyz:443] File not found [/home/cortexm1/public_html/index.php] 
2020-06-11 17:57:36.479938 [INFO] [607616] [46.229.168.130:31516#APVH_cloudred.xyz:443] File not found [/home/cortexm1/public_html/404.shtml] 
2020-06-11 17:57:36.479894 [INFO] [607616] [46.229.168.130:31516#APVH_cloudred.xyz:443] File not found [/home/cortexm1/public_html/index.php] `

**Comment by Superkooka** [comment]
+1 👍

**Comment by Superkooka** [comment]
Juste downgrade your php version

**Comment by ItsJustMyron** [comment]
ive got the same error 

Deze pagina werkt nietpowercraftmcs.nl kan dit verzoek momenteel niet verwerken.
HTTP ERROR 500

**Comment by Superkooka** [comment]
> ive got the same error
> 
> Deze pagina werkt nietpowercraftmcs.nl kan dit verzoek momenteel niet verwerken.
> HTTP ERROR 500

Have you try to downgrade php version ?

**Comment by ItsJustMyron** [comment]
Idk how

**Comment by Dovahkiin-Warrior** [comment]
Download the 2.4 zip from here on github, extract it anywhere, upload it to your web server, then go through setup as usual. Issue seems related to command line git not grabbing required files, at least, that was my issue. Working on php 7.4.8 .

**Comment by l3d00m** [comment]
Also check the logs inside /var/www/Cachet/storage/logs, they usually contain the most helpful stuff.

**Comment by jbrooksuk** [comment]
v2.4 supports PHP 7.
