### ISSUE TITLE
v2.4 downgrade to v2.3.18

### ISSUE THREAD

**Issue by iburrows** [CachetHQ/Cachet#4058]
Hi I want to downgrade from v2.4 to v2.3.18.
I have checked out the branch and run `composer install --no-dev -o` and `php artisan app:install` but I am receiving the following error:

`[2020-07-15 12:16:40] production.ERROR: PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "scheduled_at" does not exist
LINE 1: ...ents" where ("status" > $1 or ("status" = $2 and ("scheduled...
                                                             ^ in /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php:335
Stack trace:
#0 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(335): PDOStatement->execute(Array)
#1 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'select * from "...', Array)
`

I understand that the scheduled_at column does not exist...should I drop all tables?

Thanks for the help.

**Comment by iburrows** [comment]
Ok I had to create a new database and it works now but I receive the following syntax error in views:
`Next ErrorException: Parse error: syntax error, unexpected '~', expecting ',' or ')' (View: /opt/appl/Cachet/resources/views/layout/master.blade.php) in /opt/appl/Cachet/storage/framework/views/5bfda9a107fae5724a1a7d86219a90af41ba9638.php:32
Stack trace:
#0 /opt/appl/Cachet/bootstrap/cache/compiled.php(15315): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Symfony\Component\Debug\Exception\FatalThrowableError), 2)
#1 /opt/appl/Cachet/bootstrap/cache/compiled.php(15348): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/appl/Cache...', Array)
#2 /opt/appl/Cachet/bootstrap/cache/compiled.php(15180): Illuminate\View\Engines\CompilerEngine->get('/opt/appl/Cache...', Array)
#3 /opt/appl/Cachet/bootstrap/cache/compiled.php(15168): Illuminate\View\View->getContents()
#4 /opt/appl/Cachet/bootstrap/cache/compiled.php(15152): Illuminate\View\View->renderContents()
#5 /opt/appl/Cachet/storage/framework/views/f939817306f40625f966dffffefddcb09481ffe0.php(61): Illuminate\View\View->render()
#6 /opt/appl/Cachet/bootstrap/cache/compiled.php(15311): include('/opt/appl/Cache...')
#7 /opt/appl/Cachet/bootstrap/cache/compiled.php(15348): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/appl/Cache...', Array)
#8 /opt/appl/Cachet/bootstrap/cache/compiled.php(15180): Illuminate\View\Engines\CompilerEngine->get('/opt/appl/Cache...', Array)
#9 /opt/appl/Cachet/bootstrap/cache/compiled.php(15168): Illuminate\View\View->getContents()
#10 /opt/appl/Cachet/bootstrap/cache/compiled.php(15152): Illuminate\View\View->renderContents()
#11 /opt/appl/Cachet/bootstrap/cache/compiled.php(16395): Illuminate\View\View->render()
#12 /opt/appl/Cachet/bootstrap/cache/compiled.php(15891): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 /opt/appl/Cachet/bootstrap/cache/compiled.php(8366): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#14 /opt/appl/Cachet/bootstrap/cache/compiled.php(9461): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#15 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /opt/appl/Cachet/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 /opt/appl/Cachet/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /opt/appl/Cachet/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\StatusPageController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showIndex')
#21 /opt/appl/Cachet/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'showIndex')
#22 /opt/appl/Cachet/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#23 /opt/appl/Cachet/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /opt/appl/Cachet/app/Http/Middleware/Localize.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: CachetHQ\Cachet\Http\Middleware\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /opt/appl/Cachet/app/Http/Middleware/ReadyForUse.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: CachetHQ\Cachet\Http\Middleware\ReadyForUse->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /opt/appl/Cachet/bootstrap/cache/compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /opt/appl/Cachet/bootstrap/cache/compiled.php(13400): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /opt/appl/Cachet/bootstrap/cache/compiled.php(11943): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /opt/appl/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /opt/appl/Cachet/bootstrap/cache/compiled.php(13139): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /opt/appl/Cachet/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)`

Using:
Cachet v2.3.18
PHP 7.1.33
