### ISSUE TITLE
Error running migrations

### ISSUE THREAD

**Issue by eternaltyro** [CachetHQ/Cachet#4146]
A migration fails here: 
https://github.com/CachetHQ/Cachet/blob/2.4/database/migrations/2016_02_18_085210_AlterTableMetricPointsChangeValueColumn.php

<details>
<summary>Stack Trace</summary>

```
ubuntu@ip-172-31-52-250:~/Docker$ sudo docker logs e32319c19bd2c2862efdec0f068279409104e6a2650ddf6b40edeb82ce29f005
Initializing Cachet container ...
END SUBSTITUTION
Remove empties
Attempting to connect to database ...
/usr/bin/pg_isready -h cachet1.ca3byyjcislk.us-east-1.rds.amazonaws.com -p 5432 -U hotdba -d cachet1 -t 1

Table sessions does not exist! ...
Initializing Cachet database ...
Clearing settings cache...
Settings cache cleared!
Backing up database...
Dumping database and uploading...

Successfully dumped pgsql, compressed with gzip and store it to local at /var/www/html/database/backups/2020-10-26 12.09.56
Backup completed!
Application key [base64:akCn2nObYAQZSbe4HdVxSZhaUt/Lj+L8K9kAKftNzhc=] set successfully.
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Copied Directory [/vendor/roumen/feed/src/views] To [/resources/views/vendor/feed]
Publishing complete for tag []!
[2020-10-26 12:09:57] development.ERROR: PDOException: SQLSTATE[42601]: Syntax error: 7 ERROR:  unterminated quoted string at or near "'metric_points ALTER value TYPE NUMERIC(15, 3)"
LINE 1: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3)
                    ^ in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:441
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(441): PDOStatement->execute(Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\PostgresConnection), 'ALTER TABLE 'me...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE 'me...', Array, Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\Database\Connection->run('ALTER TABLE 'me...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE 'me...')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Schema\Grammars\PostgresGrammar))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): Illuminate\Database\Schema\Builder->table('metric_points', Object(Closure))
#8 /var/www/html/database/migrations/2016_02_18_085210_AlterTableMetricPointsChangeValueColumn.php(27): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(147): AlterTableMetricPointsChangeValueColumn->up()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2016_02_18_0852...', 2, false)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('/var/www/html/d...', Array)
#13 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/html/vendor/graham-campbell/core/src/Subscribers/CommandSubscriber.php(113): Illuminate\Console\Command->call('migrate', Array)
#20 [internal function]: GrahamCampbell\Core\Subscribers\CommandSubscriber->onRunMigrations(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#24 /var/www/html/vendor/graham-campbell/core/src/Console/Commands/AppInstall.php(71): Illuminate\Events\Dispatcher->fire('command.runmigr...', Array)
#25 [internal function]: GrahamCampbell\Core\Console\Commands\AppInstall->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#28 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(GrahamCampbell\Core\Console\Commands\AppInstall), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42601]: Syntax error: 7 ERROR:  unterminated quoted string at or near "'metric_points ALTER value TYPE NUMERIC(15, 3)"
LINE 1: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3)
                    ^ (SQL: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3)) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('ALTER TABLE 'me...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(442): Illuminate\Database\Connection->run('ALTER TABLE 'me...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(83): Illuminate\Database\Connection->statement('ALTER TABLE 'me...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(229): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Database\PostgresConnection), Object(Illuminate\Database\Schema\Grammars\PostgresGrammar))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(130): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\Schema\Blueprint))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): Illuminate\Database\Schema\Builder->table('metric_points', Object(Closure))
#6 /var/www/html/database/migrations/2016_02_18_085210_AlterTableMetricPointsChangeValueColumn.php(27): Illuminate\Support\Facades\Facade::__callStatic('table', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(147): AlterTableMetricPointsChangeValueColumn->up()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(117): Illuminate\Database\Migrations\Migrator->runUp('2016_02_18_0852...', 2, false)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(86): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(76): Illuminate\Database\Migrations\Migrator->run('/var/www/html/d...', Array)
#11 [internal function]: Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(185): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#17 /var/www/html/vendor/graham-campbell/core/src/Subscribers/CommandSubscriber.php(113): Illuminate\Console\Command->call('migrate', Array)
#18 [internal function]: GrahamCampbell\Core\Subscribers\CommandSubscriber->onRunMigrations(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(GrahamCampbell\Core\Console\Commands\AppInstall))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#22 /var/www/html/vendor/graham-campbell/core/src/Console/Commands/AppInstall.php(71): Illuminate\Events\Dispatcher->fire('command.runmigr...', Array)
#23 [internal function]: GrahamCampbell\Core\Console\Commands\AppInstall->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#26 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(GrahamCampbell\Core\Console\Commands\AppInstall), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 {main} {"identification":{"id":"17c289a8-b3b5-4424-98a0-bcee669e355a"}}



  [Illuminate\Database\QueryException]
  SQLSTATE[42601]: Syntax error: 7 ERROR:  unterminated quoted string at or near "'metric_points ALTER value TYPE NUMERIC(15, 3)"
  LINE 1: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3)
                      ^ (SQL: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3))



  [PDOException]
  SQLSTATE[42601]: Syntax error: 7 ERROR:  unterminated quoted string at or near "'metric_points ALTER value TYPE NUMERIC(15, 3)"
  LINE 1: ALTER TABLE 'metric_points ALTER value TYPE NUMERIC(15, 3)
                      ^
```
</details>

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
