### ISSUE TITLE
Class \BackupManager\Laravel\Laravel5ServiceProvider not found

### ISSUE THREAD

**Issue by GSIMCOX524** [CachetHQ/Cachet#4159]
I'm attempting to install on Amazon Linux 2 (AWS Lightsail instance) with PHP 7.3, Apache, and using various versions of Cachet. I've tried 2.4, 2.3.18, and 2.3 on PHP 7.2. Here's the error I continue to encounter when running `php artisan app:install` or `php artisan app:update` – any help is greatly appreciated! 😄 

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'BackupManager\Laravel\Laravel5ServiceProvider' not found in /var/www/Cachet/boo
tstrap/cache/compiled.php:7651
Stack trace:
#0 /var/www/Cachet/bootstrap/cache/compiled.php(7637): Illuminate\Foundation\ProviderRepository->createProvider('BackupManager\\L...')
#1 /var/www/Cachet/bootstrap/cache/compiled.php(7613): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /var/www/Cachet/bootstrap/cache/compiled.php(1802): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /var/www/Cachet/bootstrap/cache/compiled.php(2220): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /var/www/Cachet/bootstrap/cache/compiled.php(1666): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /var/www/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /var/www/Cachet/vendor/laravel/fr in /var/www/Cachet/bootstrap/cache/compiled.php on line 7651`

**Comment by GSIMCOX524** [comment]
**UPDATE:** I resolved this issue, and here's how if anyone else experiences the same: 

`rm -rf /var/www/Cachet/bootstrap/cache`
`php artisan app:update`

These two commands seem to be the universal fix for all things Cachet 😄
