### ISSUE TITLE
Error installing Cachet

### ISSUE THREAD

**Issue by denisvjcr** [cachethq/cachet#4264]
I'm installing Cachet ( v2.3.4 ) and when I run "php artisan app:update" I got this:

PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:794
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(774): Illuminate\Container\Container->getDependencies()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(230): Illuminate\Foundation\Application->make()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Container\Container->Illuminate\Container\{closure}()
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make()
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make()
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#11 {main}
  thrown in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 794
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:794
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(794): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(774): Illuminate\Container\Container->getDependencies()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(230): Illuminate\Foundation\Application->make()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Container\Container->Illuminate\Container\{closure}()
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Container\Container->build()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make()
#8 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make()
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#11 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#12 {main}
  thrown in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 794

Any idea what is causing this ?

Thanks  !

**Comment by denisvjcr** [comment]
Found I have installed php 8.0 and that was causing that error ,  downgrade to 7 and now it works.
