### ISSUE TITLE
Error 500 on homepage

### ISSUE THREAD

**Issue by goodgunner** [cachethq/cachet#4292]
whenever i compose the docker containers it gives me error 500 on the homepage. what could be the cause of this?

**Comment by pavog** [comment]
Hi, can you please share your configuration (.env file), your logs and your console output? We might be able to help you more with that.

**Comment by sipmann** [comment]
I'm having the same issue on a fresh install o windows.

Bellow the error log and the .env file.

```log
Laravel development server started on http://localhost:8000/
[Mon Jul 12 07:52:20 2021] PHP 7.4.12 Development Server (http://localhost:8000) started
[Mon Jul 12 07:52:21 2021] [::1]:50410 Accepted
[Mon Jul 12 07:52:21 2021] [::1]:56294 Accepted
[Mon Jul 12 07:52:21 2021] [::1]:50410 Closing
[Mon Jul 12 07:52:21 2021] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'D:\\projetos\\Cac...', 51, Array)
#1 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 D:\projetos\Cachet\bootstrap\cache\compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
[Mon Jul 12 07:52:21 2021] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'D:\\projetos\\Cac...', 51, Array)
#1 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 D:\projetos\Cachet\bootstrap\cache\compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 D:\projetos\Cachet\bootstrap\cache\compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 [inte in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
[Mon Jul 12 07:52:21 2021] [::1]:56294 Closing
[Mon Jul 12 07:52:23 2021] [::1]:61210 Accepted
[Mon Jul 12 07:52:23 2021] [::1]:54891 Accepted
[Mon Jul 12 07:52:23 2021] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'D:\\projetos\\Cac...', 51, Array)
#1 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 D:\projetos\Cachet\bootstrap\cache\compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main}
  thrown in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
[Mon Jul 12 07:52:23 2021] PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', 'D:\\projetos\\Cac...', 51, Array)
#1 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php(51): count(NULL)
#2 D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#3 D:\projetos\Cachet\bootstrap\cache\compiled.php(2163): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#4 D:\projetos\Cachet\bootstrap\cache\compiled.php(2181): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#5 [inte in D:\projetos\Cachet\vendor\graham-campbell\exceptions\src\ExceptionIdentifier.php on line 51
[Mon Jul 12 07:52:23 2021] [::1]:61210 Closing
[Mon Jul 12 07:53:28 2021] [::1]:54891 Closed without sending a request; it was probably just an unused speculative preconnection
[Mon Jul 12 07:53:28 2021] [::1]:54891 Closing
```


```ini
APP_ENV=production
APP_DEBUG=false
APP_URL=http://localhost
APP_KEY=base64:uKoTTCciXTlcWebbyvNse1d9s6R1a033VhKnbFsihdI=

DB_DRIVER=mysql
DB_HOST=localhost
DB_DATABASE=cachet
DB_USERNAME=root
DB_PASSWORD=
DB_PORT=null
DB_PREFIX=null

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHET_EMOJI=false

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ADDRESS=null
MAIL_NAME=null
MAIL_ENCRYPTION=tls

REDIS_HOST=null
REDIS_DATABASE=null
REDIS_PORT=null

GITHUB_TOKEN=null

```

**Comment by pavog** [comment]
Hi @sipmann, I would like to help you solve the problem.
For this I need some more information from you, like: 

- Which version of php are you using?
- What version of cachet are you using? 
- Are you running cachet from a local webserver, from a docker container or somehow else? 
- What is your setup and which software in which version are you using?

Maybe some answers from #4132 or #2862 can help you, but unfortunately there is no "official" fix for this problem, at least if you are already using the latest version of cachet. If not, this could be the problem.

**Comment by sipmann** [comment]
Actually #4132 solved the problem 😃  ty

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
