### ISSUE TITLE
Impossible to load setup page after installation

### ISSUE THREAD

**Issue by Tsuna77** [cachethq/cachet#4305]
Hello there,

I'm trying to install cachethq 2.4. I follow all the installation documentation but when I need to go to the setup page, something went wrong :(

I check about mod_rewrite, it's working without any problem (tested with this tool : https://docs.boltcms.io/howto/making-sure-htaccess-works )

When I go to the laravel.log I got those stacktrace : 

```
[2021-10-01 20:25:23] production.NOTICE: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:179
Stack trace:
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\RouteCollection->match()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->findRoute()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\Routing\Router->dispatchToRoute()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#8 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle()
#10 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#11 /var/www/html/Cachet/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#12 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\Cors\HandlePreflight->handle()
#13 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#14 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}()
#15 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then()
#16 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#17 /var/www/html/Cachet/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle()
#18 {main} {"identification":{"id":"6befefff-c350-465f-bc4e-44ebe6b6cd10"},"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0):  at /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:179)
[stacktrace]
#0 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\RouteCollection->match()
#1 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->findRoute()
#2 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute()
#3 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#4 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#5 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#6 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#7 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/Cachet/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#9 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle()
#10 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/html/Cachet/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#12 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Cors\\HandlePreflight->handle()
#13 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#16 /var/www/html/Cachet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#17 /var/www/html/Cachet/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()
#18 {main}
"}
```

does someone have a clue about how to finish my installation please ?

System info : 
OS : Fedora server 34
httpd : Apache/2.4.49 (Fedora) Built Sep 16 2021
php : 7.4.24 Zend engine v3.4.0
cachet commit id : cf86f65f1dabf283d001d0f5d380f26dd5cfb64c

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
