### ISSUE TITLE
ReflectionParameter deprecated

### ISSUE THREAD

**Issue by nobicycle** [cachethq/cachet#4320]
During composer install:
```
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1911
Stack trace:
#0 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Support/Collection.php(42): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /srv/http/cachet/vendor/composer/ClassLoader.php(571): include('...')
#2 /srv/http/cachet/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Composer\Autoload\ClassLoader->loadClass()
#4 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(123): collect()
#5 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(97): Illuminate\Foundation\PackageManifest->build()
#6 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(80): Illuminate\Foundation\PackageManifest->getManifest()
#7 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#8 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#9 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illuminate\Foundation\Application->bootstrapWith()
#10 /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 /srv/http/cachet/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#12 {main} in /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 42
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /srv/http/cachet/vendor/laravel/framework/src/Illuminate/Container/Container.php:838
Stack trace:

```

PHP 8.1.3 (cli) (built: Feb 16 2022 13:27:56) (NTS)

Regards

**Comment by jbrooksuk** [comment]
Cachet 2.x isn't compatible with 8.1
