### ISSUE TITLE
Doesn't install anymore 2.4.1

### ISSUE THREAD

**Issue by markovanderpuil** [cachethq/cachet#4367]
Hi James,

Not to bust your balls or anything but are you aware that right now cachet doesn't install anymore?

```
$ composer install --no-dev -o
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Package alt-three/bus is abandoned, you should avoid using it. No replacement was suggested.
Package alt-three/validator is abandoned, you should avoid using it. No replacement was suggested.
Package barryvdh/laravel-cors is abandoned, you should avoid using it. No replacement was suggested.
Package chillerlan/php-traits is abandoned, you should avoid using it. No replacement was suggested.
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package laravel/nexmo-notification-channel is abandoned, you should avoid using it. Use laravel/vonage-notification-channel instead.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Package symfony/debug is abandoned, you should avoid using it. Use symfony/error-handler instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package alt-three/testbench is abandoned, you should avoid using it. No replacement was suggested.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
Carbon 1 is deprecated, see how to migrate to Carbon 2.
https://carbon.nesbot.com/docs/#api-carbon-2
    You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Deprecation Notice: Return type of Illuminate\Container\Container::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php:1209
Deprecation Notice: Return type of Illuminate\Container\Container::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php:1220
Deprecation Notice: Return type of Illuminate\Container\Container::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php:1232
Deprecation Notice: Return type of Illuminate\Container\Container::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php:1245
> @php artisan package:discover
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Support\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1911
Stack trace:
#0 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Support/Collection.php(42): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /opt/cachethq/vendor/composer/ClassLoader.php(576): include('...')
#2 /opt/cachethq/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#3 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Composer\Autoload\ClassLoader->loadClass()
#4 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(123): collect()
#5 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(97): Illuminate\Foundation\PackageManifest->build()
#6 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(80): Illuminate\Foundation\PackageManifest->getManifest()
#7 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\Foundation\PackageManifest->aliases()
#8 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(211): Illuminate\Foundation\Bootstrap\RegisterFacades->bootstrap()
#9 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(297): Illuminate\Foundation\Application->bootstrapWith()
#10 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(120): Illuminate\Foundation\Console\Kernel->bootstrap()
#11 /opt/cachethq/artisan(35): Illuminate\Foundation\Console\Kernel->handle()
#12 {main} in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 42
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php:838
Stack trace:
#0 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(838): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(807): Illuminate\Container\Container->resolveDependencies()
#2 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#3 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
#4 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make()
#5 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(264): Illuminate\Foundation\Application->make()
#6 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Container\Container->Illuminate\Container\{closure}()
#7 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\Container\Container->build()
#8 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\Container\Container->resolve()
#9 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\Container\Container->make()
#10 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(159): Illuminate\Foundation\Application->make()
#11 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#12 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(87): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#13 /opt/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#14 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#15 {main}
  thrown in /opt/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 838
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255
```

**Comment by markovanderpuil** [comment]
Skip this, I was using PHP 8.1 - Maybe it works on PHP 7.4.
