### ISSUE TITLE
Deploy to Heroku button not working - rev-manifest.json

### ISSUE THREAD

**Issue by devcare** [cachethq/Cachet#440]
After deploying to Heroku with the button, the app setup page tells: "Whoops, looks like something went wrong.".

The heroku logs show:
```
2015-01-29T12:59:36.428711+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428716+00:00 app[web.1]: #30 /app/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428714+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428722+00:00 app[web.1]: #34 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-29T12:59:36.428723+00:00 app[web.1]: #35 {main}
2015-01-29T12:59:36.428719+00:00 app[web.1]: #32 /app/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428720+00:00 app[web.1]: #33 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428725+00:00 app[web.1]: 
2015-01-29T12:59:36.428733+00:00 app[web.1]: Next exception 'ErrorException' with message 'file_get_contents(/app/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /app/app/views/partials/dashboard/head.blade.php)' in /app/src/helpers.php:22
2015-01-29T12:59:36.428717+00:00 app[web.1]: #31 /app/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428710+00:00 app[web.1]: #26 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428713+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428734+00:00 app[web.1]: Stack trace:
2015-01-29T12:59:36.428736+00:00 app[web.1]: #0 /app/bootstrap/compiled.php(9869): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
2015-01-29T12:59:36.428737+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428740+00:00 app[web.1]: #3 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428739+00:00 app[web.1]: #2 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428742+00:00 app[web.1]: #4 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428743+00:00 app[web.1]: #5 /app/app/storage/views/70e5f56f4af9ea202e409f018723c280(3): Illuminate\View\View->render()
2015-01-29T12:59:36.428745+00:00 app[web.1]: #6 /app/bootstrap/compiled.php(9867): include('/app/app/storag...')
2015-01-29T12:59:36.428746+00:00 app[web.1]: #7 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428748+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428749+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428751+00:00 app[web.1]: #10 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428754+00:00 app[web.1]: #12 /app/bootstrap/compiled.php(9867): include('/app/app/storag...')
2015-01-29T12:59:36.428759+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428752+00:00 app[web.1]: #11 /app/app/storage/views/5c4c19aa9324ac3ec5b98a845cc1ae7c(157): Illuminate\View\View->render()
2015-01-29T12:59:36.428756+00:00 app[web.1]: #13 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428758+00:00 app[web.1]: #14 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428761+00:00 app[web.1]: #16 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428762+00:00 app[web.1]: #17 /app/bootstrap/compiled.php(10425): Illuminate\View\View->render()
2015-01-29T12:59:36.428763+00:00 app[web.1]: #18 /app/bootstrap/compiled.php(9955): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
2015-01-29T12:59:36.428765+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(5245): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
2015-01-29T12:59:36.428766+00:00 app[web.1]: #20 /app/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428768+00:00 app[web.1]: #21 /app/bootstrap/compiled.php(5054): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428769+00:00 app[web.1]: #22 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428771+00:00 app[web.1]: #23 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428772+00:00 app[web.1]: #24 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428774+00:00 app[web.1]: #25 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428776+00:00 app[web.1]: #26 /app/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428777+00:00 app[web.1]: #27 /app/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428779+00:00 app[web.1]: #28 /app/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428780+00:00 app[web.1]: #29 /app/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428782+00:00 app[web.1]: #30 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-29T
12:59:36.428783+00:00 app[web.1]: #31 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-29T12:59:36.428800+00:00 app[web.1]: 
2015-01-29T12:59:36.428798+00:00 app[web.1]: #32 {main}
2015-01-29T12:59:36.428802+00:00 app[web.1]: Next exception 'ErrorException' with message 'file_get_contents(/app/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /app/app/views/partials/dashboard/head.blade.php) (View: /app/app/views/partials/dashboard/head.blade.php)' in /app/src/helpers.php:22
2015-01-29T12:59:36.428803+00:00 app[web.1]: Stack trace:
2015-01-29T12:59:36.428808+00:00 app[web.1]: #0 /app/bootstrap/compiled.php(9869): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
2015-01-29T12:59:36.428810+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428811+00:00 app[web.1]: #2 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428812+00:00 app[web.1]: #3 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428814+00:00 app[web.1]: #4 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428815+00:00 app[web.1]: #5 /app/app/storage/views/5c4c19aa9324ac3ec5b98a845cc1ae7c(157): Illuminate\View\View->render()
2015-01-29T12:59:36.428818+00:00 app[web.1]: #6 /app/bootstrap/compiled.php(9867): include('/app/app/storag...')
2015-01-29T12:59:36.428820+00:00 app[web.1]: #8 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428822+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428823+00:00 app[web.1]: #10 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428825+00:00 app[web.1]: #11 /app/bootstrap/compiled.php(10425): Illuminate\View\View->render()
2015-01-29T12:59:36.428826+00:00 app[web.1]: #12 /app/bootstrap/compiled.php(9955): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
2015-01-29T12:59:36.428819+00:00 app[web.1]: #7 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428828+00:00 app[web.1]: #13 /app/bootstrap/compiled.php(5245): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
2015-01-29T12:59:36.428829+00:00 app[web.1]: #14 /app/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428832+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(5054): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428844+00:00 app[web.1]: #23 /app/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428838+00:00 app[web.1]: #19 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428835+00:00 app[web.1]: #17 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428846+00:00 app[web.1]: #24 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428847+00:00 app[web.1]: #25 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-29T12:59:36.428848+00:00 app[web.1]: #26 {main}
2015-01-29T12:59:36.428850+00:00 app[web.1]: 
2015-01-29T12:59:36.428852+00:00 app[web.1]: Next exception 'ErrorException' with message 'file_get_contents(/app/public/build/rev-manifest.json): failed to open stream: No such file or directory (View: /app/app/views/partials/dashboard/head.blade.php) (View: /app/app/views/partials/dashboard/head.blade.php) (View: /app/app/views/partials/dashboard/head.blade.php)' in /app/src/helpers.php:22
2015-01-29T12:59:36.428853+00:00 app[web.1]: Stack trace:
2015-01-29T12:59:36.428854+00:00 app[web.1]: #0 /app/bootstrap/compiled.php(9869): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 0)
2015-01-29T12:59:36.428841+00:00 app[web.1]: #21 /app/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428859+00:00 app[web.1]: #1 /app/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/app/app/storag...', Array)
2015-01-29T12:59:36.428875+00:00 app[web.1]: #7 /app/bootstrap/compiled.php(5245): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
2015-01-29T12:59:36.428833+00:00 app[web.1]: #16 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428864+00:00 app[web.1]: #5 /app/bootstrap/compiled.php(10425): Illuminate\View\View->render()
2015-01-29T12:59:36.428881+00:00 app[web.1]: #8 /app/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428860+00:00 app[web.1]: #2 /app/bootstrap/compiled.php(9745): Illuminate\View\Engines\CompilerEngine->get('/app/app/config...', Array)
2015-01-29T12:59:36.428882+00:00 app[web.1]: #9 /app/bootstrap/compiled.php(5054): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
2015-01-29T12:59:36.428836+00:00 app[web.1]: #18 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428884+00:00 app[web.1]: #10 /app/bootstrap/compiled.php(5040): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428861+00:00 app[web.1]: #3 /app/bootstrap/compiled.php(9732): Illuminate\View\View->getContents()
2015-01-29T12:59:36.428886+00:00 app[web.1]: #11 /app/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428840+00:00 app[web.1]: #20 /app/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428843+00:00 app[web.1]: #22 /app/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428887+00:00 app[web.1]: #12 /app/bootstrap/compiled.php(715): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428889+00:00 app[web.1]: #13 /app/bootstrap/compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428890+00:00 app[web.1]: #14 /app/bootstrap/compiled.php(7812): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428892+00:00 app[web.1]: #15 /app/bootstrap/compiled.php(8419): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428894+00:00 app[web.1]: #16 /app/bootstrap/compiled.php(8366): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428895+00:00 app[web.1]: #17 /app/bootstrap/compiled.php(11029): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
2015-01-29T12:59:36.428896+00:00 app[web.1]: #18 /app/bootstrap/compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
2015-01-29T12:59:36.428898+00:00 app[web.1]: #19 /app/public/index.php(48): Illuminate\Foundation\Application->run()
2015-01-29T12:59:36.428863+00:00 app[web.1]: #4 /app/bootstrap/compiled.php(9723): Illuminate\View\View->renderContents()
2015-01-29T12:59:36.428873+00:00 app[web.1]: #6 /app/bootstrap/compiled.php(9955): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
```

**Comment by jbrooksuk** [comment]
That means some of the assets aren't compiling. I'll have a look.

**Comment by jbrooksuk** [comment]
Everything compiled fine locally. I'll watch the output on deploy to Heroku.

**Comment by jbrooksuk** [comment]
Can you pull down and try again please.

**Comment by 0147500** [comment]
Will do asap atm getting to home
________________________________

**Comment by liamn** [comment]
I experienced this bug earlier, just used the Heroku button again and everything seems to be working now.

**Comment by jbrooksuk** [comment]
Heroku is always so problematic.

**Comment by 0147500** [comment]
That's seems to fix it for me. :D thx!

**Comment by devcare** [comment]
Thanks for your fix.
