### ISSUE TITLE
Server error when trying to add component without component group

### ISSUE THREAD

**Issue by EdeMeijer** [cachethq/Cachet#606]
When there are any component groups in the system, and you try to add a new component without selecting a component group from the dropdown, you get a `Whoops, looks like something went wrong.` 500 internal server error. I expected it should actually be possible to add components without groups, since you can also add components if there are no component groups in the system at all.

**Comment by jbrooksuk** [comment]
Is this when you use the API?

**Comment by jbrooksuk** [comment]
Also, what database server are you using?

**Comment by EdeMeijer** [comment]
This is when using the Dashboard. It happens in my Docker + Postgres setup as well as on the demo site.

**Comment by jbrooksuk** [comment]
This doesn't occur under `master`. Can you update please.

**Comment by EdeMeijer** [comment]
I updated to master but it still happens. It also still happens on the demo page, but I'm not sure if that one is up to date.

I'll try to describe exactly what to do in order to reproduce this bug
- Make sure there is at least 1 component group added to the system
- Create a new component. Give it a name, maybe a description, but **not** a  component group
- Try to save the component. You will see a 500 error.

I checked the logs and found the exception. The problem is that the page tries to insert a component with an empty component group ID, and Postgres doesn't like that. It should be NULL instead.

```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "" (SQL: insert into "components" ("order", "group_id", "description", "link", "name", "status", "user_id", "updated_at", "created_at") values (0, , , , test, 1, 1, 2015-05-11 11:10:23, 2015-05-11 11:10:23) returning "id")' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): Illuminate\Database\Connection->runQueryCallback('insert into "co...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(297): Illuminate\Database\Connection->run('insert into "co...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(272): Illuminate\Database\Connection->select('insert into "co...', Array, false)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/PostgresProcessor.php(18): Illuminate\Database\Connection->selectFromWriteConnection('insert into "co...', Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1718): Illuminate\Database\Query\Processors\PostgresProcessor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into "co...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(933): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/compiled.php(9897): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/html/vendor/compiled.php(9897): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /var/www/html/vendor/compiled.php(9887): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /var/www/html/vendor/compiled.php(9844): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/vendor/compiled.php(9485): Illuminate\Database\Eloquent\Model->save()
#12 /var/www/html/app/Http/Controllers/Admin/ComponentController.php(192): Illuminate\Database\Eloquent\Model::create(Array)
#13 [internal function]: CachetHQ\Cachet\Http\Controllers\Admin\ComponentController->createComponentAction()
#14 /var/www/html/vendor/compiled.php(8373): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/compiled.php(8440): Illuminate\Routing\Controller->callAction('createComponent...', Array)
#16 /var/www/html/vendor/compiled.php(8419): Illuminate\Routing\ControllerDispatcher->call(Object(CachetHQ\Cachet\Http\Controllers\Admin\ComponentController), Object(Illuminate\Routing\Route), 'createComponent...')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/html/vendor/compiled.php(9053): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/html/vendor/compiled.php(9036): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/www/html/vendor/compiled.php(8420): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/www/html/vendor/compiled.php(8406): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(CachetHQ\Cachet\Http\Controllers\Admin\ComponentController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'createComponent...')
#23 /var/www/html/vendor/compiled.php(7404): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'CachetHQ\\Cachet...', 'createComponent...')
#24 /var/www/html/vendor/compiled.php(7375): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /var/www/html/vendor/compiled.php(7041): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/html/vendor/compiled.php(9053): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /var/www/html/app/Http/Middleware/Authenticate.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/html/vendor/compiled.php(9045): CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/html/vendor/compiled.php(9036): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /var/www/html/vendor/compiled.php(7042): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /var/www/html/vendor/compiled.php(7031): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#34 /var/www/html/vendor/compiled.php(7016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 /var/www/html/vendor/compiled.php(1989): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/vendor/compiled.php(9053): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/html/vendor/compiled.php(12202): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /var/www/html/vendor/compiled.php(9045): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /var/www/html/vendor/compiled.php(10903): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/html/vendor/compiled.php(9045): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/html/vendor/compiled.php(11908): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/html/vendor/compiled.php(9045): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/html/vendor/compiled.php(11857): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /var/www/html/vendor/compiled.php(9045): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /var/www/html/vendor/compiled.php(2532): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/html/vendor/compiled.php(9045): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/vendor/compiled.php(9045): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/vendor/compiled.php(9036): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /var/www/html/vendor/compiled.php(1945): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/html/vendor/compiled.php(1932): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /var/www/html/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}  
```
