### ISSUE TITLE
mcrypt cipher issue

### ISSUE THREAD

**Issue by bimlendu** [cachethq/Cachet#692]
I was having this issue in Cachet. Not sure after which specific commit. 

```
[2015-06-08 07:49:49] production.ERROR: exception 'ErrorException' with message 'mcrypt_get_iv_size(): Module initialization failed' in /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:303
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mcrypt_get_iv_s...', '/usr/share/ngin...', 303, Array)
#1 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(303): mcrypt_get_iv_size('AES-256-CBC', 'cbc')
#2 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(280): Illuminate\Encryption\Encrypter->updateBlockSize()
#3 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(20): Illuminate\Encryption\Encrypter->setCipher('AES-256-CBC')
#4 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(762): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(645): Illuminate\Container\Container->build(Object(Closure), Array)
#6 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(651): Illuminate\Container\Container->make('encrypter', Array)
#7 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(876): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#8 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(837): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#9 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(802): Illuminate\Container\Container->getDependencies(Array, Array)
#10 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Container/Container.php(645): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#11 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(651): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#12 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(126): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#13 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): call_user_func_array(Array, Array)
#16 /usr/share/nginx/html/cachethq/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(127): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(101): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(123): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /usr/share/nginx/html/cachethq/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /usr/share/nginx/html/cachethq/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}
```

I was able to fix it by changing the cipher to `rijndael-256`, in `config/app.php`. Not sure if it is correct to change this, but it fixed my installation. Do you think this is related to Laravel upgrade? http://laravel.com/docs/master/upgrade.

**Comment by jbrooksuk** [comment]
Thanks, I'll take a look at this.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/cachethq/Cachet/pull/660
