### ISSUE TITLE
Getting logged out when saving an incident.

### ISSUE THREAD

**Issue by rand0mb1ts** [cachethq/Cachet#772]
Upon various tasks the system seems to think I have been logged out.  I'm not sure what the issue is.  I have tried changing the cache and session drivers from file to redis.  I have also manually cleared the cache/session/views in storage/framework.  Here is a stack trace. (I had logged in less than 2 minutes before and tried to create an incident with ALL fields filled.) 

```
production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\HttpException' in /var/www/technology-status/app/Http/Middleware/Authenticate.php:48
Stack trace:
#0 [internal function]: CachetHQ\Cachet\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#3 /var/www/technology-status/bootstrap/cache/compiled.php(9437): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#4 /var/www/technology-status/bootstrap/cache/compiled.php(7384): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#5 /var/www/technology-status/bootstrap/cache/compiled.php(7372): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#6 /var/www/technology-status/bootstrap/cache/compiled.php(7357): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 /var/www/technology-status/bootstrap/cache/compiled.php(2066): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/technology-status/bootstrap/cache/compiled.php(9455): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /var/www/technology-status/bootstrap/cache/compiled.php(12699): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#13 /var/www/technology-status/bootstrap/cache/compiled.php(11348): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#16 /var/www/technology-status/bootstrap/cache/compiled.php(12437): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#19 /var/www/technology-status/bootstrap/cache/compiled.php(12376): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#22 /var/www/technology-status/bootstrap/cache/compiled.php(2687): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#25 /var/www/technology-status/vendor/fideloper/proxy/src/TrustProxies.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/technology-status/bootstrap/cache/compiled.php(9447): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/technology-status/bootstrap/cache/compiled.php(9437): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /var/www/technology-status/bootstrap/cache/compiled.php(2013): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /var/www/technology-status/bootstrap/cache/compiled.php(1999): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#32 /var/www/technology-status/public/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#33 {main}

**Comment by jenolan** [comment]
I am being logged out about every two admin actions, though at the moment my connection is 64k

**Comment by jbrooksuk** [comment]
Does this occur for you on our demo?

- https://demo.cachethq.io/dashboard
- test@test.com
- test123

**Comment by rand0mb1ts** [comment]
Nope, the demo is working as it should.  I tried my install again this morning and it seems to be working (I didn't change anything). Maybe a sysadmin or networking guy was working on something.

Cachet is great and I'm excited it's working. Thanks for your time!

**Comment by jbrooksuk** [comment]
:)
