### ISSUE TITLE
PDOException Exception only in Status page

### ISSUE THREAD

**Issue by ephillipe** [cachethq/Cachet#917]
I'm try run Cachet [1.1.1 / 1.2.0] with Docker on AWS.
When I access Status page, I get below error. If I access Dashboard, I don't.

I using Cachet with Postgres 9.3 but **Status page** is trying connect with MySQL.

```
[2015-08-17 16:55:33] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'dntpg.ccclxkqkknpp.us-east-1.rds.amazonaws.com' (4)' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:50
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(50): PDO->__construct('mysql:host=dntp...', 'cachet', 'abc123Aa', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(22): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=dntp...', Array, Array)
#2 /var/www/html/bootstrap/cache/compiled.php(10985): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /var/www/html/bootstrap/cache/compiled.php(10981): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /var/www/html/bootstrap/cache/compiled.php(10896): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 /var/www/html/bootstrap/cache/compiled.php(10851): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(110): Illuminate\Database\DatabaseManager->connection('mysql')
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Failed/DatabaseFailedJobProvider.php(58): Illuminate\Queue\Failed\DatabaseFailedJobProvider->getTable()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(239): Illuminate\Queue\Failed\DatabaseFailedJobProvider->log('database', 'default', '{"job":"mailer@...')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(201): Illuminate\Queue\Worker->logFailedJob('database', Object(Illuminate\Queue\Jobs\DatabaseJob))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '3', 0)
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(109): Illuminate\Queue\Worker->pop(NULL, NULL, 0, '3', '3')
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(71): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, NULL, 0, 128, false)
#13 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#14 /var/www/html/bootstrap/cache/compiled.php(966): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(149): Illuminate\Container\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(259): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(135): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(878): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(100): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main} {"identification":{"id":"4254532e-66e6-4cd2-a575-6613e0ede004"}}
```

My Docker with environment variables. 
Can be noted my DB_DRIVER is **pgsql**.

```ini
DB_HOST=******.us-east-1.rds.amazonaws.com
HOSTNAME=******
DB_DRIVER=pgsql
APP_URL=http://******.elasticbeanstalk.com
CACHE_DRIVER=database
MANDRILL_SECRET=******
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DB_DATABASE=cachet
PWD=/var/www/html
DB_PASSWORD=******
NR_INSTALL_SILENT=true
MAIL_ADDRESS=******@alterdata.com.br
APP_DEBUG=true
MAIL_NAME=Erick Almeida
APP_KEY=1qsHvtSFHWAFgCwXDqglSyBtcbtzxn99
SHLVL=1
HOME=/root
DB_USERNAME=cachet
MAIL_DRIVER=mandrill
NR_INSTALL_KEY=******
```

**Comment by ephillipe** [comment]
Any ideas?

**Comment by rtrauntvein** [comment]
It appears to be unable to connect to the MySQL instance - make sure you have created a sql user and allow the cachet host to connect to it..

**Comment by jbrooksuk** [comment]
You're confusing things here...

> I using Cachet with **Postgres 9.3** but Status page is trying connect with MySQL.

> Can be noted my DB_DRIVER is pgsql.

Cachet won't connect to MySQL unless you're telling it too. Run `php artisan config:cache`.

**Comment by jbrooksuk** [comment]
@ephillipe I'm pretty sure that this is a misconfiguration on your part. If not, please re-open the issue.
